/** English is the primary dictionary. Keep it first and complete for every key. */
export const en = {
  'menu.aria': 'Task actions',
  'menu.accept': 'Accept…',
  'menu.acceptSelected': 'Accept selected…',
  'menu.openEditor': 'Open the task copy in the editor',
  'menu.revealFinder': 'Reveal in Finder',
  'menu.return': 'Send back with reason…',
  'menu.report': 'Open report and checks',
  'menu.launch': 'Launch',
  'menu.launchWorker': 'Launch with worker',
  'menu.direction': 'Give direction…',
  'menu.relaunch': 'Relaunch with context…',
  'menu.ledger': 'Run ledger',
  'menu.changes': 'Changed files',
  'menu.contract': 'Contract',
  'menu.highlight': 'Highlight chain',
  'menu.showGraph': 'Show on graph',
  'menu.follow': 'Follow-up task…',
  'menu.askAgent': 'Ask the agent to plan follow-ups',
  'menu.chatPrompt': 'Propose follow-up tasks for this task and its review findings.',
  'menu.chatTask': 'Task',
  'menu.chatVerdict': 'Verdict',
  'menu.chatReport': 'Report',
  'menu.chatFindings': 'Findings',
  'menu.chatUnknown': 'unknown',
  'menu.chatNoReport': 'No report yet.',
  'menu.chatNone': 'None recorded.',
  'menu.chatTool': 'Use orchestra_task_upsert, or prepare a plan draft for a larger set.',
  'menu.copyLink': 'Copy link to task',
  'menu.copyId': 'Copy task id',
  'menu.copyCommand': 'Copy orch command',
  'menu.backlog': 'Move to backlog',
  'menu.ready': 'Mark ready',
  'menu.supersede': 'Supersede with a task…',
  'menu.title': 'Task title',
  'menu.class': 'Class',
  'menu.lane': 'Lane',
  'menu.depends': 'Depends on parent',
  'menu.note': 'What to do',
  'menu.confirm': 'Create task',
  'actions.backendUnavailable': 'This worker has no available direct backend.',
  'actions.legacyReadOnly': 'This older run is read-only. Start a new run to send instructions.',
  'panel.planError.incompatible': 'This plan was written by a newer Crewboard. Update Crewboard to open or change it.',
  'timeline.run': 'worker running',
  'timeline.review': 'awaiting human review',
  'timeline.dependency': 'waiting for a dependency',
  'timeline.unavailable': 'Plan time unavailable: {error}',
  'timeline.loading': 'Calculating plan time…',
  'timeline.noRuns': 'No runs yet — plan time will appear as soon as a task goes to a worker.',
  'timeline.title': 'Plan time',
  'timeline.summary': 'plan ran for {plan} · workers worked for {work}',
  'timeline.now': 'now',
  'timeline.speedup': 'What will speed up the plan:',
  'timeline.criticalPath': 'Critical path',
  'timeline.undefined': 'not determined',
  'timeline.humanWait': 'Human wait',
  'timeline.parallelism': 'Parallelism',
  'timeline.maxParallel': 'max. {workers} at once',
  'language.ru': 'Russian',
  'verdict.result': 'Result received',
  'verdict.negative': 'Negative result',
  'verdict.disputed': 'Disputed',
  'verdict.facts': 'Work facts',
  'verdict.checksInReport': 'Checks in report',
  'verdict.fact.files_changed': { one: '{count} file changed', other: '{count} files changed' },
  'verdict.fact.no_changes': 'No changes',
  'verdict.fact.journal': 'Deviations journal linked',
  'verdict.fact.duration': 'Duration: {time}',
  'verdict.fact.checks_not_run': 'Checks were not run',
  'verdict.fact.checks_run': { one: '{count} contract check reported as run', other: '{count} contract checks reported as run' },
  'verdict.fact.checks_unreported': { one: '{count} contract check not reported', other: '{count} contract checks not reported' },
  'verdict.fact.checks_unreadable': { one: '{count} contract check could not be read', other: '{count} contract checks could not be read' },
  'verdict.why.blocked': 'work is blocked',
  'verdict.why.negative': 'negative result received',
  'verdict.mismatch.run_failed': 'A result was claimed, but the last run failed or was cancelled.',
  'verdict.mismatch.no_files': 'A result was claimed, but no files changed.',
  'verdict.mismatch.report_missing': 'The task has a run, but no report.',
  'verdict.mismatch.checks_missing': 'The report does not mention the checks in the contract.',
  'verdict.mismatch.claim_missing': 'The report makes no explicit result claim.',
  'worktree.keep.dirty': 'uncommitted changes', 'worktree.keep.unmerged': 'branch is not merged into the main branch',
  'worktree.keep.running': 'task is running', 'worktree.keep.recent': 'copy was accepted recently', 'worktree.keep.rejected': 'task was not accepted',
  'report.title': 'Work report',
  'report.riskNote': 'Lines with risk words are marked',
  'report.finalNote': 'The worker did not write a report section; showing the start of its response',
  'report.showAll': 'Show full response',
  'internal.testFallback': 'English fallback',
  'relative.now': 'now',
  'relative.minute': { one: '{n} minute', other: '{n} minutes' },
  'relative.hour': { one: '{n} hour', other: '{n} hours' },
  'relative.day': { one: '{n} day', other: '{n} days' },
  'relative.month': { one: '{n} month', other: '{n} months' },
  'relative.year': { one: '{n} year', other: '{n} years' },
  'relative.ago': '{t} ago',
  'panel.status.backlog': 'backlog',
  'panel.status.ready': 'ready to start',
  'panel.status.running': 'running',
  'panel.status.inReview': 'awaiting review',
  'panel.status.accepted': 'accepted',
  'panel.status.blocked': 'waiting',
  'panel.status.superseded': 'superseded',
  'panel.headline.empty': 'No tasks',
  'panel.headline.tasks': { one: '{count} task', other: '{count} tasks' },
  'panel.headline.running': { one: '{count} running', other: '{count} running' },
  'panel.headline.review': { one: '{count} awaiting review', other: '{count} awaiting review' },
  'panel.headline.decisions': { one: '{count} decision is yours', other: '{count} decisions are yours' },
  'panel.headline.attention': { one: '{count} needs attention', other: '{count} need attention' },
  'panel.duration.seconds': { one: '{count} sec', other: '{count} sec' },
  'panel.duration.minutes': { one: '{count} min', other: '{count} min' },
  'panel.duration.hoursMinutes': { one: '{count} hr {minutes} min', other: '{count} hr {minutes} min' },
  'panel.essence.blockedBy': 'waiting on: {tasks}',
  'panel.essence.decisionAcceptedAt': 'decision · accepted by you {time}',
  'panel.essence.decisionAccepted': 'decision · accepted by you',
  'panel.essence.decisionYours': 'decision is yours',
  'panel.now.decisionBlocked': 'Waiting on {tasks} — no decision needed yet.',
  'panel.now.decisionYours': 'Your decision is holding up the plan.',
  'panel.now.working': '{worker} is working',
  'panel.now.elapsed': 'running for {time}',
  'panel.now.inReview': 'Work is done and ready for your review.',
  'panel.now.reviewHint': 'Check Changes, then accept or send it back with a reason.',
  'panel.now.ready': 'Dependencies are accepted — you can start this task.',
  'panel.now.blocked': 'Waiting on: {tasks}.',
  'panel.now.decisionAcceptedAt': 'You accepted the decision at {time}.',
  'panel.now.decisionAccepted': 'You accepted the decision.',
  'panel.now.accepted': 'Accepted.',
  'panel.now.superseded': 'Another option took its place — no action needed.',
  'panel.now.backlog': 'Backlog task: it is not ready to start yet.',
  'panel.worker': 'worker',
  'board.ready': 'Ready to start',
  'board.running': 'Running',
  'board.review': 'Awaiting review',
  'board.blocked': 'Waiting',
  'board.backlog': 'Backlog',
  'board.attentionAria': 'needs attention',
  'board.negativeDep': 'A predecessor closed without a result — check whether this task still matters',
  'board.empty': 'empty',
  'board.collapse': 'Collapse',
  'board.showAll': { one: 'Show all {count}', other: 'Show all {count}' },
  'board.expandLane': 'Expand lane {lane}',
  'board.unnamedLane': 'Unassigned lane',
  'board.noTasks': 'This plan has no tasks yet. Add one with `orch task add` or `orchestra_task_upsert`.',
  'board.attention': 'Needs attention',
  'board.accepted': 'Accepted',
  'panel.console.emptyBlock': 'empty',
  'panel.console.stop': 'Stop',
  'panel.console.open': 'Open',
  'panel.console.run': 'Start',
  'panel.console.noTasks': 'This plan has no tasks yet. Add one with `orch task add` or `orchestra_task_upsert`.',
  'panel.console.idle': 'All clear: nothing is running, ready to start or needs attention.',
  'panel.console.attention': 'Needs attention',
  'panel.console.running': 'Running',
  'panel.console.ready': 'Ready to start',
  'panel.console.worker': 'worker',
  'panel.console.deadEndsCount': 'Accepted with no follow-up: {count}',
  'panel.console.deadEnds': 'Accepted with no follow-up',
  'panel.console.acceptedAgo': '{worker} · accepted {time}',
  'panel.console.longAgo': 'a while ago',
  'panel.console.deadEndsHint': 'These tasks are done and nothing depends on them. If their findings still need action, add a follow-up task and link it here.',
  'panel.console.totals': 'Plan totals',
  'panel.console.totalTasks': 'Total tasks',
  'panel.console.accepted': 'Accepted',
  'panel.console.criticalPath': 'Critical path',
  'graph.decisionLane': 'Decisions',
  'graph.fold.taskCount': { one: '{count} task', other: '{count} tasks' },
  'graph.fold.allAccepted': 'all accepted',
  'graph.fold.allSuperseded': 'all superseded',
  'graph.fold.accepted': { one: '{count} accepted', other: '{count} accepted' },
  'graph.fold.superseded': { one: '{count} superseded', other: '{count} superseded' },
  'graph.fold.inProgress': { one: '{count} in progress', other: '{count} in progress' },
  'graph.minimap.label': 'Plan minimap',
  'graph.search.label': 'Search tasks in this plan',
  'graph.search.placeholder': 'Search by task name or ID…',
  'graph.search.empty': 'No matches.',
  'graph.search.keys': '↑↓ select · ⏎ open and center · Esc close',
  'queue.decisionYours': 'decision is yours',
  'queue.files': { one: '{count} file', other: '{count} files' },
  'queue.loadingChanges': 'Checking changes…',
  'queue.moreFiles': { one: '… and {count} more', other: '… and {count} more' },
  'queue.decisionNoFiles': 'Decisions do not change files.',
  'queue.noChanges': 'No changes.',
  'queue.open': 'Open',
  'queue.changes': 'Changes',
  'queue.accept': 'Accept',
  'queue.sendBackMore': 'Send back…',
  'queue.reasonLabel': 'Reason for sending back task {id}',
  'queue.reasonPlaceholder': 'Why send this back? The worker will see your reason',
  'queue.sendBack': 'Send back',
  'queue.cancel': 'Cancel',
  'queue.confirmHint': 'Confirm in the macOS dialog',
  'queue.otherPlanReview': { one: '{count} waiting for you', other: '{count} waiting for you' },
  'queue.switchPlan': 'Go to plan',
  'queue.title': 'Review queue',
  'queue.close': 'Close review queue',
  'queue.waitingDecisions': { one: '{count} task awaits your decision', other: '{count} tasks await your decision' },
  'queue.emptyPlan': 'Nothing to review in this plan',
  'queue.otherCount': { one: '{count} more in other plans', other: '{count} more in other plans' },
  'queue.acceptAll': 'Accept all',
  'queue.emptyHint': 'When a worker finishes a task, it will appear here for you to accept or send back with a reason.',
  'queue.otherPlans': 'In other plans',
  'queue.batch.waited': 'waiting {duration}',
  'queue.batch.acceptAll': { one: 'Accept all · {count}', other: 'Accept all · {count}' },
  'queue.batch.dialogLabel': { one: 'Accept tasks: {count}', other: 'Accept tasks: {count}' },
  'queue.batch.title': 'Awaiting review',
  'queue.batch.selectAll': 'Select all',
  'queue.batch.clearAll': 'Clear selection',
  'queue.batch.open': 'Open',
  'queue.batch.acceptSelected': { one: 'Accept selected · {count}', other: 'Accept selected · {count}' },
  'queue.batch.cancel': 'Cancel',
  'queue.batch.confirmHint': 'Confirm in the macOS dialog',
  'panel.economics.workers': { one: '{count} worker', other: '{count} workers' },
  'panel.economics.turns': { one: '{count} turn', other: '{count} turns' },
  'panel.economics.seconds': { one: '{count} sec', other: '{count} sec' },
  'panel.economics.minutes': { one: '{count} min', other: '{count} min' },
  'panel.economics.hoursMinutes': { one: '{count} hr {minutes} min', other: '{count} hr {minutes} min' },
  'panel.economics.week': 'wk',
  'panel.economics.quota': 'quota',
  'panel.economics.waitingDependency': 'waiting on: {tasks}',
  'panel.economics.working': '{worker} working',
  'panel.economics.waitingReview': 'awaiting human review',
  'panel.economics.noReviewDelay': 'Review did not hold up the plan.',
  'panel.economics.acceptSooner': 'Accept {id} as soon as it finishes — {task} could have started {duration} earlier.',
  'panel.economics.currentDelay': '{id} has awaited your review for {duration} — the plan’s biggest delay.',
  'panel.economics.longestDelay': '{id} spent the longest awaiting review — {duration}.',
  'panel.economics.noConnection': 'Cannot reach the dsh server',
  'graph.saveLayoutFailed': 'Could not save the layout',
  'graph.startingTask': 'Starting {task}…',
  'graph.startTaskFailed': 'Could not start the task',
  'graph.steerButtonPrefix': 'Steer',
  'graph.noTasks': 'This plan has no tasks yet. Add one with `orch task add` or `orchestra_task_upsert`.',
  'graph.collapseLane': 'Collapse lane {lane}',
  'graph.collapse': 'collapse',
  'graph.tidyLane': 'Tidy lane: {lane}',
  'graph.tidyHere': 'tidy',
  'graph.edgeCount': { one: '{count} link', other: '{count} links' },
  'graph.selectTask': 'Select task {id}: {title}',
  'graph.expandLane': 'Expand lane {lane}',
  'graph.unnamedLane': 'Unassigned lane',
  'graph.negativeResult': 'closed: no result',
  'graph.negativePredecessor': 'a predecessor closed without a result — check whether this task still matters',
  "graph.handPicked": "hand-picked",
  "graph.handPickedTitle": "A person chose this worker outside the preset; it runs anyway.",
  "panel.app.outsidePreset": "Outside preset · {count}",
  "panel.app.outsidePresetHint": "Tasks whose assigned worker is not in the current preset",
  "panel.app.outsideAgentNote": "the preset decides at launch",
  "panel.task.workerChoice": "Worker: {worker} — {who}",
  "panel.task.chosenBy.person": "chosen by you",
  "panel.task.chosenBy.preset": "chosen by the preset",
  "panel.task.chosenBy.agent": "chosen by the agent",
  "panel.task.keepAssigned": "Assigned — {worker}",
  "panel.task.assignedHint": "{worker} · assigned, {who}",
  "panel.task.staleAssigned": "{worker} was chosen by an agent and is not in the preset — the preset decides at launch",
  "review.choice": "Worker choice",
  "review.choice.preset": "By preset",
  "review.choice.hand": "Hand-picked",
  'graph.pinned': 'pinned manually',
  'graph.attention': 'needs attention',
  'graph.negativePredecessorTitle': 'A predecessor closed without a result — check whether this task still matters',
  'graph.reviewLensCount': { one: 'Review · {count}', other: 'Review · {count}' },
  'queue.acceptAllCount': { one: 'Accept all · {count}', other: 'Accept all · {count}' },
  'graph.acceptWork': 'Accept work: {title}',
  'graph.acceptHint': 'Accept — confirm in the macOS dialog',
  'graph.acceptMore': 'Accept…',
  'graph.tidyAll': 'Tidy layout',
  'graph.fit': 'Fit (F)',
  'graph.criticalPath': { one: 'Critical path · {count}', other: 'Critical path · {count}' },
  'graph.reviewLensHint': 'Review lens: highlights tasks and steps through them without hiding anything (n for next)',
  'graph.reviewLens': 'Review',
  'graph.nextLensHint': 'Next lens match (n)',
  'graph.nextLens': 'Next lens match',
  'graph.find': 'Find',
  'graph.gestureHint': 'Two fingers or drag to pan · pinch or ⌘+scroll to zoom · double click to zoom in · ←→ along a chain',
  "settings.class.code": "Code ready to build",
  "settings.class.design": "Design and UI",
  "settings.class.review": "Review",
  "settings.class.research": "Research",
  "panel.workerUnset": "No worker assigned",
  "panel.tab": "Orchestration",
  "panel.guide": "Your workspace plan beside the chat",
  "settings.section": "Crewboard",
  "settings.worktrees.loadError": "Could not load worktrees",
  "settings.worktrees.connectionError": "Cannot reach the dsh server",
  "settings.worktrees.removeError": "Could not remove worktrees",
  "settings.worktrees.policyError": "Could not save cleanup policy",
  "settings.worktrees.unknownSize": "size unknown",
  "settings.worktrees.removable": "can be removed",
  "settings.worktrees.dirtyDetails": "{modified} modified, {untracked} untracked · {paths} · {artifacts}",
  "settings.worktrees.artifactsOnly": "output artefacts only",
  "settings.worktrees.notArtifactsOnly": "includes other changes",
  "settings.worktrees.orphanRegistered": "orphan folder · Git still registers it; manual recovery only",
  "settings.worktrees.orphanUnknown": "orphan folder · Git does not register it; never auto-removed",
  "settings.worktrees.loading": "Loading worktrees…",
  "settings.worktrees.hide": "Hide",
  "settings.worktrees.show": "Show",
  "settings.worktrees.title": "Worktrees",
  "settings.worktrees.confirmAria": "Confirm worktree cleanup",
  "settings.worktrees.removeExtras": "Remove unused",
  "settings.worktrees.empty": "No worktrees",
  "settings.worktrees.remove": "Remove worktrees",
  "settings.worktrees.cancel": "Cancel",
  "settings.worktrees.policyLabel": "Cleanup policy ",
  "settings.worktrees.gigabytes": "{size} GB",
  "settings.worktrees.summary": { one: '{count} worktree · {size} GB', other: '{count} worktrees · {size} GB' },
  "settings.worktrees.removed": "Removed: {count}",
  "settings.worktrees.remaining": "Still present: {items}",
  "settings.worktrees.confirm": { one: 'Remove {count} worktree · {size} GB?', other: 'Remove {count} worktrees · {size} GB?' },
  "settings.worktrees.confirmUnknown": { one: 'Remove {count} worktree · {size} GB of known size? Some sizes are unknown.', other: 'Remove {count} worktrees · {size} GB of known size? Some sizes are unknown.' },
  "panel.plan.running": "running",
  "panel.plan.review": "waiting for you",
  "panel.plan.attention": "needs attention",
  "panel.plan.restore": "Restore from archive",
  "panel.plan.archiveAction": "Archive",
  "panel.plan.collapse": "Collapse plans",
  "panel.plan.expand": "Expand plans",
  "panel.plan.rename": "Rename…",
  "panel.plan.goalPlaceholder": "Plan goal…",
  "panel.plan.newGoal": "New plan goal",
  "panel.plan.new": "New plan",
  "panel.plan.picker": "Plan",
  "panel.plan.archive": "Archive",
  "panel.plan.title": "Plans",
  "panel.plan.newButton": "+ New plan",
  "panel.plan.hint": "Press Enter to create and switch",
  "panel.plan.tasks": { one: '{count} task', other: '{count} tasks' },
  "panel.plan.actions": "Actions for plan “{goal}”",
  "panel.plan.renameLabel": "New name for plan “{goal}”",
  "panel.plan.badge": "Plan “{goal}”",
  "panel.plan.archiveCount": "Archive · {count}",
  "side.title": "Repositories",
  "side.search": "Search repositories, plans, tasks…",
  "side.searchAria": "Search across repositories, plans and tasks",
  "side.searchEmpty": "Nothing found.",
  "side.inbox": "Needs you",
  "side.inboxEmpty": "All clear — nothing is waiting on you.",
  "side.inboxCount": { one: '{count} needs you', other: '{count} need you' },
  "side.repos": "Repositories",
  "side.plans": { one: '{count} plan', other: '{count} plans' },
  "side.finished": { one: '{count} finished plan', other: '{count} finished plans' },
  "side.badge.running": "{count} running",
  "side.badge.review": "{count} awaiting review",
  "side.badge.failed": "{count} failed",
  "side.inboxHint": "Reviews, decisions and failed or stalled runs that wait on a person — the same list crewboard attention prints (--all for every repository). Example rows sit under their own divider and are not counted.",
  "side.quiet": "Quiet · {count}",
  "side.hidden": "Hidden · {count}",
  "side.pin": "Pin",
  "side.unpin": "Unpin",
  "side.hide": "Hide",
  "side.show": "Unhide",
  "side.openChat": "Open plan chat",
  "side.copyAgent": "Copy for agent",
  "side.repoActions": "Actions for repository “{repo}”",
  "side.moveUp": "Move up",
  "side.moveDown": "Move down",
  "side.resetOrder": "Reset order",
  "side.reposMenu": "Repositories section menu",
  "side.addRepo": "Add repository",
  "side.addRepo.label": "Repository folder",
  "side.addRepo.placeholder": "/Users/you/src/app or ~/src/app",
  "side.addRepo.hint": "Paste an absolute folder path; ~ stands for your home folder. Enter adds it.",
  "side.addRepo.error.notAbsolute": "Enter an absolute path: it starts with / or ~.",
  "side.addRepo.error.notFound": "There is no folder at this path.",
  "side.addRepo.error.notDirectory": "This path is a file, not a folder.",
  "side.addRepo.error.notGit": "This folder is not a Git repository or worktree.",
  "side.addRepo.error.alreadyListed": "This repository is already in the list.",
  "side.newPlan": "New plan…",
  "side.removeRepo": "Remove from list",
  "side.removeRepo.safe": "Files and plans stay on disk",
  "side.removeRepo.alsoDsh": "Stays on screen: it is also a dsh workspace",
  "side.removeRepo.alsoProfile": "Stays on screen: it is also in the plugin's repos setting",
  "side.removeRepo.dsh": "A dsh workspace: remove it in dsh",
  "side.removeRepo.profile": "In the plugin's repos setting of the dsh profile: edit it there",
  "side.removeRepo.worktree": "A worktree of a listed repository: it shows while it holds a plan",
  "side.removeRepo.error": "Only folders from the Crewboard list can be removed here.",
  "side.missing": "missing",
  "side.missingHint": "This folder no longer exists. Remove it from the list with «Remove from list».",
  "side.worktree": "worktree",
  "side.worktreeHint": "Worktree {path}",
  "side.moved": "{name} moved to position {pos} of {count}",
  "copyAgent.label": "Copy for agent",
  "copyAgent.done": "Copied",
  "copyAgent.hint": "Copy a brief for your agent chat",
  "panel.draft.group": "Drafts",
  "panel.draft.badge": "Draft “{goal}”",
  "panel.draft.blocked": "blocked",
  "panel.draft.review": "Draft review",
  "panel.draft.loading": "Loading draft…",
  "panel.draft.source": "Source",
  "panel.draft.chat": "chat",
  "panel.draft.close": "Close",
  "panel.draft.findings": "Findings",
  "panel.draft.blocksApproval": "Blocks approval:",
  "panel.draft.advisory": "Review:",
  "panel.draft.finding.cycle": "Dependency cycle: {tasks}",
  "panel.draft.finding.missing_dependency": "{task} depends on missing task {dependency}",
  "panel.draft.finding.missing_acceptance": "{task} has no acceptance checks",
  "panel.draft.finding.empty_contract": "{task} has no contract sketch",
  "panel.draft.finding.file_collision": "{tasks} both mention {file}",
  "panel.draft.decisions": "Agent decisions",
  "panel.draft.class": "Class",
  "panel.draft.kind": "Kind",
  "panel.draft.deps": "Dependencies",
  "panel.draft.acceptance": "Acceptance checks",
  "panel.draft.sources": "Sources",
  "panel.draft.contract": "Contract sketch",
  "panel.draft.none": "None",
  "panel.draft.approve": "Approve as plan",
  "panel.draft.approveBlocked": "Resolve blocking findings before approval",
  "panel.draft.discard": "Discard",
  "panel.draft.discardConfirm": "Discard this draft?",
  "panel.draft.discardYes": "Discard draft",
  "panel.draft.cancel": "Cancel",
  "panel.draft.error.invalid": "The draft has blocking findings. Refresh and review it again.",
  "panel.draft.error.notFound": "This draft no longer exists. Refresh the list.",
  "panel.draftJob.title": "Draft job",
  "panel.draftJob.worker": "Worker: {worker}",
  "panel.draftJob.attempt": "attempt {count}",
  "panel.draftJob.running": "A worker is drafting the plan · {time}. You can close or reload this page: the draft appears here when it is ready.",
  "panel.draftJob.needsRepair": "Needs repair",
  "panel.draftJob.needsRepairHelp": "The worker answered, but the answer does not match the PlanDraft schema. The answer is kept below; repair sends it back to a worker together with these findings.",
  "panel.draftJob.wholeAnswer": "answer",
  "panel.draftJob.failed": "The worker did not produce a draft",
  "panel.draftJob.failedHelp": "Reason: {error}. Try again or discard the job.",
  "panel.draftJob.recovered": "Recovered from run {run}: its answer was not saved before.",
  "panel.draftJob.answer": "Raw worker answer",
  "panel.draftJob.repair": "Repair with a worker",
  "panel.draftJob.retry": "Try again",
  "panel.draftJob.discardConfirm": "Discard this job? A running worker is stopped; prompts and answers stay in .orchestration/draft-runs.",
  "panel.draftJob.discardYes": "Discard job",
  "panel.draftJob.status.running": "drafting…",
  "panel.draftJob.status.needs_repair": "needs repair",
  "panel.draftJob.status.failed": "failed",
  "panel.app.work": "Work",
  "panel.app.review": "Review",
  "work.needsYou": "Needs you",
  "work.done": "Done",
  "work.reviewQueue": "Review queue",
  "work.filter": "Done filter",
  "work.filter.all": "All",
  "work.filter.accepted": "Accepted",
  "work.filter.closed": "Closed without result",
  "work.filter.superseded": "Superseded",
  "work.followupHint": "Done and nothing depends on these tasks. Add a follow-up if needed.",
  "work.filter.followup": "May need follow-up",
  "work.totals": "{tasks} tasks · {accepted} accepted",
  "work.critical": "Critical path: {path}",
  'review.failed': 'Failed',
  'review.cancelled': 'Stopped',
  'review.multipleAttempts': 'Multiple attempts',
  'review.sources': 'Show sources',
  'review.measurements': 'Show measurements',
  'review.rates': 'Show rates',
  'review.noIssues': 'No recorded issues',
  'review.lastActivity': 'Last activity',
  'review.latestDecision': 'Latest decision',
  'review.blockedDependants': 'blocked dependants',
  'review.stale': 'Showing last snapshot from {time}; refresh failed',
  'review.progress': 'Progress',
  'review.scope': 'Whole plan',
  'review.updated': 'Updated {time}',
  'review.resultAccepted': 'Accepted with result',
  'review.awaitingCount': 'awaiting review',
  'review.openCount': 'open',
  'review.negativeCount': 'closed without result',
  'review.supersededCount': 'superseded',
  'review.disputedCount': 'disputed',
  'review.legacyAcceptedCount': 'legacy acceptance; result unknown',
  'review.elapsed': 'Plan elapsed',
  'review.notStarted': 'Not started',
  'review.inferredEnd': 'End inferred from terminal tasks',
  'review.wallClock': 'Wall clock',
  'review.overlapNote': 'Work and review wait can overlap.',
  'review.history': 'Progress history',
  'review.noHistory': 'History unavailable',
  'review.accounting': 'Money and quota',
  'review.coverage': 'Usage available for {known} of {total} runs',
  'review.fixedFees': 'Fixed subscription fees are unallocated.',
  'review.pp': 'pp',
  'review.investigate': 'Investigate',
  'review.historyIncomplete': 'Decision history incomplete',
  'review.updatesAvailable': 'Updates available',
  'review.tasks': 'Tasks',
  'review.search': 'Search task, worker or run',
  'review.class': 'Task class',
  'review.lane': 'Lane',
  'review.noLane': 'No lane',
  'review.unclassified': 'Unclassified',
  'review.group': 'Group by',
  'review.none': 'None',
  'review.sort': 'Sort',
  'review.sort.start': 'Started',
  'review.sort.duration': 'Duration',
  'review.sort.wait': 'Human wait',
  'review.sort.cash': 'Cash',
  'review.sort.equivalent': 'Equivalent',
  'review.sort.quota': 'Quota',
  'review.waitMin': 'Wait at least (min)',
  'review.durationMin': 'Duration at least (min)',
  'review.from': 'Runs started from',
  'review.to': 'Runs started through',
  'review.reset': 'Reset filters',
  'review.moreFilters': 'More filters',
  'review.noMatches': 'No matching runs',
  'review.page': '{from}–{to} of {total}',
  'review.pageSize': 'Rows per page',
  'review.quotaWindow': 'Quota window',
  'review.taskAttempt': 'Task / attempt',
  'review.attempts': 'Attempts',
  'review.mixedClasses': 'Mixed task classes',
  'review.workerSort.tasks': 'Tasks touched',
  'review.workerSort.attempts': 'Attempts',
  'review.workerSort.median': 'Median run time',
  'review.workerSort.acceptance': 'Reviewed acceptance rate',
  'review.workerSort.cash': 'Cash',
  'review.workerSort.equivalent': 'Equivalent',
  'review.acceptedReviewed': 'Accepted / reviewed',
  'review.median': 'Median run time',
  'review.inspectContributions': 'Inspect contributions',
  'review.noClassRuns': 'No runs for this class',
  "review.summary": "Plan summary",
  "review.lessThanMinute": "<1 min",
  "review.planDuration": "Plan duration",
  "review.workerTime": "Worker time",
  "review.yourWait": "Waiting for you",
  "review.quota": "Quota spent",
  "review.spent": "Spent",
  "review.tokens": "Tokens",
  "review.noRuns": "No runs yet.",
  'review.pendingUsage': 'Awaiting usage', 'review.partial': 'Partial data', 'review.notApplicable': 'Not applicable', 'review.unavailable': 'Unavailable',
  'review.notCharged': 'Estimate, not charged', 'review.sharedQuota': 'Shared window; run attribution unavailable', 'review.cash': 'API cash recorded', 'review.quotaChange': 'Subscription quota change', 'review.equivalent': 'API-price equivalent',
  'review.input': 'Input tokens', 'review.output': 'Output tokens', 'review.cacheRead': 'Cache read', 'review.cacheWrite': 'Cache write', 'review.humanWait': 'Awaiting human review', 'review.execution': 'Execution', 'review.decision': 'Human decision', 'review.noDecision': 'No recorded decision',
  'review.noChange': 'No change detected',
  'review.smallSample': 'Small sample',
  'review.touched': 'Tasks touched',
  'review.workersClass': 'Workers by task class',
  'panel.app.screenLoading': 'Loading screen…', 'panel.app.screenLoadError': 'Screen unavailable.',
  'review.openRun': 'Open run', 'review.taskHistory': 'Task history', 'review.expand': 'Expand', 'review.back': 'Back to runs', 'review.backRun': 'Back to run', 'review.backPanel': 'Back to run panel', 'review.backTask': 'Back to task history', 'review.ledger': 'Run ledger', 'review.usageTime': 'Usage over time', 'review.breakdown': 'Breakdown by step', 'review.unattributed': 'Unattributed usage', 'review.noStepUsage': 'No step-level usage recorded', 'review.cumulative': 'Cumulative across attempts', 'review.allAttempts': 'All attempts shown', 'review.previous': 'Previous', 'review.next': 'Next', 'review.retry': 'Retry', 'review.loading': 'Loading Review…', 'review.stepsMissing': 'Run summary available; step history unavailable.', 'review.triggerUnknown': 'Trigger unknown', 'review.attempt': 'Attempt {n}', 'review.workerSum': 'Worker time · sum across runs',
  'drill.worker': 'Worker', 'drill.model': 'Model', 'drill.attempt': 'Attempt', 'drill.start': 'Started', 'drill.end': 'Ended', 'drill.elapsed': 'Elapsed', 'drill.reason': 'Reason', 'drill.reasoning': 'Reasoning tokens', 'drill.reasoningIncluded': 'included in output', 'drill.availability': 'Usage availability', 'drill.recorded': 'Recorded', 'drill.reset': 'Window reset', 'drill.quotaSamples': 'Account window measurements', 'drill.time': 'Time', 'drill.source': 'Source', 'drill.increment': 'Increment', 'drill.attributed': 'Attributed usage', 'drill.total': 'Run total', 'drill.unreconciled': 'Does not reconcile', 'drill.state': 'Current outcome', 'drill.metric': 'Metric / event', 'drill.trigger': 'Trigger', 'drill.attemptRange': 'Attempts {from}–{to} of {total}', 'drill.decisionHistory': 'Decision history', 'drill.mode.cash': 'Cash', 'drill.mode.equivalent': 'Equivalent', 'drill.mode.tokens': 'Tokens', 'drill.mode.quota': 'Quota',
  'drill.execution.completed': 'Completed', 'drill.execution.failed': 'Failed', 'drill.execution.cancelled': 'Stopped', 'drill.execution.running': 'Running', 'drill.trigger.initial': 'Initial', 'drill.trigger.human_relaunch': 'Human relaunch', 'drill.trigger.automatic_retry': 'Automatic retry', 'drill.decision.accepted': 'Accepted', 'drill.decision.rejected': 'Returned',
  "review.runs": "Runs",
  "review.steps": "{count} steps",
  "review.decisionWait": "Your decision: {duration}",
  "review.outcome.awaiting": "Awaiting review",
  "review.outcome.running": "Running",
  "review.outcome.returned": "Returned",
  "review.outcome.noResult": "No result",
  "review.outcome.accepted": "Accepted",
  "review.step.model": "Model",
  "review.step.tool": "Tool",
  "review.step.edit": "File edit",
  "review.step.check": "Check",
  "review.step.problem": "Problem",
  "review.step.correction": "Correction",
  "panel.app.graph": "Graph",
  "panel.app.overview": "Compact",
  "panel.app.detail": "Detailed",
  "panel.app.attentionHint": "Focus: needs attention. Highlights tasks without hiding others (n for next).",
  "panel.app.runningHint": "Focus: running tasks. Highlights work in progress (n for next).",
  "panel.app.readyHint": "Focus: ready to start. Highlights tasks without hiding others (n for next).",
  "panel.app.reviewHint": "Focus: review. Highlights tasks without hiding others (n for next).",
  "panel.app.queueEmpty": "Waiting for you",
  "panel.app.nextHint": "Next focused task (n)",
  "panel.app.next": "Next focused task",
  "panel.app.queueTitle": "Review queue",
  "panel.app.repo": "Repository",
  "panel.app.status": "Status",
  "panel.app.view": "View",
  "panel.app.density": "Density",
  "panel.app.loading": "Loading plans…",
  "panel.app.noRepos": "No repositories connected. Add a path in the plugin settings (repos) or set CREWBOARD_REPOS.",
  "panel.app.disconnected": "Connection lost, reconnecting…",
  "panel.app.attentionCount": "Needs attention · {count}",
  "panel.app.runningCount": "Running · {count}",
  "panel.app.readyCount": "Ready · {count}",
  "panel.app.reviewCount": { one: 'Awaiting review · {count}', other: 'Awaiting review · {count}' },
  "panel.app.lensListHint": "↑↓ choose · Enter opens · n next match · Esc closes",
  "panel.app.queueCount": "Waiting for you · {count}",
  "panel.app.otherCount": " · {count} more in other plans",
  "panel.side.own": "this chat runs the plan",
  "panel.side.other": "another chat runs the plan",
  "panel.side.none": "no chat assigned",
  "panel.side.decisionYours": "your decision",
  "panel.side.noChangesDecision": "Decisions do not change files.",
  "panel.side.noChanges": "No changes.",
  "panel.side.open": "Open",
  "panel.side.changes": "Changes",
  "panel.side.worker": "worker",
  "panel.side.workerAuto": "routing will choose a worker",
  "panel.side.unavailable": "The full screen is unavailable in this version of dsh",
  "panel.side.newTaskHint": "Ask an agent or orch to add tasks to the plan; they will appear here right away",
  "panel.side.confirmHint": "Confirm in the macOS window",
  "panel.side.goalAria": "Plan goal",
  "panel.side.goalPlaceholder": "Plan goal…",
  "panel.side.rejectPlaceholder": "Why send it back? The worker will see this.",
  "panel.side.openScreen": "Open on full screen",
  "panel.side.noPlan": "There is no plan in this folder.",
  "panel.side.noPlanHelp": "A plan keeps a goal and its tasks together. Start one here; an agent or orch can add the tasks.",
  "panel.side.startPlan": "Start a plan",
  "panel.side.counting": "Checking changes…",
  "panel.side.accept": "Accept",
  "panel.side.sendBack": "Send back…",
  "panel.side.sendBackNow": "Send back",
  "panel.side.cancel": "Cancel",
  "panel.side.run": "Run",
  "panel.side.bind": "Make this chat the orchestrator",
  "panel.side.calm": "All clear: nothing is running or waiting for review.",
  "panel.side.now": "Now",
  "panel.side.openGraph": "Open graph",
  "panel.side.newTask": "New task",
  "panel.side.review": "Awaiting your review",
  "panel.side.ready": "Ready to start",
  "panel.side.tab": "Orchestration",
  "panel.side.noCwd": "Could not find this chat’s workspace.",
  "panel.side.connecting": "Connecting to orchestration…",
  "panel.side.untracked": "This folder is not tracked by orchestration.",
  "panel.side.untrackedHelp": "This chat’s folder is not a dsh workspace, not in the plugin settings (repos) and not in the Crewboard list. Add it with «+» next to Repositories or `crewboard repo add`.",
  "panel.side.unreadable": "Cannot read the plan in this folder.",
  "panel.side.files": { one: '{count} file', other: '{count} files' },
  "panel.side.moreFiles": "… and {count} more",
  "panel.side.rejectAria": "Reason for sending back task {id}",
  "panel.side.runningSince": "running {since}",
  "panel.side.tasks": { one: '{count} task', other: '{count} tasks' },
  "panel.side.reviewCount": "Awaiting your review · {count}",
  "panel.side.readyCount": "Ready to start · {count}",
  "settings.classShort.code": "code",
  "settings.classShort.design": "design",
  "settings.classShort.review": "review",
  "settings.classShort.research": "research",
  "settings.kind.dsh": "DeepSeek via dsh",
  "settings.loadError": "Cannot reach the dsh server",
  "settings.saveWorkerError": "Could not save worker",
  "settings.removeWorkerError": "Could not remove worker",
  "settings.workerRemoved": "Removed: {workers}",
  "settings.notUsed": "not used",
  "settings.profileEdit": "Edit this profile in ~/.config/crewboard/profiles.json",
  "settings.newName": "New name",
  "settings.note": "Note",
  "settings.checking": "checking…",
  "settings.checkError": "check failed",
  "settings.unchecked": "not checked",
  "settings.cliMissing": "CLI not found",
  "settings.signedIn": "signed in",
  "settings.signinNeeded": "sign in required",
  "settings.cliUnconfirmed": "CLI available · sign in unverified",
  "settings.modelExampleClaude": "For example, opus",
  "settings.modelExampleCodex": "For example, gpt-6-sol",
  "settings.checkForm": "Checking…",
  "settings.checkFormError": "CLI check failed",
  "settings.cliAvailable": "CLI available",
  "settings.checkManual": "Click Check to test access",
  "settings.saving": "Saving…",
  "settings.saved": "Saved",
  "settings.gripHint": "Drag to reorder, or press Space and use the arrow keys",
  "settings.cliAccess": "CLI access",
  "settings.modelDsh": "dsh model",
  "settings.profileEditHint": "Edit this profile in ~/.config/crewboard/profiles.json.",
  "settings.emptyClass": "The list is empty. Tasks in this class will not start.",
  "settings.addWorkerOption": "+ add worker",
  "settings.loading": "Loading orchestration rules…",
  "settings.noRepos": "No repositories connected. Add a path in the plugin settings (repos) or set CREWBOARD_REPOS.",
  "settings.rename": "Rename",
  "settings.remove": "Remove",
  "settings.save": "Save",
  "settings.cancel": "Cancel",
  "settings.removeWorker": "Remove worker",
  'settings.presets': 'Presets',
  'settings.presetsHint': 'Choose which workers each class can use, in priority order.',
  'settings.allWorkers': 'All workers',
  'settings.defaultPreset': 'Default — used where no other preset is chosen',
  'settings.newPreset': 'New preset',
  'settings.whoRunsTasks': 'Who runs tasks',
  'settings.thisRepository': 'This repository · {repo}',
  'settings.repositoryHelp': 'Every plan in the repository uses it unless the plan picks its own.',
  'settings.thisPlan': 'This plan · {plan}',
  'settings.planHelp': 'Overrides the repository for this plan only.',
  'settings.scopeRepository': 'Repository',
  'settings.scopePlan': 'Plan',
  'settings.openOrchestration': 'Orchestration settings',
  'panel.app.partFailed': 'This part of the screen failed: {area}',
  'panel.app.partRetry': 'Try again',
  'panel.app.areaMain': 'main view',
  'panel.app.areaSide': 'task panel',
  'panel.app.hostStale': 'Restart dsh to finish the update',
  'panel.app.hostStaleHint': 'The plugin was updated, but dsh still runs its previous host half. Restart dsh so both halves match.',
  'settings.repositoryUnknown': 'Loading repository preset…',
  'settings.inForce': 'In force: {preset} — {source}',
  'settings.forceSource.plan': 'from the plan',
  'settings.forceSource.repository': 'from the repository',
  'settings.forceSource.builtin': 'built in',
  'settings.workerOrder': 'Worker order by task class',
  'settings.skippedWorker.disabled': '{worker} is off on this machine — skipped',
  'settings.skippedWorker.unknown': '{worker} is unavailable on this machine — skipped',
  'settings.builtin': 'Built in · read only',
  'settings.edit': 'Edit',
  'settings.presetName': 'Preset name',
  'settings.createPreset': 'Create preset',
  'settings.presetDeletePrompt': 'Remove “{label}”? These assignments will be cleared:',
  'settings.presetRepoUse': 'Repository: {repo}',
  'settings.presetPlanUse': '{repo} · plan: {plan}',
  'settings.repositoryPreset': 'Repository preset',
  'settings.planPreset': 'Plan preset',
  'settings.repositoryOverridden': 'Repository preset · plan override active',
  'settings.workersButton': 'Workers · {preset}: {worker}',
  'settings.asRepository': 'Same as the repository ({preset})',
  'settings.noWorker': 'No available worker',
  'settings.runManual': '{worker} · selected for this run',
  'settings.visibleUses': 'No assignments visible in connected repositories.',
  'settings.runSource': '{worker} · from {source} preset {preset}',
  'settings.disabledLine': 'Unavailable on this machine: {workers}',
  'settings.source.plan': 'the plan',
  'settings.source.repository': 'the repository',
  'settings.source.builtin': 'the built in',
  "settings.workers": "Workers",
  "settings.workersHint": "Workers the orchestrator can assign to tasks. Disabled workers are skipped by Auto and are not offered to agents.",
  "settings.checkAccess": "Check access",
  "settings.billing": "Billing",
  "settings.usedIn": "Used in",
  "settings.assign": "Assign",
  "settings.extraHint": "Saved profiles not yet configured here. Enable one after installing and signing in to its CLI.",
  "settings.addWorker": "+ Add worker",
  "settings.chooseModel": "Choose a model",
  "settings.configureModels": "Configure models in Settings → Models.",
  "settings.devinModelHint": "The Devin profile sets the model; there is nothing to select here.",
  "settings.chooseProfile": "Choose a profile",
  "settings.check": "Check",
  "settings.add": "Add",
  "settings.orderTitle": "Worker order by task class",
  "settings.orderHint": "A task without an assigned worker goes to the first enabled worker in its class. Drag a row by its handle, or press Space to lift it.",
  "settings.workerType": "Worker type",
  "settings.dshModel": "dsh model",
  "settings.modelId": "Model ID",
  "settings.workerName": "Worker name",
  "settings.position": "{label} — position {position} of {count}",
  "settings.grabbing": "{label} — moving: position {position} of {count}",
  "settings.cancelMove": "{label} — move canceled",
  "settings.reorder": "Reorder {label}",
  "settings.raise": "Move {id} up",
  "settings.lower": "Move {id} down",
  "settings.removeFromClass": "Remove {id}",
  "settings.addToClass": "Add worker: {label}",
  "settings.workerAria": "Worker {id}",
  "settings.actions": "Actions: {label}",
  "settings.deleteAria": "Confirm removal of {label}",
  "settings.removePrompt": "Remove “{label}”?",
  "settings.removeUsedPrompt": "Remove “{label}”? Also remove it from these lists: {uses}.",
  "settings.profileDelete": "This profile is not in the worker registry. Remove it from saved profiles.",
  "settings.disableReason": "Reason for disabling: {id}",
  "settings.off": "disabled",
  "settings.extraCount": "More profiles · {count}",
  "settings.offReason": "no available quota",
  "settings.billing.subscription": "subscription",
  "settings.billing.promo": "promo",
  'settings.providerOther': 'Other',
  'settings.worktrees.keep.dirty': 'has uncommitted changes',
  'settings.worktrees.keep.unmerged': 'branch is not merged into main',
  'settings.worktrees.keep.running': 'task is running',
  'settings.worktrees.keep.recent': 'worktree was accepted recently',
  'settings.worktrees.keep.rejected': 'task was not accepted',
  'settings.worktrees.keep.orphan': 'orphan folder; manual review only',
  'settings.worktrees.policy.0': 'after acceptance',
  'settings.worktrees.policy.1': 'on request',
  'settings.worktrees.policy.2': 'never remove',
  'panel.run.seconds': { one: '{count} sec', other: '{count} sec' },
  'panel.run.minutes': { one: '{count} min', other: '{count} min' },
  'panel.run.hoursMinutes': { one: '{count} h {minutes} min', other: '{count} h {minutes} min' },
  'settings.usedPosition': '{class} #{position}',
  // Review toasts and the sidebar badge.
  'notify.decision': '{id} “{title}” — the decision is yours',
  'notify.ready': '{id} “{title}” is ready — waiting for acceptance',
  'notify.planWaiting': 'in the plan “{title}”: {count} waiting for acceptance',
  'notify.waitingCount': { one: '{n} task is waiting for acceptance', other: '{n} tasks are waiting for acceptance' },
  'notify.hide': 'Hide notification',
  'notify.open': 'Open',
  'notify.badge': 'Orchestration',
  'notify.badgeWaiting': 'Orchestration · {n} waiting — {locations}',
  'panel.app.repoWaiting': { one: '{count} waiting', other: '{count} waiting' },
  'panel.app.repoRunning': { one: '{count} running', other: '{count} running' },
  'panel.app.repoMark': { one: '● {count} in {repo}', few: '● {count} in {repo}', many: '● {count} in {repo}', other: '● {count} in {repo}' },
  // API failures: one name per server error code, so the code stays stable when the words change.
  'actions.declined': 'Cancelled in the confirmation dialog',
  'actions.unknownRepo': 'The repository is not connected to the plugin',
  'actions.unknownTask': 'Task not found',
  'actions.noWorktree': 'The task has no working copy',
  'actions.running': 'The task is already running',
  'actions.blocked': 'The task is waiting on its dependencies',
  'actions.notReviewable': 'Some tasks are no longer waiting for acceptance — refresh your selection',
  'actions.forbidden': 'dsh rejected the request',
  'actions.failed': 'That didn’t work: {error}',
  'actions.noConnection': 'No connection to the dsh server',
  // Working-copy reasons and the cleanup policy.
  'worktree.policy.afterAccept': 'after acceptance',
  'worktree.policy.onCommand': 'on command',
  'worktree.policy.keepAlways': 'keep always',
  'panel.task.tab.overview': "Overview",
  'panel.task.tab.activity': "Activity",
  'panel.task.tab.changes': "Changes",
  'panel.task.tab.contract': "Contract",
  'panel.task.tab.notes': "Your actions",
  'panel.task.tab.links': "Links",
  'panel.task.copyRemoveFailed': "Could not remove the copy. Refresh the list and try again.",
  'panel.task.copyRemains': "The copy is still on disk",
  'panel.task.serverUnavailable': "Cannot reach the dsh server",
  'panel.task.aria': "Task: {title}",
  'panel.task.start': "Start",
  'panel.task.worker': "Worker",
  'panel.task.auto': "Auto — by rules",
  'panel.task.steer': "Give direction…",
  'panel.task.stop': "Stop",
  'panel.task.accept': "Accept",
  'panel.task.acceptDecision': "Accept decision",
  'panel.task.sendBackMore': "Send back…",
  'panel.task.blocker': "What is blocking this?",
  'panel.task.noAction': "Task accepted — no action needed.",
  'panel.task.autoHint': "Auto for “{class}” — the first enabled worker will start",
  'panel.task.classHint': "Task class: “{class}”",
  'panel.task.decisionHelpTitle': "What to do",
  'panel.task.decisionAcceptHelp': "Accept decision — confirms you have checked it and agree.",
  'panel.task.decisionReturnHelp': "Send back… — explain what is wrong; the orchestrator will get your reason.",
  'panel.task.confirmHint': "Confirm in the macOS dialog",
  'panel.task.steerLabel': "Direction for the worker",
  'panel.task.steerPlaceholder': "What should change? One or two sentences",
  'panel.task.steersLabel': 'Corrections',
  'panel.task.steerState.queued': 'Queued',
  'panel.task.steerState.sent': 'Sent',
  'panel.task.steerState.acknowledged': 'Acknowledged',
  'panel.task.steerState.abandoned': 'Not delivered',
  'panel.task.steerState.refused': 'Refused',
  'panel.task.steerReason.run_finished': 'The run finished before this correction was sent.',
  'panel.task.steerReason.run_failed': 'The run failed before this correction was sent.',
  'panel.task.steerReason.cancelled': 'The run was cancelled before this correction was sent.',
  'panel.task.steerDelivered': "Direction written to the running worker. Check the feed for its effect.",
  'panel.task.steerFailed': "Direction was not written: {reason}",
  'panel.task.steerRefused': "Direction refused: the last run is {state}. Your text is still here.",
  'panel.task.relaunchWithCorrection': "Relaunch with this direction",
  'panel.task.send': "Send",
  'panel.task.cancel': "Cancel",
  'panel.task.reasonLabel': "Reason for sending back",
  'panel.task.decisionReasonPlaceholder': "What is wrong? The orchestrator will get your reason",
  'panel.task.reasonPlaceholder': "Why send this back? The worker will see your reason",
  'panel.task.sendBack': "Send back",
  'panel.task.run': "Run",
  'panel.task.copyRemoved': "Copy removed",
  'panel.task.copyBranch': "Copy branch",
  'panel.task.baselineGreen': "Baseline ✓ green on {commit} · {at}",
  'panel.task.baselineRed': "Baseline ✗ red on {commit} · {at} — the next launch runs it again",
  'panel.task.copyPath': "Copy worktree path",
  'panel.task.copyLink': 'Copy link to task',
  'panel.task.removeCopy': "Remove copy",
  'panel.task.pickRun': "Run",
  'panel.task.runNumber': "Run {count}",
  'panel.task.openLedger': "Open run ledger",
  'panel.task.details': "Task details",
  'panel.task.tab.changesCount': { one: "Changes · {count}", other: "Changes · {count}" },
  'panel.tabs.outcome.completed': "completed",
  'panel.tabs.outcome.failed': "failed",
  'panel.tabs.outcome.cancelled': "stopped",
  'panel.tabs.note.steer': "direction",
  'panel.tabs.note.reject': "sent back",
  'panel.tabs.note.accept': "acceptance",
  'panel.tabs.note.comment': "note",
  'panel.tabs.note.check': "check",
  'feed.note.by': " ({by})",
  'feed.note.checkDue': "check due: the orchestrator checks the work before it waits for you",
  'feed.note.checkTaken': "checking{by}",
  'feed.note.checked': "checked{by}: {note}",
  'feed.note.checkReturned': "returned to the worker{by}: {findings}",
  'feed.note.checkSkipped': "check skipped: the orchestrator check was turned off",
  'feed.note.verdict': "verdict: {verdict}",
  'feed.note.accepted': "accepted by a person",
  'feed.note.evidence': "evidence: {evidence}",
  'feed.note.superseded': "superseded by task {by}",
  'feed.note.outsidePreset': "Launched by hand outside the preset “{preset}”: {worker}",
  'feed.note.presetFallback': "Worker {stale}, chosen by an agent, is no longer in the preset “{preset}” for this class — ran by the preset order instead: {worker}. The assignment was cleared.",
  'feed.note.steer': "{state} [{id}]{detail}: {message}",
  'feed.note.steer.delivered': "delivered",
  'feed.note.steer.refused': "refused",
  'feed.note.steer.failed': "not delivered",
  'feed.note.steer.abandoned': "not applied",
  'feed.note.worktree.removed': "Worktree removed after acceptance.",
  'feed.note.worktree.kept_recent': "Worktree kept: one of the three most recently accepted.",
  'feed.note.worktree.kept_unmerged': "Worktree kept: branch is not merged yet.",
  'panel.tabs.feedLoading': "Loading feed…",
  'panel.tabs.humanDecision': "This is a human decision: no worker or model is involved — your acceptance closes it",
  'panel.tabs.afterTasks': " after tasks {tasks}",
  'panel.tabs.decisionAccepted': " Accepted {time} ({text}).",
  'panel.tabs.noEvents': "No events yet — this run has not done anything.",
  'panel.tabs.yourSteer': "Your direction",
  'panel.tabs.fileDiff': "file diff",
  'panel.tabs.changesLoading': "Loading changes…",
  'panel.tabs.noChanges': "No changes: the worktree matches its branch point.",
  'panel.tabs.emptyDiff': "Empty diff.",
  'panel.preview.preview': 'Preview',
  'panel.preview.diff': 'Diff',
  'panel.preview.fullSize': 'Open full size',
  'panel.preview.close': 'Close',
  'panel.preview.before': 'Before',
  'panel.preview.after': 'After',
  'panel.preview.zoom': 'Click to toggle fit / 1:1',
  'panel.preview.newTab': 'Open in a new tab',
  'panel.preview.sandbox': 'Sandboxed render. See Diff for source.',
  'panel.preview.rows': '{count} rows',
  'panel.preview.cleaned': 'The task copy was removed.',
  'panel.preview.tooLarge': 'File exceeds the 25 MB preview limit.',
  'panel.preview.unavailable': 'Preview unavailable.',
  'panel.preview.loading': 'Loading preview…',
  'panel.preview.overlay': 'Overlay slider',
  'panel.preview.sideBySide': 'Side by side',
  'panel.preview.slider': 'Compare before and after',
  'panel.preview.fontSample': 'Aa Bb Cc 123 · The quick brown fox',
  'panel.preview.entitiesNotShown': 'entities not shown',
  'panel.tabs.contractLoading': "Loading contract…",
  'panel.tabs.noContract': "No contract: the worker will receive only the task title.",
  'panel.tabs.truncated': "truncated",
  'panel.tabs.runsLoading': "Loading runs…",
  'panel.tabs.noRuns': "This task has not been run yet.",
  'panel.tabs.runActive': "running",
  'panel.tabs.trace': "Trace",
  'panel.tabs.notesLoading': "Loading your actions…",
  'panel.tabs.noNotes': "No directions or decisions yet.",
  'panel.tabs.notesLabel': "Directions and decisions",
  'panel.tabs.before': "Before this task",
  'panel.tabs.noDependencies': "depends on nothing",
  'panel.tabs.after': "After this task",
  'panel.tabs.noDependents': "nothing depends on this task",
  'panel.tabs.fileCount': { one: "{count} change", other: "{count} changes" },
  'panel.tabs.actionCount': { one: "{count} command", other: "{count} commands" },
  'panel.decision.whatToCheck': "What to check",
  'panel.decision.contractTruncated': "Contract text is truncated",
  'panel.decision.noChecklist': "The orchestrator left no checklist",
  'panel.decision.whereToLook': "Where to look",
  'panel.decision.countUnavailable': "Changed file count unavailable",
  'panel.decision.countLoading': "Loading changed file details",
  'panel.decision.negativeResult': "Negative result",
  'panel.decision.disputedVerdict': "Verdict disputed",
  'panel.decision.resultReceived': "Result received",
  'panel.decision.verdictUnavailable': "Verdict unavailable",
  'panel.decision.modelUnknown': "Model not specified",
  'panel.decision.filesUnavailable': "file count unavailable",
  'status.checking': "orchestrator is checking",
  'check.pending': "Orchestrator is checking — the work reaches you when it is done",
  'check.checking': "Orchestrator is checking — the work reaches you when it is done",
  'check.checked': "Checked by the orchestrator",
  'check.acceptEarly': "The orchestrator has not finished checking — accept without it?",
  'check.acceptAnyway': "Accept without the check",
  'check.setting.title': "Orchestrator checks finished work",
  'check.setting.help': "On: a finished task first goes to the orchestrator; it reaches you with the orchestrator’s note. Off: straight to you.",
  'check.setting.repository': "Orchestrator check in {repo}",
  'check.setting.plan': "Orchestrator check in this plan",
  'check.setting.byChat': "On while the plan has a chat",
  'check.setting.asRepository': "As the repository",
  'check.setting.on': "On",
  'check.setting.off': "Off",
  'check.setting.inForceOn': "In force: on ({source})",
  'check.setting.inForceOff': "In force: off ({source})",
  'check.setting.source.plan': "plan",
  'check.setting.source.repository': "repository",
  'check.setting.source.chat': "the plan has an orchestrator chat",
  'check.setting.source.default': "no orchestrator chat",
  'review.check.checked': "after the orchestrator check",
  'review.check.unchecked': "before the orchestrator finished checking",
  'status.closedNegative': 'closed: no result',
  'panel.decision.closedNegative': " · Closed with a negative result",
  'panel.decision.noPredecessors': "No tasks before this decision",
  'panel.decision.fileCount': { one: "{count} file", other: "{count} files" },
  'panel.decision.totalChanged': { one: "{files} changed in the tasks below", other: "{files} changed in the tasks below" },
  'panel.decision.filesChanged': { one: "{files} changed", other: "{files} changed" },
  'panel.trace.lane.input': "input",
  'panel.trace.lane.model': "model",
  'panel.trace.lane.tools': "tools",
  'panel.trace.lane.watch': "watch",
  'panel.trace.fromStep': "From step “{step}”: ",
  'panel.trace.steerFrom': "Give direction from here…",
  'panel.trace.relaunchFrom': "Relaunch from step",
  'panel.trace.steer': "Give direction…",
  'panel.trace.more': "More",
  'panel.trace.relaunchHint': "New run in the same worktree: the worker receives the contract, the previous run’s result and this step.",
  'panel.trace.worker': "Worker",
  'panel.trace.workerInstruction': "Instruction for the worker",
  'panel.trace.instructionPlaceholder': "What should change? One or two sentences",
  'panel.trace.relaunch': "Relaunch",
  'panel.trace.cancel': "Cancel",
  'panel.trace.started': "Run started:",
  'panel.trace.selectStep': "Select a step on a lane to see its time, duration and result.",
  'panel.trace.runStep': "Run step",
  'panel.trace.close': "Close",
  'panel.trace.approximate': "Duration is approximate: the worker did not say when this step ended.",
  'panel.trace.feedHint': "The response text and command output are in the task panel’s Feed tab.",
  'panel.trace.serverUnavailable': "Cannot reach the dsh server",
  'panel.trace.statusRunning': "running · {time}",
  'panel.trace.statusFinishedTime': "finished · {time}",
  'panel.trace.statusFinished': "finished",
  'panel.trace.viewLanes': "Lanes",
  'panel.trace.viewJournal': "Events",
  'panel.trace.viewCompare': "Compare runs",
  'panel.trace.compareUnavailable': "Nothing to compare: this task has fewer than two runs",
  'panel.trace.aria': "Trace for run {id}",
  'panel.trace.viewLabel': "Trace view",
  'panel.trace.backToPlan': "Back to plan",
  'panel.trace.unavailable': "Trace unavailable: {error}",
  'panel.trace.loading': "Gathering run steps…",
  'panel.trace.noSteps': "No steps yet. Lanes will fill as soon as the worker starts.",
  'panel.trace.time': "Time",
  'panel.trace.timeBreakdown': "{total} · model {model} · tools {tools}",
  'panel.trace.steps': "Steps",
  'panel.trace.context': "Context",
  'panel.trace.contextUsage': "{used}k of {size}k",
  'panel.trace.noData': "no data",
  'panel.trace.nearbyMarks': { one: "{count} nearby mark", other: "{count} nearby marks" },
  'panel.trace.marksAt': { one: "{count} mark, {time}", other: "{count} marks, {time}" },
  'panel.trace.toolCalls': { one: "{count} tool", other: "{count} tools" },
  'panel.trace.step.input': "input",
  'panel.trace.step.model': "model step",
  'panel.trace.step.read': "read",
  'panel.trace.step.edit': "edit",
  'panel.trace.step.cmd': "command",
  'panel.trace.step.tool': "tool",
  'panel.trace.step.problem': "problem",
  'panel.compare.outcome.completed': "finished",
  'panel.compare.outcome.failed': "failed",
  'panel.compare.outcome.cancelled': "stopped",
  'panel.compare.running': "running",
  'panel.compare.timeUnknown': "duration is not known for both runs",
  'panel.compare.slower': "the second run was {factor}× slower",
  'panel.compare.faster': "the second run was {factor}× faster",
  'panel.compare.sameTime': "their times were nearly equal",
  'panel.compare.sameSteps': "the same number of steps",
  'panel.compare.answer': "Difference: {time}, {steps}.",
  'panel.compare.traceUnavailable': "{label}: trace unavailable",
  'panel.compare.onlyOneRun': "Nothing to compare: this task has one run.",
  'panel.compare.duration': "Duration",
  'panel.compare.steps': "Steps",
  'panel.compare.activity': "Reads / edits / commands",
  'panel.compare.steers': "Directions",
  'panel.compare.outcome': "Outcome",
  'panel.compare.aria': "Run comparison",
  'panel.compare.firstRun': "First run",
  'panel.compare.secondRun': "Second run",
  'panel.compare.runSteps': "Steps in run {id}",
  'panel.compare.difference': "Difference",
  'panel.compare.what': "Measure",
  'panel.compare.scaleHint': "The shared scale starts at each run’s beginning and spans the longer run.",
  'panel.compare.runLabel': { one: "Run {count} · {agent}", other: "Run {count} · {agent}" },
  'panel.compare.moreSteps': { one: "{count} more step", other: "{count} more steps" },
  'panel.compare.fewerSteps': { one: "{count} fewer step", other: "{count} fewer steps" },
  "welcome.eyebrow": "Orchestrator",
  "welcome.headline": "Break work into tasks and hand them to workers",
  "welcome.lead": "Keep the goal in a plan, let workers take tasks, then review what they return.",
  "welcome.setup": "Setup",
  "welcome.progress": "{count} of 3",
  "welcome.workers": "Workers found",
  "welcome.worker.ready": "ready",
  "welcome.worker.sign_in": "sign in",
  "welcome.worker.missing": "missing",
  "welcome.checking": "Checking…",
  "welcome.openWorkers": "Open Workers settings",
  "welcome.preset": "Preset chosen",
  "welcome.presetValue": "{preset} · {source}",
  "welcome.choosePreset": "Choose a preset",
  "welcome.repository": "Repository check",
  "welcome.recipeFound": "Recipe saved",
  "welcome.recipeMissing": "No recipe yet",
  "welcome.recipeHelp": "A recipe prepares each worker copy and runs a baseline check before work starts.",
  "welcome.editRecipe": "Edit recipe",
  "welcome.start": "How to start",
  "welcome.fromSpec": "From a spec",
  "welcome.fromSpecHelp": "Bring a document from disk, paste text or pick a repository file, then review the draft plan.",
  "welcome.fromChat": "From chat",
  "welcome.fromChatHelp": "Ask the orchestrator to draft a plan.",
  "welcome.chatPrompt": "Draft a plan for this repository with orchestra_plan_draft. Show me the draft for review before approving it.",
  "welcome.example": "See an example",
  "welcome.exampleHelp": "Explore tasks, a worker run, and a review.",
  "welcome.emptyPlan": "Or an empty plan",
  "welcome.goal": "Plan goal",
  "welcome.create": "Create plan",
  "welcome.cliHint": "In a terminal: orch init",
  "welcome.addRepository": "Add a repository",
  "welcome.noRepos": "Open a dsh workspace, run `crewboard repo add` in a repository, or add a path in the repos setting.",
  "welcome.openSettings": "Open settings",
  "welcome.recipeTitle": "Repository recipe",
  "welcome.setupCommands": "Setup commands, one per line",
  "welcome.baseline": "Baseline test command",
  "welcome.timeout": "Timeout, seconds",
  "welcome.save": "Save recipe",
  "welcome.cancel": "Cancel",
  "welcome.pickSpec": "Choose a spec",
  "welcome.specFromDisk": "From disk",
  "welcome.specPaste": "Paste text",
  "welcome.specFromRepo": "From the repository",
  "welcome.specDrop": "Drop a file here or choose one from your computer.",
  "welcome.specChoose": "Choose a file",
  "welcome.specChooseOther": "Choose another file",
  "welcome.specPicked": "{name} · {size}",
  "welcome.specTypes": "Supported: {types}, up to {limit}. PDF and Word are not supported yet — save them as text or paste the text.",
  "welcome.specPasteLabel": "Spec text (Markdown works)",
  "welcome.specPastePlaceholder": "# Goal\n\nWhat should be built, for whom, and how you will check it…",
  "welcome.specSavedTo": "The text is saved in the repository under .orchestration/specs/ before drafting.",
  "welcome.specSearch": "Search",
  "welcome.specSearchPlaceholder": "File name or folder",
  "welcome.specNoMatch": "No files match the search.",
  "welcome.specSaving": "Saving…",
  "welcome.specUnsupported": "This file type is not supported. Use {types}.",
  "welcome.specTooLarge": "The spec is {size}; the limit is {limit}.",
  "welcome.specOverLimit": "The spec is larger than {limit}.",
  "welcome.specEmpty": "The spec is empty.",
  "welcome.specBadName": "The file name must not contain a folder path.",
  "welcome.noSpecs": "No Markdown or text files found in this repository.",
  "welcome.draft": "Draft plan",
  "welcome.error": "The action failed. Try again.",
  "welcome.exampleLabel": "Example",
  "welcome.syntheticData": "Example data: these runs and costs are made up for the tour and never count toward real spending.",
  "welcome.removeExample": "Remove example",
  "welcome.tourNext": "Next",
  "welcome.tourBack": "Back",
  "welcome.tourSkip": "Skip",
  "welcome.tourDone": "Done",
  "welcome.tourCount": "{step} of {total}",
  "welcome.tour1": "Look at the highlighted task «Build the welcome screen». Arrows show what it waits for: the outline and the copy. Colours show status — accepted, running, waiting, returned.",
  "welcome.tour2": "Work sorts every task by status. Find the running worker, the task waiting for your review, and the returned and failed ones.",
  "welcome.tour3": "This is the worker's report with its checks. Read it, open a run to see its step ledger and cost, then accept or send back the task.",
  "welcome.tour4": "Your turn: start a plan from a spec, a chat or an empty goal here. You can remove the example from the plan menu.",
  "welcome.showAgain": "Show the introduction again",
  "welcome.exampleImage": "Example image preview",
  "welcome.unsetEnv": "Unset environment variables, comma separated",
  "welcome.chatOpened": "Chat started. Open its conversation in dsh.",
  "welcome.exampleReadOnly": "Example only · actions are disabled",
  "welcome.returned": "Returned",
  'panel.ledger.summary': '{total} steps; retained steps {from}–{to}',
  'panel.ledger.completeness.complete': 'Complete recorded history',
  'panel.ledger.completeness.partial': 'Recorded history may be incomplete',
  'panel.ledger.completeness.live': 'Live history',
  'panel.ledger.loaded': 'Loaded {count} of {total} steps',
  'panel.ledger.more': 'Load next 100 steps',
  'panel.ledger.latest': 'Jump to latest',
  'panel.ledger.loadError': 'Could not load steps. Try again.',
  'panel.ledger.loadOutput': 'Load more ({size} characters)',
  'panel.ledger.zoomIn': 'Zoom in',
  'panel.ledger.zoomOut': 'Zoom out',
  'panel.ledger.rangeStart': 'Set range start',
  'panel.ledger.rangeEnd': 'Set range end',
  'panel.ledger.matches': '{count} matching steps',
  'panel.ledger.searching': 'Loading remaining steps…',
  'panel.ledger.open': 'Open',
  'panel.ledger.approximate': '{count} approximate marks',
  'panel.ledger.stepLink': 'Link to this step',
  'panel.ledger.title': 'Run ledger',
  'panel.ledger.totals': 'Run totals',
  'panel.ledger.duration': 'Duration',
  'panel.ledger.tokens': 'Tokens in / out / cache',
  'panel.ledger.money': 'Money / quota',
  'panel.ledger.wait': 'Decision wait',
  'panel.ledger.outcome': 'Outcome',
  'panel.ledger.outcome.running': 'Running',
  'panel.ledger.outcome.completed': 'Completed',
  'panel.ledger.outcome.failed': 'Failed',
  'panel.ledger.outcome.cancelled': 'Stopped',
  'panel.ledger.outcome.accepted': 'Accepted',
  'panel.ledger.outcome.awaiting': 'Awaiting review',
  'panel.ledger.outcome.returned': 'Returned',
  'panel.ledger.overview': 'Overview',
  'panel.ledger.clear': 'Clear focus',
  'panel.ledger.timeline': 'Run timing overview; arrows select steps, Home and End jump, use range and zoom controls',
  'panel.ledger.contextLine': 'Recorded context occupancy',
  'panel.ledger.cumulativeTokens': 'Cumulative recorded tokens',
  'panel.ledger.cumulativeCost': 'Cumulative recorded cost',
  'panel.ledger.search': 'Search records',
  'panel.ledger.records': 'Run records',
  'panel.ledger.inspector': 'Record inspector',
  'panel.ledger.copy': 'Copy',
  'panel.ledger.turn': 'Turn {n}',
  'panel.ledger.context': 'Context used',
  'panel.ledger.state': 'State',
  'panel.ledger.input': 'Input',
  'panel.ledger.output': 'Output',
  'panel.ledger.select': 'Select a record to inspect its input and output.',
  'panel.ledger.kind.request': 'Request',
  'panel.ledger.kind.model': 'Model',
  'panel.ledger.kind.tool': 'Tool',
  'panel.ledger.kind.edit': 'Edit',
  'panel.ledger.kind.check': 'Check',
  'panel.ledger.kind.steer': 'Steer',
  'panel.ledger.kind.problem': 'Problem',
  'panel.ledger.kind.final': 'Final',
  'settings.notify.title': 'Notifications',
  'settings.notify.hint': 'Choose how crewboard tells you that work is waiting. Browser notifications appear only while this tab is hidden.',
  'settings.notify.browser': 'Browser',
  'settings.notify.macos': 'macOS',
  'settings.notify.off': 'Off',
  'settings.notify.granted': 'Permission: granted',
  'settings.notify.denied': 'Permission: denied',
  'settings.notify.default': 'Permission: not requested',
  'settings.notify.unsupported': 'Permission: unsupported by this browser',
  'settings.notify.allow': 'Allow browser notifications',
  'settings.notify.blocked': 'Notifications are blocked in the browser settings for this site. Allow them there, then retry.',
  // rv6 · Review redesign: top band, progress, time, money, run rows and strip.
  'review.title': 'Review',
  'review.eyebrow': 'Plan overview',
  'review.unavailableLoad': 'Review data is unavailable right now.',
  'review.newerSnapshot': 'A newer snapshot is ready.',
  'review.needs.title': 'Needs you',
  'review.needs.waiting': { one: '{count} decision is waiting for you', other: '{count} decisions are waiting for you' },
  'review.needs.none': 'No decision is waiting for you',
  'review.needs.more': { one: 'and {count} more', other: 'and {count} more' },
  'review.needs.running': { one: '{count} task is running. Check it or browse a run below.', other: '{count} tasks are running. Check them or browse a run below.' },
  'review.needs.idle': 'Nothing is running. Browse a run below.',
  'review.needs.failed': { one: '{count} failed task needs a follow-up; it is not accepted.', other: '{count} failed tasks need a follow-up; they are not accepted.' },
  'review.needs.showFailed': 'Show failed runs',
  'review.needs.open': 'Open waiting tasks',
  'review.needs.runs': 'See runs',
  'review.progressTitle': 'Plan progress',
  'review.scopeLine': '{total} in scope · {superseded} superseded not counted',
  'review.acceptedOf': '{total} accepted',
  'review.bucket.accepted': 'Accepted',
  'review.bucket.running': 'Running',
  'review.bucket.ready': 'Ready',
  'review.bucket.queued': 'Queued',
  'review.bucket.attention': 'Needs attention',
  'review.verdicts': 'Of accepted: {result} result verified · {disputed} disputed · {negative} negative · {untyped} outcome untyped (older decisions)',
  'review.noTasks': 'No plan tasks yet.',
  'review.notObserved': 'Not observed',
  'review.noMeasurements': 'No measurements yet',
  'review.time.title': 'Elapsed since first run',
  'review.time.worker': 'Worker time',
  'review.time.wait': 'Review wait',
  'review.unitsNote': 'Separate units; no combined total',
  'review.quotaNote': 'Account-window before/after change',
  'review.legacyQuota': 'Older samples have no window',
  'review.noSubscriptionRuns': 'No subscription runs',
  'review.noApiRuns': 'No API-billed runs',
  'review.moreWindows': { one: '+{count} window', other: '+{count} windows' },
  'review.coverageLine': 'Measured on {known} of {total} runs',
  'review.coverageNone': 'No run this applies to',
  'review.lastMeasured': 'latest run {time}',
  'review.runsTitle': 'Runs to inspect',
  'review.statusFilter': 'Status',
  'review.show': 'Show',
  'review.direction': 'Sort direction',
  'review.moneyPerRun': 'Show money per run',
  'review.noRunsLong': 'No runs yet. Once a worker starts, its steps will appear here.',
  'review.noMatchesLong': 'No matching runs. The search and filters are kept.',
  'review.clearSearch': 'Clear search',
  'review.investigation.waiting': 'tasks waiting for you',
  'review.investigation.multiple': 'tasks with several attempts',
  'review.status.running': 'Running',
  'review.status.waiting': 'Waiting for you',
  'review.status.failed': 'Failed',
  'review.status.stopped': 'Stopped',
  'review.status.accepted': 'Accepted',
  'review.status.returned': 'Returned',
  'review.status.completed': 'Completed',
  'review.status.unknown': 'Outcome unknown',
  'review.kind.model': 'Model',
  'review.kind.tool': 'Tools',
  'review.kind.edit': 'Edits',
  'review.kind.check': 'Checks',
  'review.kind.steer': 'Steers',
  'review.kind.request': 'Human input',
  'review.kind.problem': 'Problems',
  'review.legend': 'Step colours',
  'review.steps.aria': 'Recorded steps: {counts}',
  'review.steps.note': { one: '{count} step', other: '{count} steps' },
  'review.steps.complete': 'complete history',
  'review.steps.partial': 'history may be incomplete',
  'review.steps.live': 'live',
  'review.steps.none.complete': 'No steps recorded',
  'review.steps.none.partial': 'Step history unavailable',
  'review.steps.none.live': 'No steps yet',
  'review.steps.unavailable': 'Step overview unavailable',
  'review.steps.timing.elapsed': 'placed by elapsed time',
  'review.steps.timing.sequence': 'placed by order; no measured span',
  'review.steps.problems': { one: '{count} problem', other: '{count} problems' },
  'review.steps.route': 'Step overview; choose a cell to open its first step',
  'review.steps.cell': '{kind}: {count} steps from #{index}',
  'review.runDetail': 'Run detail',
  'review.close': 'Close',
  'review.copyLink': 'Copy link',
  'review.linkCopied': 'Link copied',
  'review.runMoney': 'Money or quota',
  'review.allFacts': 'All run facts',
} as const
