export const ru = {
  'menu.aria': 'Действия с задачей',
  'menu.accept': 'Принять…',
  'menu.acceptSelected': 'Принять выбранные…',
  'menu.openEditor': 'Открыть рабочую копию в редакторе',
  'menu.revealFinder': 'Показать в Finder',
  'menu.return': 'Вернуть с причиной…',
  'menu.report': 'Открыть отчёт и проверки',
  'menu.launch': 'Запустить',
  'menu.launchWorker': 'Запустить воркером',
  'menu.direction': 'Дать направление…',
  'menu.relaunch': 'Перезапустить с контекстом…',
  'menu.ledger': 'Журнал запуска',
  'menu.changes': 'Изменённые файлы',
  'menu.contract': 'Контракт',
  'menu.highlight': 'Подсветить цепочку',
  'menu.showGraph': 'Показать на графе',
  'menu.follow': 'Задача-продолжение…',
  'menu.askAgent': 'Попросить агента спланировать продолжение',
  'menu.chatPrompt': 'Предложи задачи-продолжения по этой задаче и замечаниям проверки.',
  'menu.chatTask': 'Задача',
  'menu.chatVerdict': 'Вердикт',
  'menu.chatReport': 'Отчёт',
  'menu.chatFindings': 'Замечания',
  'menu.chatUnknown': 'неизвестно',
  'menu.chatNoReport': 'Отчёта пока нет.',
  'menu.chatNone': 'Не зафиксированы.',
  'menu.chatTool': 'Используй orchestra_task_upsert или подготовь черновик плана для большого набора задач.',
  'menu.copyLink': 'Скопировать ссылку на задачу',
  'menu.copyId': 'Скопировать id задачи',
  'menu.copyCommand': 'Скопировать команду orch',
  'menu.backlog': 'Переместить в бэклог',
  'menu.ready': 'Отметить готовой',
  'menu.supersede': 'Заменить новой задачей…',
  'menu.drop': 'Закрыть как ненужную…',
  'menu.dropReason': 'Почему задача не нужна?',
  'menu.dropConfirm': 'Закрыть задачу',
  'menu.title': 'Название задачи',
  'menu.class': 'Класс',
  'menu.lane': 'Дорожка',
  'menu.depends': 'Зависит от родителя',
  'menu.note': 'Что сделать',
  'menu.confirm': 'Создать задачу',
  'actions.backendUnavailable': 'Для этого воркера нет доступного прямого бэкенда.',
  'actions.legacyReadOnly': 'Этот старый запуск доступен только для чтения. Для новых указаний создайте новый запуск.',
  'actions.planArchived': 'План в архиве и открыт только для чтения. Чтобы менять его, восстановите план через меню плана.',
  'panel.planError.incompatible': 'План записан более новой версией Crewboard. Обновите Crewboard, чтобы открыть или менять его.',
  'timeline.run': 'работает воркер',
  'timeline.review': 'ждёт приёмки человеком',
  'timeline.dependency': 'ждёт зависимость',
  'timeline.unavailable': 'Время плана недоступно: {error}',
  'timeline.loading': 'Считаю время плана…',
  'timeline.noRuns': 'Запусков ещё не было — время плана появится, как только задача уйдёт воркеру.',
  'timeline.title': 'Время плана',
  'timeline.summary': 'план шёл {plan} · воркеры работали {work}',
  'timeline.now': 'сейчас',
  'timeline.speedup': 'Что ускорит план:',
  'timeline.criticalPath': 'Критический путь',
  'timeline.undefined': 'не определён',
  'timeline.humanWait': 'Ожидание человека',
  'timeline.parallelism': 'Параллельность',
  'timeline.maxParallel': 'макс. {workers} одновременно',
  'language.ru': 'Русский',
  'verdict.result': 'Результат получен',
  'verdict.negative': 'Отрицательный результат',
  'verdict.disputed': 'Спорно',
  'verdict.facts': 'Факты работы',
  'verdict.checksInReport': 'Проверки в отчёте',
  'verdict.fact.files_changed': { one: 'изменено файлов: {count}', few: 'изменено файлов: {count}', many: 'изменено файлов: {count}', other: 'изменено файлов: {count}' },
  'verdict.fact.no_changes': 'изменений нет',
  'verdict.fact.journal': 'журнал отклонений указан',
  'verdict.fact.duration': 'длительность: {time}',
  'verdict.fact.checks_not_run': 'проверки не запускались',
  'verdict.fact.checks_run': { one: 'по отчёту запущена проверка контракта: {count}', other: 'по отчёту запущены проверки контракта: {count}' },
  'verdict.fact.uncommitted': { one: 'не закоммичено файлов: {count} — их нет в ветке', few: 'не закоммичено файлов: {count} — их нет в ветке', many: 'не закоммичено файлов: {count} — их нет в ветке', other: 'не закоммичено файлов: {count} — их нет в ветке' },
  'verdict.fact.checks_unreported': { one: 'проверка контракта не упомянута: {count}', few: 'проверки контракта не упомянуты: {count}', many: 'проверок контракта не упомянуто: {count}', other: 'проверки контракта не упомянуты: {count}' },
  'verdict.fact.checks_unreadable': { one: 'проверку контракта не удалось прочитать: {count}', few: 'проверки контракта не удалось прочитать: {count}', many: 'проверок контракта не удалось прочитать: {count}', other: 'проверки контракта не удалось прочитать: {count}' },
  'verdict.why.blocked': 'работа заблокирована',
  'verdict.why.negative': 'получен отрицательный результат',
  'verdict.mismatch.run_failed': 'Заявлен результат, но последний запуск завершился с ошибкой или отменой.',
  'verdict.mismatch.no_files': 'Заявлен результат, но изменённых файлов нет.',
  'verdict.mismatch.report_missing': 'У задачи есть запуск, но отчёт отсутствует.',
  'verdict.mismatch.checks_missing': 'В отчёте не упомянуты проверки из контракта.',
  'verdict.mismatch.claim_missing': 'В отчёте нет явного заявления о результате.',
  'worktree.keep.dirty': 'есть незакоммиченные изменения', 'worktree.keep.unmerged': 'ветка не влита в основную',
  'worktree.keep.running': 'задача выполняется', 'worktree.keep.recent': 'копия принята недавно', 'worktree.keep.rejected': 'задача не принята',
  'report.title': 'Итог работы',
  'report.riskNote': 'Подсвечены строки со словами риска',
  'report.finalNote': 'Воркер не написал раздел «Отчёт» — показано начало его ответа',
  'report.showAll': 'Показать весь ответ',
  'relative.now': 'сейчас',
  'relative.minute': { one: '{n} минута', few: '{n} минуты', many: '{n} минут', other: '{n} минуты' },
  'relative.hour': { one: '{n} час', few: '{n} часа', many: '{n} часов', other: '{n} часа' },
  'relative.day': { one: '{n} день', few: '{n} дня', many: '{n} дней', other: '{n} дня' },
  'relative.month': { one: '{n} месяц', few: '{n} месяца', many: '{n} месяцев', other: '{n} месяца' },
  'relative.year': { one: '{n} год', few: '{n} года', many: '{n} лет', other: '{n} года' },
  'relative.ago': '{t} назад',
  'panel.status.backlog': 'бэклог',
  'panel.status.ready': 'можно запускать',
  'panel.status.running': 'идёт',
  'panel.status.inReview': 'ждёт приёмки',
  'panel.status.accepted': 'принята',
  'panel.status.blocked': 'ждёт',
  'panel.status.superseded': 'вытеснена',
  'panel.status.dropped': 'закрыта как ненужная',
  'panel.headline.empty': 'Задач нет',
  'panel.headline.tasks': { one: '{count} задача', few: '{count} задачи', many: '{count} задач', other: '{count} задачи' },
  'panel.headline.running': { one: '{count} идёт', few: '{count} идут', many: '{count} идут', other: '{count} идут' },
  'panel.headline.review': { one: '{count} ждёт приёмки', few: '{count} ждут приёмки', many: '{count} ждут приёмки', other: '{count} ждут приёмки' },
  'panel.headline.decisions': { one: '{count} решение за вами', few: '{count} решения за вами', many: '{count} решений за вами', other: '{count} решения за вами' },
  'panel.headline.attention': { one: '{count} требует внимания', few: '{count} требуют внимания', many: '{count} требуют внимания', other: '{count} требуют внимания' },
  'panel.duration.seconds': { one: '{count} с', few: '{count} с', many: '{count} с', other: '{count} с' },
  'panel.duration.minutes': { one: '{count} мин', few: '{count} мин', many: '{count} мин', other: '{count} мин' },
  'panel.duration.hoursMinutes': { one: '{count} ч {minutes} мин', few: '{count} ч {minutes} мин', many: '{count} ч {minutes} мин', other: '{count} ч {minutes} мин' },
  'graph.reviewLensCount': { one: 'Приёмка · {count}', few: 'Приёмка · {count}', many: 'Приёмка · {count}', other: 'Приёмка · {count}' },
  'panel.essence.blockedBy': 'ждёт: {tasks}',
  'panel.essence.waitingMerge': 'ждёт слияния {tasks}',
  'panel.essence.unmerged': 'принята, не слита',
  'panel.essence.decisionAcceptedAt': 'решение · принято вами {time}',
  'panel.essence.decisionAccepted': 'решение · принято вами',
  'panel.essence.decisionYours': 'решение за вами',
  'panel.now.decisionBlocked': 'Ждёт задач {tasks} — решать пока рано.',
  'panel.now.decisionYours': 'Решение за вами: план ждёт вашего ответа.',
  'panel.now.working': 'Работает {worker}',
  'panel.now.elapsed': 'идёт {time}',
  'panel.now.inReview': 'Работа закончена, ждёт вашей приёмки.',
  'panel.now.reviewHint': 'Посмотрите «Изменения» — и примите или верните с причиной.',
  'panel.now.ready': 'Зависимости приняты — задачу можно запускать.',
  'panel.now.blocked': 'Ждёт задачи: {tasks}.',
  'panel.now.waitingMerge': 'Ждёт слияния {tasks}.',
  'panel.now.waitingMergeHint': 'Эта работа принята, но ещё не в базовой ветке: копия, начатая сейчас, её не увидит.',
  'panel.now.acceptedUnmerged': 'Принята — ещё не слита в базовую ветку.',
  'panel.now.acceptedUnmergedHint': 'Зависящие от неё задачи ждут, пока её ветку сольют.',
  'panel.now.decisionAcceptedAt': 'Решение принято вами в {time}.',
  'panel.now.decisionAccepted': 'Решение принято вами.',
  'panel.now.accepted': 'Принята.',
  'panel.now.superseded': 'Вытеснена другим вариантом — действий не требуется.',
  'panel.now.dropped': 'Закрыта как ненужная — в очередь не вернётся.',
  'panel.now.backlog': 'Задача в бэклоге: ещё не размечена как готовая.',
  'panel.worker': 'воркер',
  'board.ready': 'Можно запускать',
  'board.running': 'Идёт',
  'board.review': 'Ждёт приёмки',
  'board.blocked': 'Ждёт',
  'board.backlog': 'Бэклог',
  'board.attentionAria': 'требует внимания',
  'board.negativeDep': 'Предшественник закрыт без результата — проверьте, актуальна ли задача',
  'board.empty': 'пусто',
  'board.collapse': 'Свернуть',
  'board.showAll': { one: 'Показать все {count}', few: 'Показать все {count}', many: 'Показать все {count}', other: 'Показать все {count}' },
  'board.expandLane': 'Развернуть дорожку {lane}',
  'board.unnamedLane': 'Без дорожки',
  'board.noTasks': 'В этом плане ещё нет задач. Добавьте их через `orch task add` или инструмент `orchestra_task_upsert`.',
  'board.attention': 'Требует внимания',
  'board.accepted': 'Приняты',
  'panel.console.emptyBlock': 'пусто',
  'panel.console.stop': 'Остановить',
  'panel.console.open': 'Открыть',
  'panel.console.run': 'Запустить',
  'panel.console.noTasks': 'В этом плане ещё нет задач. Добавьте их через `orch task add` или инструмент `orchestra_task_upsert`.',
  'panel.console.idle': 'Пульт пуст: сейчас ничего не идёт, не ждёт запуска и не требует внимания.',
  'panel.console.attention': 'Требует внимания',
  'panel.console.running': 'Идут',
  'panel.console.ready': 'Можно запускать',
  'panel.console.worker': 'воркер',
  'panel.console.deadEndsCount': 'Принято, но никуда не ведёт: {count}',
  'panel.console.deadEnds': 'Принято, но никуда не ведёт',
  'panel.console.acceptedAgo': '{worker} · принята {time}',
  'panel.console.longAgo': 'давно',
  'panel.console.deadEndsHint': 'Эти задачи закончены, и ничего от них не зависит. Если их находки ещё не применены — заведите следующую задачу и свяжите её с этой.',
  'panel.console.totals': 'Итоги плана',
  'panel.console.totalTasks': 'Всего задач',
  'panel.console.accepted': 'Принято',
  'panel.console.criticalPath': 'Критический путь',
  'graph.decisionLane': 'Решения',
  'graph.fold.taskCount': { one: '{count} задача', few: '{count} задачи', many: '{count} задач', other: '{count} задачи' },
  'graph.fold.allAccepted': 'все приняты',
  'graph.fold.allSuperseded': 'все вытеснены',
  'graph.fold.accepted': { one: '{count} принята', few: '{count} приняты', many: '{count} приняты', other: '{count} приняты' },
  'graph.fold.superseded': { one: '{count} вытеснена', few: '{count} вытеснены', many: '{count} вытеснены', other: '{count} вытеснены' },
  'graph.fold.dropped': { one: '{count} закрыта как ненужная', few: '{count} закрыты как ненужные', many: '{count} закрыты как ненужные', other: '{count} закрыты как ненужные' },
  'graph.fold.inProgress': { one: '{count} в работе', few: '{count} в работе', many: '{count} в работе', other: '{count} в работе' },
  'graph.minimap.label': 'Миникарта плана',
  'graph.search.label': 'Поиск задачи по плану',
  'graph.search.placeholder': 'Задача по названию или id…',
  'graph.search.empty': 'Ничего не нашлось.',
  'graph.search.keys': '↑↓ — выбрать · ⏎ — открыть и навести камеру · Esc — закрыть',
  'queue.decisionYours': 'решение за вами',
  'queue.files': { one: '{count} файл', few: '{count} файла', many: '{count} файлов', other: '{count} файла' },
  'queue.loadingChanges': 'Считаю изменения…',
  'queue.moreFiles': { one: '… и ещё {count}', few: '… и ещё {count}', many: '… и ещё {count}', other: '… и ещё {count}' },
  'queue.decisionNoFiles': 'Решения не правят файлы.',
  'queue.noChanges': 'Изменений нет.',
  'queue.open': 'Открыть',
  'queue.changes': 'Изменения',
  'queue.accept': 'Принять',
  'queue.sendBackMore': 'Вернуть…',
  'queue.reasonLabel': 'Причина возврата задачи {id}',
  'queue.reasonPlaceholder': 'Почему возвращаем: это увидит воркер',
  'queue.sendBack': 'Вернуть',
  'queue.cancel': 'Отмена',
  'queue.confirmHint': 'Подтвердите в окне macOS',
  'queue.otherPlanReview': { one: '{count} ждёт вас', few: '{count} ждут вас', many: '{count} ждут вас', other: '{count} ждут вас' },
  'queue.switchPlan': 'Перейти',
  'queue.title': 'Очередь приёмки',
  'queue.close': 'Закрыть очередь приёмки',
  'queue.waitingDecisions': { one: '{count} задача ждёт вашего решения', few: '{count} задачи ждут вашего решения', many: '{count} задач ждут вашего решения', other: '{count} задачи ждут вашего решения' },
  'queue.emptyPlan': 'В этом плане приёмка пуста',
  'queue.otherCount': { one: 'ещё {count} в других планах', few: 'ещё {count} в других планах', many: 'ещё {count} в других планах', other: 'ещё {count} в других планах' },
  'queue.emptyHint': 'Когда воркер закончит задачу, она появится здесь — примете её или вернёте с причиной.',
  'queue.otherPlans': 'В других планах',
  'queue.batch.waited': 'ждёт {duration}',
  'queue.batch.acceptAll': { one: 'Принять пакетом · {count}', few: 'Принять пакетом · {count}', many: 'Принять пакетом · {count}', other: 'Принять пакетом · {count}' },
  'queue.batch.dialogLabel': { one: 'Принять задачи: {count}', few: 'Принять задачи: {count}', many: 'Принять задачи: {count}', other: 'Принять задачи: {count}' },
  'queue.batch.title': 'Ждут приёмки',
  'queue.batch.selectAll': 'Выбрать все',
  'queue.batch.clearAll': 'Снять все',
  'queue.batch.open': 'Открыть',
  'queue.batch.acceptSelected': { one: 'Принять выбранные · {count}', few: 'Принять выбранные · {count}', many: 'Принять выбранные · {count}', other: 'Принять выбранные · {count}' },
  'queue.batch.cancel': 'Отмена',
  'queue.batch.confirmHint': 'Подтвердите в окне macOS',
  'queue.batch.loading': 'Читаю вердикты…',
  'queue.batch.clean': { one: 'Чистые · {count}', few: 'Чистые · {count}', many: 'Чистые · {count}', other: 'Чистые · {count}' },
  'queue.batch.risky': { one: 'Сначала открыть · {count}', few: 'Сначала открыть · {count}', many: 'Сначала открыть · {count}', other: 'Сначала открыть · {count}' },
  'queue.batch.riskyHint': 'Отрицательная, спорная или непроверенная работа не выбрана: откройте её перед приёмкой.',
  'queue.batch.verdictUnknown': 'Вердикт недоступен',
  'queue.batch.summary': 'Выбрано: чистых {clean}, с риском {risky}',
  'panel.economics.workers': { one: '{count} воркер', few: '{count} воркера', many: '{count} воркеров', other: '{count} воркера' },
  'panel.economics.turns': { one: '{count} ход', few: '{count} хода', many: '{count} ходов', other: '{count} хода' },
  'panel.economics.seconds': { one: '{count} с', few: '{count} с', many: '{count} с', other: '{count} с' },
  'panel.economics.minutes': { one: '{count} мин', few: '{count} мин', many: '{count} мин', other: '{count} мин' },
  'panel.economics.hoursMinutes': { one: '{count} ч {minutes} м', few: '{count} ч {minutes} м', many: '{count} ч {minutes} м', other: '{count} ч {minutes} м' },
  'panel.economics.week': 'нед.',
  'panel.economics.quota': 'квоты',
  'panel.economics.waitingDependency': 'ждёт зависимость: {tasks}',
  'panel.economics.working': 'работает {worker}',
  'panel.economics.waitingReview': 'ждёт приёмки человеком',
  'panel.economics.noReviewDelay': 'Приёмка план не задерживала.',
  'panel.economics.acceptSooner': 'Примите {id} сразу после завершения — {task} стартовала бы на {duration} раньше.',
  'panel.economics.currentDelay': '{id} ждёт вашей приёмки уже {duration} — это главная задержка плана.',
  'panel.economics.longestDelay': 'Дольше всего ждала приёмки {id} — {duration}.',
  'panel.economics.noConnection': 'Нет связи с сервером dsh',
  'graph.saveLayoutFailed': 'Не удалось сохранить расположение',
  'graph.startingTask': 'Запускаю {task}…',
  'graph.startTaskFailed': 'Не удалось запустить задачу',
  'graph.steerButtonPrefix': 'Поправить',
  'graph.noTasks': 'В этом плане ещё нет задач. Добавьте их через `orch task add` или инструмент `orchestra_task_upsert`.',
  'graph.collapseLane': 'Свернуть дорожку {lane}',
  'graph.collapse': 'свернуть',
  'graph.tidyLane': 'По местам: {lane}',
  'graph.tidyHere': 'по местам',
  'graph.edgeCount': { one: '{count} связь', few: '{count} связи', many: '{count} связей', other: '{count} связи' },
  'graph.selectTask': 'Выбрать задачу {id}: {title}',
  'graph.expandLane': 'Развернуть дорожку {lane}',
  'graph.unnamedLane': 'Без дорожки',
  'graph.negativeResult': 'закрыта: результата нет',
  'graph.negativePredecessor': 'предшественник закрыт без результата — проверьте, актуальна ли задача',
  "graph.handPicked": "выбран вручную",
  "graph.handPickedTitle": "Человек выбрал этого воркера вне пресета; он запускается всё равно.",
  "panel.app.outsidePreset": "Вне пресета · {count}",
  "panel.app.outsidePresetHint": "Задачи, у которых назначенный воркер не входит в текущий пресет",
  "panel.app.outsideAgentNote": "при запуске решит пресет",
  "panel.task.workerChoice": "Воркер: {worker} — {who}",
  "panel.task.chosenBy.person": "выбран вами",
  "panel.task.chosenBy.preset": "выбран пресетом",
  "panel.task.chosenBy.agent": "выбран агентом",
  "panel.task.keepAssigned": "Назначенный — {worker}",
  "panel.task.assignedHint": "{worker} · назначен, {who}",
  "panel.task.staleAssigned": "{worker} выбран агентом и не входит в пресет — при запуске решит пресет",
  "review.choice": "Выбор воркера",
  "review.choice.preset": "По пресету",
  "review.choice.hand": "Выбран вручную",
  'graph.pinned': 'закреплено вручную',
  'graph.attention': 'требует внимания',
  'graph.negativePredecessorTitle': 'Предшественник закрыт без результата — проверьте, актуальна ли задача',
  'graph.acceptWork': 'Принять работу: {title}',
  'graph.acceptHint': 'Принять — подтвердите в окне macOS',
  'graph.acceptMore': 'Принять…',
  'graph.tidyAll': 'Навести порядок',
  'graph.fit': 'Вписать (F)',
  'graph.overview': 'Обзор (O)',
  'graph.overviewHint': 'Показать весь план целиком — издали задачи становятся цветными блоками',
  'graph.criticalPath': { one: 'Критический путь · {count}', few: 'Критический путь · {count}', many: 'Критический путь · {count}', other: 'Критический путь · {count}' },
  'graph.reviewLensHint': 'Линза «Приёмка»: подсвечивает и ведёт по задачам, ничего не скрывая (n — следующая)',
  'graph.reviewLens': 'Приёмка',
  'graph.nextLensHint': 'Следующая по линзе (n)',
  'graph.nextLens': 'Следующая по линзе',
  'graph.find': 'Найти',
  'graph.gestureHint': 'Два пальца или перетаскивание — двигать · щипок или ⌘+прокрутка — масштаб · F — вписать · O — обзор всего плана · двойной клик — приблизить · ←→ по цепочке',
  "settings.class.code": "По готовому коду",
  "settings.class.design": "Проектирование и UI",
  "settings.class.review": "Ревью",
  "settings.class.research": "Исследование",
  "panel.workerUnset": "воркер не задан",
  "panel.tab": "Оркестрация",
  "panel.guide": "План воркспейса рядом с чатом",
  "settings.section": "Crewboard",
  "settings.worktrees.loadError": "Не удалось загрузить рабочие копии",
  "settings.worktrees.connectionError": "Нет связи с сервером dsh",
  "settings.worktrees.removeError": "Не удалось убрать копии",
  "settings.worktrees.policyError": "Не удалось сохранить правило",
  "settings.worktrees.unknownSize": "размер неизвестен",
  "settings.worktrees.removable": "можно убрать",
  "settings.worktrees.dirtyDetails": "изменено: {modified}, новых: {untracked} · {paths} · {artifacts}",
  "settings.worktrees.artifactsOnly": "только артефакты сборки",
  "settings.worktrees.notArtifactsOnly": "есть и другие изменения",
  "settings.worktrees.orphanRegistered": "бесхозная папка · Git считает её worktree; только ручное решение",
  "settings.worktrees.orphanUnknown": "бесхозная папка · Git её не знает; не удаляется автоматически",
  "settings.worktrees.loading": "Загрузка копий…",
  "settings.worktrees.hide": "Скрыть",
  "settings.worktrees.show": "Показать",
  "settings.worktrees.title": "Рабочие копии",
  "settings.worktrees.confirmAria": "Подтверждение уборки копий",
  "settings.worktrees.removeExtras": "Убрать лишние",
  "settings.worktrees.empty": "Рабочих копий нет",
  "settings.worktrees.remove": "Убрать копии",
  "settings.worktrees.cancel": "Отмена",
  "settings.worktrees.policyLabel": "Правило уборки ",
  "settings.worktrees.gigabytes": "{size} ГБ",
  "settings.worktrees.summary": { one: '{count} копия · {size} ГБ', few: '{count} копии · {size} ГБ', many: '{count} копий · {size} ГБ', other: '{count} копии · {size} ГБ' },
  "settings.worktrees.removed": "Убрано: {count}",
  "settings.worktrees.remaining": "Остались: {items}",
  "settings.worktrees.confirm": { one: 'Убрать {count} копию · {size} ГБ?', few: 'Убрать {count} копии · {size} ГБ?', many: 'Убрать {count} копий · {size} ГБ?', other: 'Убрать {count} копии · {size} ГБ?' },
  "settings.worktrees.confirmUnknown": { one: 'Убрать {count} копию · {size} ГБ известного размера; размер части копий неизвестен?', few: 'Убрать {count} копии · {size} ГБ известного размера; размер части копий неизвестен?', many: 'Убрать {count} копий · {size} ГБ известного размера; размер части копий неизвестен?', other: 'Убрать {count} копии · {size} ГБ известного размера; размер части копий неизвестен?' },
  "panel.plan.running": "идёт",
  "panel.plan.review": "ждёт вас",
  "panel.plan.attention": "требует внимания",
  "panel.plan.restore": "Вернуть из архива",
  "panel.plan.archiveAction": "В архив",
  "panel.plan.collapse": "Свернуть планы",
  "panel.plan.expand": "Развернуть планы",
  "panel.plan.rename": "Переименовать…",
  "panel.plan.goalPlaceholder": "Цель плана…",
  "panel.plan.newGoal": "Цель нового плана",
  "panel.plan.new": "Новый план",
  "panel.plan.picker": "План",
  "panel.plan.archive": "Архив",
  "panel.plan.title": "Планы",
  "panel.plan.newButton": "+ Новый план",
  "panel.plan.hint": "Enter — создать и переключиться",
  "panel.plan.tasks": { one: '{count} задача', few: '{count} задачи', many: '{count} задач', other: '{count} задачи' },
  "panel.plan.actions": "Действия с планом «{goal}»",
  "panel.plan.renameLabel": "Новое название плана «{goal}»",
  "panel.plan.badge": "План «{goal}»",
  "panel.plan.archiveCount": "Архив · {count}",
  "side.title": "Репозитории",
  "side.search": "Поиск по репозиториям, планам и задачам…",
  "side.searchAria": "Поиск по репозиториям, планам и задачам",
  "side.searchEmpty": "Ничего не нашлось.",
  "side.inbox": "Ждут вас",
  "side.inboxEmpty": "Всё разобрано — вас ничего не ждёт.",
  "side.inboxUnmerged": "принята, не слита",
  "side.inboxCount": { one: '{count} ждёт вас', few: '{count} ждут вас', many: '{count} ждут вас', other: '{count} ждут вас' },
  "side.repos": "Репозитории",
  "side.plans": { one: '{count} план', few: '{count} плана', many: '{count} планов', other: '{count} плана' },
  "side.finished": { one: '{count} завершённый план', few: '{count} завершённых плана', many: '{count} завершённых планов', other: '{count} завершённых плана' },
  "side.badge.running": "{count} в работе",
  "side.badge.review": { one: '{count} ждёт приёмки', few: '{count} ждут приёмки', many: '{count} ждут приёмки', other: '{count} ждут приёмки' },
  "side.badge.failed": { one: '{count} ошибка', few: '{count} ошибки', many: '{count} ошибок', other: '{count} ошибки' },
  "side.inboxHint": "Проверки, решения и упавшие или зависшие запуски, где нужен человек, — тот же список печатает crewboard attention (--all — по всем репозиториям). Строки примера стоят под своим разделителем и не считаются.",
  "side.quiet": "Тихие · {count}",
  "side.hidden": "Скрытые · {count}",
  "side.pin": "Закрепить",
  "side.unpin": "Открепить",
  "side.hide": "Скрыть",
  "side.show": "Показать",
  "side.openChat": "Открыть чат плана",
  "side.copyAgent": "Скопировать для агента",
  "side.repoActions": "Действия для репозитория «{repo}»",
  "side.moveUp": "Переместить выше",
  "side.moveDown": "Переместить ниже",
  "side.resetOrder": "Сбросить порядок",
  "side.reposMenu": "Меню раздела репозиториев",
  "side.addRepo": "Добавить репозиторий",
  "side.addRepo.label": "Папка репозитория",
  "side.addRepo.placeholder": "/Users/you/src/app или ~/src/app",
  "side.addRepo.hint": "Вставь абсолютный путь к папке; ~ — домашняя папка. Enter — добавить.",
  "side.addRepo.error.notAbsolute": "Нужен абсолютный путь: он начинается с / или ~.",
  "side.addRepo.error.notFound": "По этому пути нет папки.",
  "side.addRepo.error.notDirectory": "По этому пути файл, а не папка.",
  "side.addRepo.error.notGit": "Эта папка не Git-репозиторий и не рабочая копия.",
  "side.addRepo.error.alreadyListed": "Этот репозиторий уже в списке.",
  "side.newPlan": "Новый план…",
  "side.removeRepo": "Убрать из списка",
  "side.removeRepo.safe": "Файлы и планы остаются на диске",
  "side.removeRepo.alsoDsh": "Останется на экране: это ещё и воркспейс dsh",
  "side.removeRepo.alsoProfile": "Останется на экране: он ещё и в настройке repos плагина",
  "side.removeRepo.dsh": "Воркспейс dsh: убери его в dsh",
  "side.removeRepo.profile": "Из настройки repos плагина в профиле dsh: измени её там",
  "side.removeRepo.worktree": "Рабочая копия репозитория из списка: видна, пока в ней есть план",
  "side.removeRepo.error": "Здесь можно убрать только папки из списка Crewboard.",
  "side.missing": "нет на диске",
  "side.missingHint": "Этой папки больше нет. Убери её через «Убрать из списка».",
  "side.worktree": "рабочая копия",
  "side.worktreeHint": "Рабочая копия {path}",
  "side.moved": "«{name}» — позиция {pos} из {count}",
  "side.lanes.aria": "Дорожки плана",
  "side.lanes.now": "Сейчас · {count}",
  "side.lanes.history": "История · {count}",
  "side.lanes.noLane": "Без дорожки",
  "side.lanes.more": "… ещё {count}",
  "side.lanes.actions": "Действия для дорожки «{lane}»",
  "side.lanes.copyLink": "Скопировать ссылку на дорожку",
  "side.lanes.count.running": "{count} в работе",
  "side.lanes.count.review": { one: '{count} ждёт вас', few: '{count} ждут вас', many: '{count} ждут вас', other: '{count} ждут вас' },
  "side.lanes.count.ready": { one: '{count} готова к запуску', few: '{count} готовы к запуску', many: '{count} готовы к запуску', other: '{count} готовы к запуску' },
  "side.lanes.count.queued": "{count} в очереди",
  "side.lanes.count.accepted": { one: '{count} принята', few: '{count} приняты', many: '{count} принято', other: '{count} принято' },
  "copyAgent.label": "Скопировать для агента",
  "copyAgent.done": "Скопировано",
  "copyAgent.hint": "Скопировать краткое описание для чата с агентом",
  "panel.draft.group": "Черновики",
  "panel.draft.badge": "Черновик «{goal}»",
  "panel.draft.blocked": "есть препятствия",
  "panel.draft.review": "Просмотр черновика",
  "panel.draft.loading": "Загрузка черновика…",
  "panel.draft.source": "Источник",
  "panel.draft.chat": "чат",
  "panel.draft.close": "Закрыть",
  "panel.draft.findings": "Замечания",
  "panel.draft.blocksApproval": "Мешает утверждению:",
  "panel.draft.advisory": "Проверьте:",
  "panel.draft.finding.cycle": "Цикл зависимостей: {tasks}",
  "panel.draft.finding.missing_dependency": "У задачи {task} нет зависимости {dependency}",
  "panel.draft.finding.missing_acceptance": "У задачи {task} нет критериев приёмки",
  "panel.draft.finding.empty_contract": "У задачи {task} нет наброска контракта",
  "panel.draft.finding.file_collision": "Задачи {tasks} обе упоминают {file}",
  "panel.draft.decisions": "Решения агента",
  "panel.draft.class": "Класс",
  "panel.draft.kind": "Тип",
  "panel.draft.deps": "Зависимости",
  "panel.draft.acceptance": "Критерии приёмки",
  "panel.draft.sources": "Источники",
  "panel.draft.contract": "Набросок контракта",
  "panel.draft.none": "Нет",
  "panel.draft.approve": "Утвердить как план",
  "panel.draft.approveBlocked": "Устраните препятствия перед утверждением",
  "panel.draft.discard": "Удалить черновик",
  "panel.draft.discardConfirm": "Удалить этот черновик?",
  "panel.draft.discardYes": "Удалить",
  "panel.draft.cancel": "Отмена",
  "panel.draft.error.invalid": "В черновике есть препятствия. Обновите и проверьте его снова.",
  "panel.draft.error.notFound": "Черновик больше не существует. Обновите список.",
  "panel.draftJob.title": "Задание черновика",
  "panel.draftJob.worker": "Воркер: {worker}",
  "panel.draftJob.attempt": "попытка {count}",
  "panel.draftJob.running": "Воркер составляет план · {time}. Страницу можно закрыть или перезагрузить — черновик появится здесь, когда будет готов.",
  "panel.draftJob.needsRepair": "Нужна починка",
  "panel.draftJob.needsRepairHelp": "Воркер ответил, но ответ не соответствует схеме PlanDraft. Ответ сохранён ниже; починка отправит его воркеру вместе с этими замечаниями.",
  "panel.draftJob.wholeAnswer": "ответ",
  "panel.draftJob.failed": "Воркер не вернул черновик",
  "panel.draftJob.failedHelp": "Причина: {error}. Повторите или отбросьте задание.",
  "panel.draftJob.recovered": "Восстановлено из запуска {run}: его ответ раньше не сохранился.",
  "panel.draftJob.answer": "Сырой ответ воркера",
  "panel.draftJob.repair": "Починить воркером",
  "panel.draftJob.retry": "Повторить",
  "panel.draftJob.discardConfirm": "Отбросить задание? Работающий воркер будет остановлен; промпты и ответы останутся в .orchestration/draft-runs.",
  "panel.draftJob.discardYes": "Отбросить задание",
  "panel.draftJob.status.running": "составляется…",
  "panel.draftJob.status.needs_repair": "нужна починка",
  "panel.draftJob.status.failed": "не удалось",
  "panel.app.work": "Работа",
  "panel.app.review": "Итоги",
  "work.needsYou": "Ждёт вас",
  "work.done": "Готово",
  "work.reviewQueue": "Очередь приёмки",
  "work.filter": "Фильтр завершённых",
  "work.filter.all": "Все",
  "work.filter.accepted": "Приняты",
  "work.filter.closed": "Закрыты без результата",
  "work.filter.superseded": "Вытеснены",
  "work.filter.dropped": "Не нужны",
  "work.followupHint": "Задачи завершены, от них ничего не зависит. При необходимости добавьте продолжение.",
  "work.filter.followup": "Возможно, нужно продолжение",
  "work.totals": "Задач: {tasks} · принято: {accepted}",
  "work.lane": "Дорожка: {lane}",
  "work.laneClear": "Показать все дорожки",
  "work.critical": "Критический путь: {path}",
  'review.failed': 'Ошибка',
  'review.cancelled': 'Остановлен',
  'review.multipleAttempts': 'Несколько попыток',
  'review.sources': 'Показать источники',
  'review.measurements': 'Показать измерения',
  'review.rates': 'Показать тарифы',
  'review.noIssues': 'Проблемы не зафиксированы',
  'review.lastActivity': 'Последнее действие',
  'review.latestDecision': 'Последнее решение',
  'review.blockedDependants': 'зависимых задач заблокировано',
  'review.stale': 'Показаны последние данные от {time}; обновление не удалось',
  'review.progress': 'Прогресс',
  'review.scope': 'Весь план',
  'review.updated': 'Обновлено {time}',
  'review.resultAccepted': 'Принято с результатом',
  'review.awaitingCount': 'ждут приёмки',
  'review.openCount': 'открыто',
  'review.negativeCount': 'закрыто без результата',
  'review.supersededCount': 'вытеснено',
  'review.disputedCount': 'спорных',
  'review.legacyAcceptedCount': 'старых приёмок без типа результата',
  'review.elapsed': 'Прошло с начала плана',
  'review.notStarted': 'Не начато',
  'review.inferredEnd': 'Конец определён по завершённым задачам',
  'review.wallClock': 'Календарное время',
  'review.overlapNote': 'Работа и ожидание приёмки могут идти одновременно.',
  'review.history': 'История прогресса',
  'review.noHistory': 'История недоступна',
  'review.accounting': 'Деньги и квота',
  'review.coverage': 'Данные расхода есть для {known} из {total} запусков',
  'review.fixedFees': 'Стоимость подписок не распределена по запускам.',
  'review.pp': 'п. п.',
  'review.investigate': 'Разобраться',
  'review.historyIncomplete': 'История решений неполная',
  'review.updatesAvailable': 'Есть обновления',
  'review.tasks': 'Задачи',
  'review.search': 'Поиск задачи, воркера или запуска',
  'review.class': 'Класс задачи',
  'review.lane': 'Дорожка',
  'review.noLane': 'Без дорожки',
  'review.unclassified': 'Без класса',
  'review.group': 'Группировать по',
  'review.none': 'Без группировки',
  'review.sort': 'Сортировка',
  'review.sort.start': 'Начало',
  'review.sort.duration': 'Длительность',
  'review.sort.wait': 'Ожидание приёмки',
  'review.sort.cash': 'Расходы API',
  'review.sort.equivalent': 'Эквивалент',
  'review.sort.quota': 'Квота',
  'review.waitMin': 'Ожидание от (мин)',
  'review.durationMin': 'Длительность от (мин)',
  'review.from': 'Запуски с даты',
  'review.to': 'Запуски до даты',
  'review.reset': 'Сбросить фильтры',
  'review.moreFilters': 'Ещё фильтры',
  'review.noMatches': 'Подходящих запусков нет',
  'review.page': '{from}–{to} из {total}',
  'review.pageSize': 'Строк на странице',
  'review.quotaWindow': 'Окно квоты',
  'review.taskAttempt': 'Задача / попытка',
  'review.attempts': 'Попытки',
  'review.mixedClasses': 'Смешанные классы задач',
  'review.workerSort.tasks': 'Задачи с участием',
  'review.workerSort.attempts': 'Попытки',
  'review.workerSort.median': 'Медиана времени',
  'review.workerSort.acceptance': 'Доля принятых из проверенных',
  'review.workerSort.cash': 'Расходы API',
  'review.workerSort.equivalent': 'Эквивалент',
  'review.acceptedReviewed': 'Принято / проверено',
  'review.median': 'Медиана времени',
  'review.inspectContributions': 'Посмотреть вклад',
  'review.noClassRuns': 'Запусков этого класса нет',
  "review.summary": "Итоги плана",
  "review.lessThanMinute": "<1 мин",
  "review.planDuration": "Время плана",
  "review.workerTime": "Время воркеров",
  "review.yourWait": "Ожидание вас",
  "review.quota": "Квота потрачена",
  "review.spent": "Потрачено",
  "review.tokens": "Токены",
  "review.noRuns": "Запусков пока нет.",
  'review.pendingUsage': 'Ожидаются данные расхода', 'review.partial': 'Неполные данные', 'review.notApplicable': 'Не применимо', 'review.unavailable': 'Недоступно',
  'review.notCharged': 'Оценка, не списание', 'review.sharedQuota': 'Общее окно квоты; расход запуска не выделен', 'review.cash': 'Учтённые расходы API', 'review.quotaChange': 'Изменение квоты подписки', 'review.equivalent': 'Эквивалент по тарифам API',
  'review.input': 'Входные токены', 'review.output': 'Выходные токены', 'review.cacheRead': 'Чтение из кеша', 'review.cacheWrite': 'Запись в кеш', 'review.humanWait': 'Ожидание приёмки человеком', 'review.execution': 'Выполнение', 'review.decision': 'Решение человека', 'review.noDecision': 'Решение не записано',
  'review.noChange': 'Изменение не зафиксировано',
  'review.smallSample': 'Мало данных',
  'review.touched': 'Задачи с участием воркера',
  'review.workersClass': 'Воркеры по классам задач',
  'panel.app.screenLoading': 'Загружаем экран…', 'panel.app.screenLoadError': 'Экран недоступен.',
  'review.openRun': 'Открыть запуск', 'review.taskHistory': 'История задачи', 'review.expand': 'Развернуть', 'review.back': 'К запускам', 'review.backRun': 'Назад к запуску', 'review.backPanel': 'Назад к панели запуска', 'review.backTask': 'Назад к истории задачи', 'review.ledger': 'Журнал запуска', 'review.usageTime': 'Расход по времени', 'review.breakdown': 'Расход по шагам', 'review.unattributed': 'Расход без привязки к шагу', 'review.noStepUsage': 'Расход по шагам не записан', 'review.cumulative': 'Суммарно по попыткам', 'review.allAttempts': 'Показаны все попытки', 'review.previous': 'Назад', 'review.next': 'Далее', 'review.retry': 'Повторить', 'review.loading': 'Загружаем итоги…', 'review.stepsMissing': 'Сводка запуска есть; история шагов недоступна.', 'review.triggerUnknown': 'Причина запуска неизвестна', 'review.attempt': 'Попытка {n}', 'review.workerSum': 'Время воркеров · сумма запусков',
  'drill.worker': 'Воркер', 'drill.model': 'Модель', 'drill.attempt': 'Попытка', 'drill.start': 'Начало', 'drill.end': 'Конец', 'drill.elapsed': 'Длительность', 'drill.reason': 'Причина', 'drill.reasoning': 'Токены рассуждения', 'drill.reasoningIncluded': 'входят в выходные', 'drill.availability': 'Доступность данных расхода', 'drill.recorded': 'Записано', 'drill.reset': 'Сброс окна', 'drill.quotaSamples': 'Измерения окна аккаунта', 'drill.time': 'Время', 'drill.source': 'Источник', 'drill.increment': 'Приращение', 'drill.attributed': 'Расход с привязкой', 'drill.total': 'Итого за запуск', 'drill.unreconciled': 'Не сходится', 'drill.state': 'Текущий исход', 'drill.metric': 'Метрика / событие', 'drill.trigger': 'Причина запуска', 'drill.attemptRange': 'Попытки {from}–{to} из {total}', 'drill.decisionHistory': 'История решений', 'drill.mode.cash': 'Деньги', 'drill.mode.equivalent': 'Эквивалент', 'drill.mode.tokens': 'Токены', 'drill.mode.quota': 'Квота',
  'drill.execution.completed': 'Завершено', 'drill.execution.failed': 'Ошибка', 'drill.execution.cancelled': 'Остановлено', 'drill.execution.incomplete': 'Не доделан', 'drill.execution.running': 'Идёт', 'drill.trigger.initial': 'Первый запуск', 'drill.trigger.human_relaunch': 'Перезапуск человеком', 'drill.trigger.automatic_retry': 'Автоповтор', 'drill.decision.accepted': 'Принято', 'drill.decision.rejected': 'Возвращено',
  "review.runs": "Запуски",
  "review.steps": "Шагов: {count}",
  "review.decisionWait": "Ожидание решения: {duration}",
  "review.outcome.awaiting": "Ждёт приёмки",
  "review.outcome.running": "Идёт",
  "review.outcome.returned": "Возвращён",
  "review.outcome.noResult": "Без результата",
  "review.outcome.accepted": "Принят",
  "review.step.model": "Модель",
  "review.step.tool": "Инструмент",
  "review.step.edit": "Изменение файла",
  "review.step.check": "Проверка",
  "review.step.problem": "Проблема",
  "review.step.correction": "Исправление",
  "panel.app.graph": "Граф",
  "panel.app.overview": "Компактно",
  "panel.app.detail": "Подробно",
  "panel.app.attentionHint": "Линза «Требует внимания»: подсвечивает и ведёт по задачам, ничего не скрывая (n — следующая)",
  "panel.app.runningHint": "Линза «В работе»: подсвечивает задачи, которые сейчас выполняют воркеры (n — следующая)",
  "panel.app.readyHint": "Линза «Можно запускать»: подсвечивает и ведёт по задачам, ничего не скрывая (n — следующая)",
  "panel.app.reviewHint": "Линза «Приёмка»: подсвечивает и ведёт по задачам, ничего не скрывая (n — следующая)",
  "panel.app.queueEmpty": "Ждут вас",
  "panel.app.nextHint": "Следующая по линзе (n)",
  "panel.app.next": "Следующая по линзе",
  "panel.app.queueTitle": "Очередь приёмки",
  "panel.app.repo": "Репозиторий",
  "panel.app.status": "Статусы",
  "panel.app.view": "Вид",
  "panel.app.density": "Плотность",
  "panel.app.loading": "Загружаю планы…",
  "panel.app.noRepos": "Нет подключённых репозиториев. Добавьте путь в настройку плагина (repos) или в переменную CREWBOARD_REPOS.",
  "panel.app.disconnected": "нет связи, переподключаюсь…",
  "panel.app.attentionCount": "Требует внимания · {count}",
  "panel.app.runningCount": "В работе · {count}",
  "panel.app.readyCount": "Готовы · {count}",
  "panel.app.reviewCount": { one: 'Ждёт приёмки · {count}', few: 'Ждут приёмки · {count}', many: 'Ждут приёмки · {count}', other: 'Ждут приёмки · {count}' },
  "panel.app.lensListHint": "↑↓ выбор · Enter открывает · n следующий · Esc закрывает",
  "panel.app.queueCount": "Ждут вас · {count}",
  "panel.app.otherCount": " · ещё {count} в других планах",
  "panel.side.own": "этот чат ведёт план",
  "panel.side.other": "ведёт другой чат",
  "panel.side.none": "чат не назначен",
  "panel.side.decisionYours": "решение за вами",
  "panel.side.noChangesDecision": "Решения не правят файлы.",
  "panel.side.noChanges": "Изменений нет.",
  "panel.side.open": "Открыть",
  "panel.side.changes": "Изменения",
  "panel.side.worker": "воркер",
  "panel.side.workerAuto": "воркера выберут правила",
  "panel.side.unavailable": "Большой экран недоступен в этой версии dsh",
  "panel.side.newTaskHint": "Задачи в план добавляет агент или orch — экран покажет их сразу",
  "panel.side.confirmHint": "Подтвердите в окне macOS",
  "panel.side.goalAria": "Цель плана",
  "panel.side.goalPlaceholder": "Цель плана…",
  "panel.side.rejectPlaceholder": "Почему возвращаем: это увидит воркер",
  "panel.side.openScreen": "Открыть на большом экране",
  "panel.side.noPlan": "В этой папке нет плана.",
  "panel.side.noPlanHelp": "План — это цель и задачи вокруг неё. Заведите его здесь — задачи добавит агент или orch.",
  "panel.side.startPlan": "Завести план",
  "panel.side.counting": "Считаю изменения…",
  "panel.side.accept": "Принять",
  "panel.side.sendBack": "Вернуть…",
  "panel.side.sendBackNow": "Вернуть",
  "panel.side.cancel": "Отмена",
  "panel.side.run": "Запустить",
  "panel.side.bind": "Сделать этот чат оркестратором",
  "panel.side.calm": "Всё спокойно: ничего не ждёт приёмки и не идёт.",
  "panel.side.now": "Сейчас",
  "panel.side.openGraph": "Открыть граф",
  "panel.side.newTask": "Новая задача",
  "panel.side.review": "Ждёт вашей приёмки",
  "panel.side.ready": "Можно запускать",
  "panel.side.tab": "Оркестрация",
  "panel.side.noCwd": "Не удалось узнать рабочую папку чата — панели нечего показать.",
  "panel.side.connecting": "Соединяюсь с оркестрацией…",
  "panel.side.untracked": "За этой папкой оркестрация не следит.",
  "panel.side.untrackedHelp": "Папка чата не входит в воркспейсы dsh, не названа в настройке плагина (repos) и не в списке Crewboard. Добавь её через «+» у раздела «Репозитории» или `crewboard repo add`.",
  "panel.side.unreadable": "План в этой папке не читается.",
  "panel.side.files": { one: '{count} файл', few: '{count} файла', many: '{count} файлов', other: '{count} файла' },
  "panel.side.moreFiles": "… и ещё {count}",
  "panel.side.rejectAria": "Причина возврата задачи {id}",
  "panel.side.runningSince": "идёт {since}",
  "panel.side.tasks": { one: '{count} задача', few: '{count} задачи', many: '{count} задач', other: '{count} задачи' },
  "panel.side.reviewCount": "Ждёт вашей приёмки · {count}",
  "panel.side.readyCount": "Можно запускать · {count}",
  "settings.classShort.code": "код",
  "settings.classShort.design": "дизайн",
  "settings.classShort.review": "ревью",
  "settings.classShort.research": "исследование",
  "settings.kind.dsh": "DeepSeek через dsh",
  "settings.loadError": "Нет связи с сервером dsh",
  "settings.saveWorkerError": "Не удалось сохранить воркера",
  "settings.removeWorkerError": "Не удалось убрать воркера",
  "settings.workerRemoved": "Убрано: {workers}",
  "settings.notUsed": "не используется",
  "settings.profileEdit": "Измените профиль в ~/.config/crewboard/profiles.json",
  "settings.newName": "Новое имя",
  "settings.note": "Заметка",
  "settings.checking": "проверка…",
  "settings.checkError": "ошибка проверки",
  "settings.unchecked": "не проверено",
  "settings.cliMissing": "CLI не найден",
  "settings.signedIn": "вход выполнен",
  "settings.signinNeeded": "требуется вход",
  "settings.cliUnconfirmed": "CLI доступен · вход не подтверждён",
  "settings.modelExampleClaude": "Например, opus",
  "settings.modelExampleCodex": "Например, gpt-6-sol",
  "settings.checkForm": "Проверка…",
  "settings.checkFormError": "Ошибка проверки CLI",
  "settings.cliAvailable": "CLI доступен",
  "settings.checkManual": "Проверка запускается только по кнопке",
  "settings.saving": "Сохранение…",
  "settings.saved": "Сохранено",
  "settings.gripHint": "Перетащить мышью — или поднять пробелом и двигать стрелками",
  "settings.cliAccess": "Доступ к CLI",
  "settings.modelDsh": "Модель dsh",
  "settings.profileEditHint": "Измените профиль в ~/.config/crewboard/profiles.json.",
  "settings.emptyClass": "Список пуст — задачи этого класса не запустятся.",
  "settings.addWorkerOption": "+ добавить воркера",
  "settings.loading": "Загружаю правила оркестрации…",
  "settings.noRepos": "Нет подключённых репозиториев. Добавьте путь в настройку плагина (repos) или в переменную CREWBOARD_REPOS.",
  "settings.rename": "Переименовать",
  "settings.remove": "Убрать",
  "settings.save": "Сохранить",
  "settings.cancel": "Отмена",
  "settings.removeWorker": "Убрать воркера",
  'settings.presets': 'Пресеты',
  'settings.presetsHint': 'Выберите воркеров для каждого класса и расставьте их по приоритету.',
  'settings.allWorkers': 'Все воркеры',
  'settings.defaultPreset': 'По умолчанию — если другой пресет не выбран',
  'settings.newPreset': 'Новый пресет',
  'settings.whoRunsTasks': 'Кто выполняет задачи',
  'settings.thisRepository': 'Этот репозиторий · {repo}',
  'settings.repositoryHelp': 'Все планы репозитория используют его, пока план не выберет свой.',
  'settings.thisPlan': 'Этот план · {plan}',
  'settings.planHelp': 'Переопределяет репозиторий только для этого плана.',
  'settings.scopeRepository': 'Репозиторий',
  'settings.scopePlan': 'План',
  'settings.openOrchestration': 'Настройки оркестрации',
  'panel.app.partFailed': 'Эта часть экрана упала: {area}',
  'panel.app.stalled': 'Планы не пришли за 10 секунд, хотя связь с Crewboard есть.',
  'panel.app.stalledHint': 'Экран может держать сохранённое в этом браузере состояние (выбранный репозиторий, маршруты, выбор задач). Сброс удалит только сохранённые значения Crewboard для этого адреса.',
  'panel.app.resetState': 'Сбросить состояние экрана',
  'panel.app.partRetry': 'Повторить',
  'panel.app.workerSettingsIncomplete': 'Настройки воркеров повреждены: у классов {classes} нет списка воркеров, для них взят порядок по умолчанию. Репозитории это не затрагивает.',
  'panel.app.workerSettingsUnreadable': 'Настройки воркеров повреждены и не читаются. Репозитории показаны; выбор воркера и пресеты могут пропасть, пока файл не исправлен.',
  'panel.app.workerSettingsOpen': 'Открыть настройки воркеров',
  'panel.app.areaMain': 'основная область',
  'panel.app.areaSide': 'панель задачи',
  'panel.app.hostStale': 'Перезапустите dsh, чтобы завершить обновление',
  'panel.app.hostStaleHint': 'Плагин обновлён, но dsh ещё держит прежнюю хостовую часть. Перезапустите dsh, чтобы обе части совпали.',
  'settings.repositoryUnknown': 'Загрузка пресета репозитория…',
  'settings.inForce': 'Действует: {preset} — {source}',
  'settings.forceSource.plan': 'из плана',
  'settings.forceSource.repository': 'из репозитория',
  'settings.forceSource.builtin': 'встроенный',
  'settings.workerOrder': 'Порядок воркеров по классам задач',
  'settings.skippedWorker.disabled': '{worker} выключен на этой машине — пропущен',
  'settings.skippedWorker.unknown': '{worker} недоступен на этой машине — пропущен',
  'settings.builtin': 'Встроенный · только чтение',
  'settings.edit': 'Изменить',
  'settings.presetName': 'Имя пресета',
  'settings.createPreset': 'Создать пресет',
  'settings.presetDeletePrompt': 'Удалить «{label}»? Эти назначения будут сброшены:',
  'settings.presetRepoUse': 'Репозиторий: {repo}',
  'settings.presetPlanUse': '{repo} · план: {plan}',
  'settings.repositoryPreset': 'Пресет репозитория',
  'settings.planPreset': 'Пресет плана',
  'settings.repositoryOverridden': 'Пресет репозитория · план переопределяет',
  'settings.workersButton': 'Воркеры · {preset}: {worker}',
  'settings.asRepository': 'Как у репозитория ({preset})',
  'settings.noWorker': 'Нет доступного воркера',
  'settings.runManual': '{worker} · выбран для этого запуска',
  'settings.visibleUses': 'В подключённых репозиториях назначений не видно.',
  'settings.runSource': '{worker} · из пресета {source} «{preset}»',
  'settings.disabledLine': 'Недоступны на этой машине: {workers}',
  'settings.source.plan': 'плана',
  'settings.source.repository': 'репозитория',
  'settings.source.builtin': 'встроенного',
  "settings.workers": "Воркеры",
  "settings.workersHint": "Кого оркестратор может назначать на задачи. Выключенный воркер пропускается при «Авто» и не предлагается агенту.",
  "settings.checkAccess": "Проверить доступ",
  "settings.billing": "Оплата",
  "settings.usedIn": "Где используется",
  "settings.assign": "Назначать",
  "settings.extraHint": "Сохранённые профили, ещё не настроенные здесь. Включите после установки и входа в соответствующий CLI.",
  "settings.addWorker": "+ Добавить воркера",
  "settings.chooseModel": "Выберите модель",
  "settings.configureModels": "Настройте модели в Settings → Models.",
  "settings.devinModelHint": "Модель задаётся профилем Devin; здесь выбирать её не нужно.",
  "settings.chooseProfile": "Выберите профиль",
  "settings.check": "Проверить",
  "settings.add": "Добавить",
  "settings.orderTitle": "Порядок по классам задач",
  "settings.orderHint": "Задача без явного воркера идёт к первому включённому воркеру своего класса. Строку можно перетащить за ручку или поднять пробелом.",
  "settings.workerType": "Тип воркера",
  "settings.dshModel": "Модель dsh",
  "settings.modelId": "Идентификатор модели",
  "settings.workerName": "Имя воркера",
  "settings.position": "{label} — позиция {position} из {count}",
  "settings.grabbing": "{label} — перестановка: позиция {position} из {count}",
  "settings.cancelMove": "{label} — перестановка отменена",
  "settings.reorder": "Переставить {label}",
  "settings.raise": "Поднять {id}",
  "settings.lower": "Опустить {id}",
  "settings.removeFromClass": "Убрать {id}",
  "settings.addToClass": "Добавить воркера: {label}",
  "settings.workerAria": "Воркер {id}",
  "settings.actions": "Действия: {label}",
  "settings.deleteAria": "Подтверждение удаления {label}",
  "settings.removePrompt": "Убрать «{label}»?",
  "settings.removeUsedPrompt": "Убрать «{label}»? Он стоит в списках: {uses}. Из них он тоже будет удалён.",
  "settings.profileDelete": "Этот профиль отсутствует в реестре воркеров. Уберите его из сохранённых профилей.",
  "settings.disableReason": "Причина отключения: {id}",
  "settings.off": "отключён",
  "settings.extraCount": "Ещё профили · {count}",
  "settings.offReason": "нет лимитов",
  "settings.billing.subscription": "подписка",
  "settings.billing.promo": "промо",
  'settings.providerOther': 'Другие',
  'settings.worktrees.keep.dirty': 'есть незакоммиченные изменения',
  'settings.worktrees.keep.unmerged': 'ветка не влита в основную',
  'settings.worktrees.keep.running': 'задача выполняется',
  'settings.worktrees.keep.recent': 'копия принята недавно',
  'settings.worktrees.keep.rejected': 'задача не принята',
  'settings.worktrees.keep.orphan': 'бесхозная папка; проверить вручную',
  'settings.worktrees.policy.0': 'после приёмки',
  'settings.worktrees.policy.1': 'по команде',
  'settings.worktrees.policy.2': 'не убирать',
  'panel.run.seconds': { one: '{count} с', other: '{count} с' },
  'panel.run.minutes': { one: '{count} мин', other: '{count} мин' },
  'panel.run.hoursMinutes': { one: '{count} ч {minutes} мин', other: '{count} ч {minutes} мин' },
  'settings.usedPosition': '{class} №{position}',
  'notify.decision': '{id} «{title}» — решение за вами',
  'notify.ready': '{id} «{title}» готова — ждёт приёмки',
  'notify.planWaiting': 'в плане «{title}» ждут приёмки: {count}',
  'notify.waitingCount': { one: '{n} задача ждёт приёмки', few: '{n} задачи ждут приёмки', many: '{n} задач ждут приёмки', other: '{n} задачи ждут приёмки' },
  'notify.hide': 'Скрыть уведомление',
  'notify.open': 'Открыть',
  'notify.badge': 'Оркестрация',
  'notify.badgeWaiting': 'Оркестрация, ждут вас: {n} — {locations}',
  'panel.app.repoWaiting': { one: '{count} ждёт вас', few: '{count} ждут вас', many: '{count} ждут вас', other: '{count} ждут вас' },
  'panel.app.repoRunning': { one: '{count} идёт', few: '{count} идут', many: '{count} идут', other: '{count} идут' },
  'panel.app.repoMark': { one: '● {count} в {repo}', few: '● {count} в {repo}', many: '● {count} в {repo}', other: '● {count} в {repo}' },
  'actions.declined': 'Отменено в окне подтверждения',
  'actions.unknownRepo': 'Репозиторий не подключён к плагину',
  'actions.unknownTask': 'Задача не найдена',
  'actions.noWorktree': 'У задачи нет рабочей копии',
  'actions.running': 'Задача уже идёт',
  'actions.blocked': 'Задача ждёт зависимости',
  'actions.notReviewable': 'Часть задач уже не ждёт приёмки — обновите выбор',
  'actions.forbidden': 'Запрос отклонён сервером dsh',
  'actions.failed': 'Не получилось: {error}',
  'actions.noConnection': 'Нет связи с сервером dsh',
  'worktree.policy.afterAccept': 'после приёмки',
  'worktree.policy.onCommand': 'по команде',
  'worktree.policy.keepAlways': 'не убирать',
  'panel.task.tab.overview': "Обзор",
  'panel.task.tab.activity': "Активность",
  'panel.task.tab.changes': "Изменения",
  'panel.task.tab.contract': "Контракт",
  'panel.task.tab.notes': "Ваши действия",
  'panel.task.tab.links': "Связи",
  'panel.task.copyRemoveFailed': "Не удалось убрать копию. Обновите список и попробуйте ещё раз.",
  'panel.task.copyRemains': "Копия осталась на диске",
  'panel.task.serverUnavailable': "Нет связи с сервером dsh",
  'panel.task.aria': "Задача: {title}",
  'panel.task.start': "Запустить",
  'panel.task.worker': "Воркер",
  'panel.task.auto': "Авто — по правилам",
  'panel.task.steer': "Поправить…",
  'panel.task.stop': "Остановить",
  'panel.task.accept': "Принять",
  'panel.task.acceptDecision': "Принять решение",
  'panel.task.sendBackMore': "Вернуть…",
  'panel.task.blocker': "Что блокирует",
  'panel.task.noAction': "Закрыта — делать больше нечего.",
  'panel.task.autoHint': "Авто по классу «{class}» — запустится первый включённый воркер списка",
  'panel.task.classHint': "Класс задачи «{class}»",
  'panel.task.decisionHelpTitle': "Что делать",
  'panel.task.decisionAcceptHelp': "Принять решение — вы подтверждаете, что проверили и согласны.",
  'panel.task.decisionReturnHelp': "Вернуть… — укажите, что именно не так; причина уходит оркестратору.",
  'panel.task.confirmHint': "Подтвердите в окне macOS",
  'panel.task.mergeLead': 'Принята, ещё не слита в {into}.',
  'panel.task.mergeBase': 'базовую ветку',
  'panel.task.mergeHint': 'Crewboard не сливает сам. Когда будете готовы, выполните эти команды в терминале; зависящие задачи стартуют после слияния ветки.',
  'panel.task.mergeCopy': 'Скопировать команды',
  'panel.task.mergeCopied': 'Скопировано',
  'panel.task.merged': 'Принята и слита — делать больше нечего.',
  'panel.task.steerLabel': "Поправка воркеру",
  'panel.task.steerPlaceholder': "Что поправить: одна-две фразы",
  'panel.task.steersLabel': 'Поправки',
  'panel.task.steerState.queued': 'В очереди',
  'panel.task.steerState.sent': 'Отправлена',
  'panel.task.steerState.acknowledged': 'Подтверждена',
  'panel.task.steerState.abandoned': 'Не доставлена',
  'panel.task.steerState.refused': 'Отклонена',
  'panel.task.steerReason.run_finished': 'Запуск завершился до отправки поправки.',
  'panel.task.steerReason.run_failed': 'Запуск завершился с ошибкой до отправки поправки.',
  'panel.task.steerReason.cancelled': 'Запуск отменён до отправки поправки.',
  'panel.task.steerDelivered': "Поправка записана работающему воркеру. Проверьте эффект в ленте.",
  'panel.task.steerFailed': "Поправка не записана: {reason}",
  'panel.task.steerRefused': "Поправка отклонена: последний запуск в состоянии {state}. Ваш текст остался здесь.",
  'panel.task.relaunchWithCorrection': "Перезапустить с этой поправкой",
  'panel.task.continue': 'Продолжить',
  'panel.task.continueHint': 'Новый запуск в той же рабочей копии с указанием доделать работу, закоммитить её и отчитаться.',
  'panel.task.incompleteNoReport': 'Запуск закончился без отчёта. Не закоммичено файлов: {count}.',
  'panel.task.incompleteNoClaim': 'Запуск закончился без строки «Результат:». Не закоммичено файлов: {count}.',
  'panel.task.send': "Отправить",
  'panel.task.cancel': "Отмена",
  'panel.task.reasonLabel': "Причина возврата",
  'panel.task.decisionReasonPlaceholder': "Что именно не так: причину получит оркестратор",
  'panel.task.reasonPlaceholder': "Почему возвращаем: это увидит воркер",
  'panel.task.sendBack': "Вернуть",
  'panel.task.run': "Запуск",
  'panel.task.copyRemoved': "Копия убрана",
  'panel.task.copyBranch': "Скопировать ветку",
  'panel.task.baselineGreen': "Базовый прогон ✓ зелёный на {commit} · {at}",
  'panel.task.baselineRed': "Базовый прогон ✗ красный на {commit} · {at} — следующий запуск прогонит его снова",
  'panel.task.copyPath': "Скопировать путь рабочей копии",
  'panel.task.copyLink': 'Скопировать ссылку на задачу',
  'panel.task.removeCopy': "Убрать копию",
  'panel.task.pickRun': "Запуск",
  'panel.task.runNumber': "Запуск {count}",
  'panel.task.openLedger': "Открыть журнал запуска",
  'panel.task.details': "Подробности задачи",
  'panel.task.tab.changesCount': { one: "Изменения · {count}", few: "Изменения · {count}", many: "Изменения · {count}", other: "Изменения · {count}" },
  'panel.tabs.outcome.completed': "завершён",
  'panel.tabs.outcome.failed': "ошибка",
  'panel.tabs.outcome.cancelled': "остановлен",
  'panel.tabs.note.steer': "поправка",
  'panel.tabs.note.reject': "возврат",
  'panel.tabs.note.accept': "приёмка",
  'panel.tabs.note.comment': "заметка",
  'panel.tabs.note.check': "проверка",
  'feed.note.by': " ({by})",
  'feed.note.checkDue': "ждёт проверки: оркестратор проверит работу, прежде чем она дойдёт до вас",
  'feed.note.checkTaken': "проверяет{by}",
  'feed.note.checked': "проверено{by}: {note}",
  'feed.note.checkReturned': "возвращено воркеру{by}: {findings}",
  'feed.note.checkSkipped': "проверка пропущена: проверку оркестратором выключили",
  'feed.note.verdict': "вердикт: {verdict}",
  'feed.note.accepted': "принято человеком",
  'feed.note.evidence': "доказательства: {evidence}",
  'feed.note.superseded': "вытеснена задачей {by}",
  'feed.note.dropped': "закрыта как ненужная: {reason}",
  'feed.note.outsidePreset': "Запущено вручную вне пресета «{preset}»: {worker}",
  'feed.note.presetFallback': "Воркер {stale}, выбранный агентом, больше не входит в пресет «{preset}» для этого класса — запущен по порядку пресета: {worker}. Назначение снято.",
  'feed.note.steer': "{state} [{id}]{detail}: {message}",
  'feed.note.steer.delivered': "доставлена",
  'feed.note.steer.refused': "отклонена",
  'feed.note.steer.failed': "не доставлена",
  'feed.note.steer.abandoned': "не применена",
  'feed.note.worktree.removed': "Рабочая копия убрана после приёмки.",
  'feed.note.worktree.kept_recent': "Рабочая копия сохранена: одна из трёх последних принятых.",
  'feed.note.worktree.kept_unmerged': "Рабочая копия сохранена: ветка ещё не влита.",
  'panel.tabs.feedLoading': "Загружаю ленту…",
  'panel.tabs.humanDecision': "Это решение человека: воркера и модели у него нет — его закрывает ваша приёмка",
  'panel.tabs.ownWork': "Запуска воркера нет: эту работу оркестратор делает сам. Его отчёт и сводка — во вкладке обзора.",
  'panel.tabs.afterTasks': " после задач {tasks}",
  'panel.tabs.decisionAccepted': " Принято {time} ({text}).",
  'panel.tabs.noEvents': "Событий пока нет — воркер ещё не сделал ни одного шага.",
  'panel.tabs.noEventsFinished': "Шагов этого запуска нет в этой ленте — откройте журнал запуска выше.",
  'failure.rateLimited': "Лимит Claude исчерпан — сброс в {time}",
  'failure.rateLimitedNoTime': "Лимит Claude исчерпан",
  'failure.rateLimitedHint': "Запустите задачу снова после сброса.",
  'failure.interruptedStopped': "Супервизор запуска исчез; его воркер (pid {pid}) остановлен.",
  'failure.interruptedGone': "Супервизор запуска исчез; его воркер (pid {pid}) уже не работал.",
  'failure.interrupted': "Супервизор запуска исчез.",
  'panel.tabs.yourSteer': "Ваша поправка",
  'panel.tabs.fileDiff': "дифф файла",
  'panel.tabs.changesLoading': "Загружаю изменения…",
  'panel.tabs.noChanges': "Изменений нет: рабочая копия совпадает с точкой ветвления.",
  'panel.tabs.emptyDiff': "Пустой дифф.",
  'panel.preview.preview': 'Просмотр',
  'panel.preview.diff': 'Дифф',
  'panel.preview.fullSize': 'Открыть крупно',
  'panel.preview.close': 'Закрыть',
  'panel.preview.before': 'До',
  'panel.preview.after': 'После',
  'panel.preview.zoom': 'Нажмите для масштаба 1:1',
  'panel.preview.newTab': 'Открыть в новой вкладке',
  'panel.preview.sandbox': 'Изолированный просмотр. Исходный код — во вкладке «Дифф».',
  'panel.preview.rows': 'Строк: {count}',
  'panel.preview.cleaned': 'Копия задачи уже убрана.',
  'panel.preview.tooLarge': 'Файл превышает лимит просмотра 25 МБ.',
  'panel.preview.unavailable': 'Просмотр недоступен.',
  'panel.preview.loading': 'Загрузка просмотра…',
  'panel.preview.overlay': 'Ползунок сравнения',
  'panel.preview.sideBySide': 'Рядом',
  'panel.preview.slider': 'Сравнить до и после',
  'panel.preview.fontSample': 'Aa Bb Cc 123 · Съешь ещё этих мягких французских булок',
  'panel.preview.entitiesNotShown': 'объектов не показано',
  'panel.tabs.contractLoading': "Загружаю контракт…",
  'panel.tabs.noContract': "Контракта нет: воркер получит только название задачи.",
  'panel.tabs.truncated': "обрезано",
  'panel.tabs.runsLoading': "Загружаю запуски…",
  'panel.tabs.noRuns': "Задачу ещё не запускали.",
  'panel.tabs.runActive': "идёт",
  'panel.tabs.trace': "Трассировка",
  'panel.tabs.notesLoading': "Загружаю ваши действия…",
  'panel.tabs.noNotes': "Поправок и решений пока нет.",
  'panel.tabs.notesLabel': "Поправки и решения",
  'panel.tabs.before': "До этой задачи",
  'panel.tabs.noDependencies': "ни от чего не зависит",
  'panel.tabs.after': "После этой задачи",
  'panel.tabs.noDependents': "от неё ничего не зависит",
  'panel.tabs.fileCount': { one: "{count} правка", few: "{count} правки", many: "{count} правок", other: "{count} правки" },
  'panel.tabs.actionCount': { one: "{count} команда", few: "{count} команды", many: "{count} команд", other: "{count} команды" },
  'panel.decision.whatToCheck': "Что проверить",
  'panel.decision.contractTruncated': "Текст контракта обрезан",
  'panel.decision.noChecklist': "Оркестратор не оставил списка проверки",
  'panel.decision.whereToLook': "Куда смотреть",
  'panel.decision.countUnavailable': "Число изменённых файлов недоступно",
  'panel.decision.countLoading': "Сведения об изменённых файлах загружаются",
  'panel.decision.negativeResult': "Отрицательный результат",
  'panel.decision.disputedVerdict': "Вердикт спорный",
  'panel.decision.resultReceived': "Результат получен",
  'panel.decision.verdictUnavailable': "Вердикт недоступен",
  'panel.decision.modelUnknown': "Модель не указана",
  'panel.decision.filesUnavailable': "число файлов недоступно",
  'status.checking': "проверяет оркестратор",
  'check.pending': "Проверяет оркестратор — работа придёт к вам, когда он закончит",
  'check.checking': "Проверяет оркестратор — работа придёт к вам, когда он закончит",
  'check.checked': "Проверено оркестратором",
  'feed.note.started': "оркестратор взял в работу{by}",
  'panel.essence.preparing': "готовит оркестратор",
  'panel.essence.byOrchestrator': "в работе у оркестратора",
  'panel.essence.rootReady': "работа оркестратора · не начата",
  'panel.now.preparing': "Решение готовит оркестратор.",
  'panel.now.preparingHint': "Оно придёт к вам, когда оркестратор изложит варианты и свою рекомендацию.",
  'panel.now.byOrchestrator': "В работе у оркестратора",
  'panel.now.byOrchestratorHint': "Воркер здесь не работает: оркестратор делает это сам и отдаёт вам на приёмку с отчётом.",
  'panel.now.rootReady': "Эту работу оркестратор делает сам; он её ещё не начал.",
  'status.preparing': "готовит оркестратор",
  'status.byOrchestrator': "в работе у оркестратора",
  'status.orchestrator': "оркестратор",
  'check.prepared': "Подготовлено оркестратором",
  'panel.task.preparingHelp': "Готовит оркестратор — решение придёт к вам с вариантами и рекомендацией.",
  'panel.task.byOrchestratorHelp': "В работе у оркестратора — придёт к вам на приёмку, когда он отчитается.",
  'panel.task.rootReadyHelp': "Оркестратор начинает её сам (orch start {id}); воркер для неё не запускается.",
  'panel.task.rootOwner': "Собственная работа оркестратора — воркеру не передаётся",
  'report.orchestratorTitle': "Отчёт оркестратора",
  'panel.decision.preparing': "Решение готовит оркестратор",
  'queue.batch.unchecked': "Не проверено оркестратором",
  'check.acceptEarly': "Оркестратор ещё не закончил проверку — принять без неё?",
  'check.acceptAnyway': "Принять без проверки",
  'check.setting.title': "Оркестратор проверяет законченную работу",
  'check.setting.help': "Вкл.: законченная задача сначала идёт к оркестратору и приходит к вам с его сводкой. Выкл.: сразу к вам.",
  'check.setting.repository': "Проверка оркестратором в {repo}",
  'check.setting.plan': "Проверка оркестратором в этом плане",
  'check.setting.byChat': "Вкл., если у плана есть чат",
  'check.setting.asRepository': "Как в репозитории",
  'check.setting.on': "Вкл.",
  'check.setting.off': "Выкл.",
  'check.setting.inForceOn': "Действует: вкл. ({source})",
  'check.setting.inForceOff': "Действует: выкл. ({source})",
  'check.setting.source.plan': "план",
  'check.setting.source.repository': "репозиторий",
  'check.setting.source.chat': "у плана есть чат оркестратора",
  'check.setting.source.default': "чата оркестратора нет",
  'review.check.checked': "после проверки оркестратором",
  'review.check.unchecked': "до конца проверки оркестратором",
  'status.closedNegative': 'закрыта: результата нет',
  'panel.decision.closedNegative': " · Закрыта с отрицательным результатом",
  'panel.decision.noPredecessors': "Задач перед решением нет",
  'panel.decision.fileCount': { one: "{count} файл", few: "{count} файла", many: "{count} файлов", other: "{count} файла" },
  'panel.decision.totalChanged': { one: "Изменено {files} в задачах ниже", few: "Изменено {files} в задачах ниже", many: "Изменено {files} в задачах ниже", other: "Изменено {files} в задачах ниже" },
  'panel.decision.filesChanged': { one: "изменено {files}", few: "изменено {files}", many: "изменено {files}", other: "изменено {files}" },
  'panel.trace.lane.input': "ввод",
  'panel.trace.lane.model': "модель",
  'panel.trace.lane.tools': "инструменты",
  'panel.trace.lane.watch': "надзор",
  'panel.trace.fromStep': "С шага «{step}»: ",
  'panel.trace.steerFrom': "Поправить отсюда…",
  'panel.trace.relaunchFrom': "Перезапустить с шага",
  'panel.trace.steer': "Поправить…",
  'panel.trace.more': "Ещё",
  'panel.trace.relaunchHint': "Новый запуск в той же рабочей копии: воркер получит контракт, итог прошлого запуска и этот шаг.",
  'panel.trace.worker': "Воркер",
  'panel.trace.workerInstruction': "Указание воркеру",
  'panel.trace.instructionPlaceholder': "Что сделать иначе: одна-две фразы",
  'panel.trace.relaunch': "Перезапустить",
  'panel.trace.cancel': "Отмена",
  'panel.trace.started': "Запуск начат:",
  'panel.trace.selectStep': "Выберите шаг на дорожке — здесь появятся его время, длительность и итог.",
  'panel.trace.runStep': "Шаг запуска",
  'panel.trace.close': "Закрыть",
  'panel.trace.approximate': "Длительность приблизительная: воркер не сообщил, когда шаг закончился.",
  'panel.trace.feedHint': "Текст ответа и вывод команд — во вкладке «Лента» панели задачи.",
  'panel.trace.serverUnavailable': "Нет связи с сервером dsh",
  'panel.trace.statusRunning': "идёт · {time}",
  'panel.trace.statusFinishedTime': "завершён · {time}",
  'panel.trace.statusFinished': "завершён",
  'panel.trace.viewLanes': "Дорожки",
  'panel.trace.viewJournal': "События",
  'panel.trace.viewCompare': "Сравнить запуски",
  'panel.trace.compareUnavailable': "Сравнивать нечего: у задачи меньше двух запусков",
  'panel.trace.aria': "Трассировка запуска {id}",
  'panel.trace.viewLabel': "Вид трассировки",
  'panel.trace.backToPlan': "Назад к плану",
  'panel.trace.unavailable': "Трассировка недоступна: {error}",
  'panel.trace.loading': "Собираю шаги запуска…",
  'panel.trace.noSteps': "Запуск ещё не сделал ни одного шага — как только воркер начнёт, дорожки заполнятся.",
  'panel.trace.time': "Время",
  'panel.trace.timeBreakdown': "{total} · модель {model} · инстр. {tools}",
  'panel.trace.steps': "Шаги",
  'panel.trace.context': "Контекст",
  'panel.trace.contextUsage': "{used}k из {size}k",
  'panel.trace.noData': "нет данных",
  'panel.trace.nearbyMarks': { one: "{count} отметки рядом", few: "{count} отметки рядом", many: "{count} отметки рядом", other: "{count} отметки рядом" },
  'panel.trace.marksAt': { one: "{count} отметки, {time}", few: "{count} отметки, {time}", many: "{count} отметки, {time}", other: "{count} отметки, {time}" },
  'panel.trace.toolCalls': { one: "{count} инструментов", few: "{count} инструментов", many: "{count} инструментов", other: "{count} инструментов" },
  'panel.trace.step.input': "ввод",
  'panel.trace.step.model': "шаг модели",
  'panel.trace.step.read': "чтение",
  'panel.trace.step.edit': "правка",
  'panel.trace.step.cmd': "команда",
  'panel.trace.step.tool': "инструмент",
  'panel.trace.step.problem': "проблема",
  'panel.compare.outcome.completed': "завершён",
  'panel.compare.outcome.failed': "ошибка",
  'panel.compare.outcome.cancelled': "остановлен",
  'panel.compare.running': "идёт",
  'panel.compare.timeUnknown': "длительность известна не для обоих запусков",
  'panel.compare.slower': "второй медленнее в {factor}×",
  'panel.compare.faster': "второй быстрее в {factor}×",
  'panel.compare.sameTime': "по времени они почти равны",
  'panel.compare.sameSteps': "шагов поровну",
  'panel.compare.answer': "Разница: {time}, {steps}.",
  'panel.compare.traceUnavailable': "{label}: трассировка недоступна",
  'panel.compare.onlyOneRun': "Сравнивать нечего: у задачи один запуск.",
  'panel.compare.duration': "Длительность",
  'panel.compare.steps': "Шаги",
  'panel.compare.activity': "Чтение / правки / команды",
  'panel.compare.steers': "Поправки",
  'panel.compare.outcome': "Итог",
  'panel.compare.aria': "Сравнение запусков",
  'panel.compare.firstRun': "Первый запуск",
  'panel.compare.secondRun': "Второй запуск",
  'panel.compare.runSteps': "Шаги запуска {id}",
  'panel.compare.difference': "Разница",
  'panel.compare.what': "Что",
  'panel.compare.scaleHint': "Шкала общая: она идёт от начала каждого запуска и длится столько, сколько шёл более долгий.",
  'panel.compare.runLabel': { one: "Запуск {count} · {agent}", few: "Запуск {count} · {agent}", many: "Запуск {count} · {agent}", other: "Запуск {count} · {agent}" },
  'panel.compare.moreSteps': { one: "шагов больше на {count}", few: "шагов больше на {count}", many: "шагов больше на {count}", other: "шагов больше на {count}" },
  'panel.compare.fewerSteps': { one: "шагов меньше на {count}", few: "шагов меньше на {count}", many: "шагов меньше на {count}", other: "шагов меньше на {count}" },
  "welcome.eyebrow": "Оркестратор",
  "welcome.headline": "Разбейте работу на задачи и поручите их воркерам",
  "welcome.lead": "Сохраните цель в плане, поручите задачи воркерам и проверьте результат.",
  "welcome.setup": "Настройка",
  "welcome.progress": "{count} из 3",
  "welcome.workers": "Воркеры",
  "welcome.worker.ready": "готов",
  "welcome.worker.sign_in": "нужен вход",
  "welcome.worker.missing": "не найден",
  "welcome.worker.not_ready": "не готов",
  "welcome.worker.unchecked": "не проверен",
  "welcome.checking": "Проверка…",
  "welcome.openWorkers": "Открыть настройки воркеров",
  "welcome.preset": "Пресет",
  "welcome.presetValue": "{preset} · {source}",
  "welcome.choosePreset": "Выбрать пресет",
  "welcome.repository": "Проверка репозитория",
  "welcome.recipeFound": "Рецепт сохранён",
  "welcome.recipeMissing": "Рецепта пока нет",
  "welcome.recipeHelp": "Рецепт готовит копию для воркера и запускает базовую проверку перед работой.",
  "welcome.editRecipe": "Настроить рецепт",
  "welcome.start": "Как начать",
  "welcome.fromSpec": "Из спецификации",
  "welcome.fromSpecHelp": "Загрузите документ с диска, вставьте текст или выберите файл репозитория, затем проверьте черновик плана.",
  "welcome.fromChat": "Из чата",
  "welcome.fromChatHelp": "Попросите оркестратора составить черновик.",
  "welcome.chatPrompt": "Составь черновик плана для этого репозитория через orchestra_plan_draft. Покажи мне черновик для проверки перед утверждением.",
  "welcome.example": "Посмотреть пример",
  "welcome.exampleHelp": "Посмотрите задачи, работу воркера и проверку результата.",
  "welcome.emptyPlan": "Или пустой план",
  "welcome.goal": "Цель плана",
  "welcome.create": "Создать план",
  "welcome.cliHint": "В терминале: orch init",
  "welcome.addRepository": "Добавить репозиторий",
  "welcome.noRepos": "Откройте рабочую область dsh, выполните `crewboard repo add` в репозитории или добавьте путь в настройку repos.",
  "welcome.openSettings": "Открыть настройки",
  "welcome.recipeTitle": "Рецепт репозитория",
  "welcome.setupCommands": "Команды подготовки, по одной в строке",
  "welcome.baseline": "Команда базовой проверки",
  "welcome.timeout": "Лимит времени, секунды",
  "welcome.save": "Сохранить рецепт",
  "welcome.cancel": "Отмена",
  "welcome.pickSpec": "Выберите спецификацию",
  "welcome.specFromDisk": "С диска",
  "welcome.specPaste": "Вставить текст",
  "welcome.specFromRepo": "Из репозитория",
  "welcome.specDrop": "Перетащите файл сюда или выберите его на компьютере.",
  "welcome.specChoose": "Выбрать файл",
  "welcome.specChooseOther": "Выбрать другой файл",
  "welcome.specPicked": "{name} · {size}",
  "welcome.specTypes": "Подходят {types}, до {limit}. PDF и Word пока не поддерживаются — сохраните их как текст или вставьте текст.",
  "welcome.specPasteLabel": "Текст спецификации (можно Markdown)",
  "welcome.specPastePlaceholder": "# Цель\n\nЧто сделать, для кого и как проверить результат…",
  "welcome.specSavedTo": "Перед составлением черновика текст сохранится в репозитории в .orchestration/specs/.",
  "welcome.specSearch": "Поиск",
  "welcome.specSearchPlaceholder": "Имя файла или папки",
  "welcome.specNoMatch": "Нет подходящих файлов.",
  "welcome.specSaving": "Сохраняю…",
  "welcome.specUnsupported": "Такой тип файла не поддерживается. Подходят {types}.",
  "welcome.specTooLarge": "Спецификация весит {size}, а предел — {limit}.",
  "welcome.specOverLimit": "Спецификация больше {limit}.",
  "welcome.specEmpty": "Спецификация пустая.",
  "welcome.specBadName": "В имени файла не должно быть пути к папке.",
  "welcome.noSpecs": "В репозитории нет файлов Markdown или TXT.",
  "welcome.draft": "Составить черновик",
  "welcome.error": "Не удалось выполнить действие. Повторите попытку.",
  "welcome.exampleLabel": "Пример",
  "welcome.syntheticData": "Данные примера: запуски и расходы придуманы для знакомства и не входят в настоящие траты.",
  "welcome.removeExample": "Убрать пример",
  "welcome.tourNext": "Далее",
  "welcome.tourBack": "Назад",
  "welcome.tourSkip": "Пропустить",
  "welcome.tourDone": "Готово",
  "welcome.tourCount": "{step} из {total}",
  "welcome.tour1": "Посмотрите на выделенную задачу «Собрать экран приветствия». Стрелки показывают, чего она ждёт: макета и текста. Цвет — статус: принята, идёт, ждёт, возвращена.",
  "welcome.tour2": "«Работа» раскладывает задачи по статусам. Найдите работающего воркера, задачу на проверке, возвращённую и упавшую.",
  "welcome.tour3": "Это отчёт воркера с проверками. Прочитайте его, откройте запуск, чтобы увидеть шаги и стоимость, затем примите задачу или верните её.",
  "welcome.tour4": "Теперь вы: начните план со спецификации, чата или пустой цели здесь. Убрать пример можно в меню плана.",
  "welcome.showAgain": "Показать введение снова",
  "welcome.exampleImage": "Предпросмотр изображения примера",
  "welcome.unsetEnv": "Очистить переменные окружения, через запятую",
  "welcome.chatOpened": "Чат запущен. Откройте его диалог в dsh.",
  "welcome.exampleReadOnly": "Это пример · действия отключены",
  "welcome.returned": "Возвращена",
  'panel.ledger.summary': 'Шагов: {total}; сохранены шаги {from}–{to}',
  'panel.ledger.completeness.complete': 'Полная записанная история',
  'panel.ledger.completeness.partial': 'Записанная история может быть неполной',
  'panel.ledger.completeness.live': 'Текущая история',
  'panel.ledger.loaded': 'Загружено {count} из {total} шагов',
  'panel.ledger.more': 'Загрузить ещё 100 шагов',
  'panel.ledger.latest': 'К последнему шагу',
  'panel.ledger.loadError': 'Не удалось загрузить шаги. Повторите попытку.',
  'panel.ledger.loadOutput': 'Загрузить ещё ({size} символов)',
  'panel.ledger.zoomIn': 'Приблизить',
  'panel.ledger.zoomOut': 'Отдалить',
  'panel.ledger.rangeStart': 'Начало диапазона',
  'panel.ledger.rangeEnd': 'Конец диапазона',
  'panel.ledger.matches': 'Совпадений: {count}',
  'panel.ledger.searching': 'Загружаем остальные шаги…',
  'panel.ledger.open': 'Идёт',
  'panel.ledger.approximate': 'Приблизительных отметок: {count}',
  'panel.ledger.stepLink': 'Ссылка на этот шаг',
  'panel.ledger.title': 'Журнал запуска',
  'panel.ledger.totals': 'Итоги запуска',
  'panel.ledger.duration': 'Длительность',
  'panel.ledger.tokens': 'Токены вход / выход / кэш',
  'panel.ledger.money': 'Деньги / квота',
  'panel.ledger.wait': 'Ожидание решения',
  'panel.ledger.outcome': 'Итог',
  'panel.ledger.outcome.running': 'Идёт',
  'panel.ledger.outcome.completed': 'Завершён',
  'panel.ledger.outcome.failed': 'Ошибка',
  'panel.ledger.outcome.cancelled': 'Остановлен',
  'panel.ledger.outcome.accepted': 'Принят',
  'panel.ledger.outcome.awaiting': 'Ждёт приёмки',
  'panel.ledger.outcome.returned': 'Возвращён',
  'panel.ledger.overview': 'Обзор',
  'panel.ledger.clear': 'Сбросить фокус',
  'panel.ledger.timeline': 'Временная шкала запуска: стрелки выбирают шаги, Home и End переходят к краям, используйте кнопки диапазона и масштаба',
  'panel.ledger.contextLine': 'Записанное заполнение контекста',
  'panel.ledger.cumulativeTokens': 'Накопленные записанные токены',
  'panel.ledger.cumulativeCost': 'Накопленная записанная стоимость',
  'panel.ledger.search': 'Поиск записей',
  'panel.ledger.records': 'Записи запуска',
  'panel.ledger.inspector': 'Просмотр записи',
  'panel.ledger.copy': 'Копировать',
  'panel.ledger.turn': 'Ход {n}',
  'panel.ledger.context': 'Контекст',
  'panel.ledger.state': 'Состояние',
  'panel.ledger.input': 'Вход',
  'panel.ledger.output': 'Выход',
  'panel.ledger.select': 'Выберите запись для просмотра входа и выхода.',
  'panel.ledger.kind.request': 'Запрос',
  'panel.ledger.kind.model': 'Модель',
  'panel.ledger.kind.tool': 'Инструмент',
  'panel.ledger.kind.edit': 'Правка',
  'panel.ledger.kind.check': 'Проверка',
  'panel.ledger.kind.steer': 'Поправка',
  'panel.ledger.kind.problem': 'Проблема',
  'panel.ledger.kind.final': 'Итог',
  'settings.notify.title': 'Уведомления',
  'settings.notify.hint': 'Выберите, как crewboard сообщает, что работа ждёт вас. Уведомления в браузере показываются, только когда вкладка скрыта.',
  'settings.notify.browser': 'В браузере',
  'settings.notify.macos': 'macOS',
  'settings.notify.off': 'Выключены',
  'settings.notify.granted': 'Разрешение: разрешено',
  'settings.notify.denied': 'Разрешение: запрещено',
  'settings.notify.default': 'Разрешение: не запрошено',
  'settings.notify.unsupported': 'Разрешение: не поддерживается браузером',
  'settings.notify.allow': 'Разрешить уведомления в браузере',
  'settings.notify.blocked': 'Уведомления заблокированы в настройках сайта в браузере. Разрешите их там и попробуйте снова.',
  // rv6 · Review redesign: top band, progress, time, money, run rows and strip.
  'review.title': 'Итоги',
  'review.eyebrow': 'Обзор плана',
  'review.unavailableLoad': 'Данные итогов сейчас недоступны.',
  'review.newerSnapshot': 'Готов более новый снимок.',
  'review.needs.title': 'Нужно ваше решение',
  'review.needs.waiting': { one: '{count} решение ждёт вас', few: '{count} решения ждут вас', many: '{count} решений ждут вас', other: '{count} решения ждут вас' },
  'review.needs.none': 'Сейчас решений не требуется',
  'review.needs.more': { one: 'и ещё {count}', few: 'и ещё {count}', many: 'и ещё {count}', other: 'и ещё {count}' },
  'review.needs.running': { one: 'Выполняется {count} задача. Проверьте её или откройте запуск ниже.', few: 'Выполняются {count} задачи. Проверьте их или откройте запуск ниже.', many: 'Выполняются {count} задач. Проверьте их или откройте запуск ниже.', other: 'Выполняются {count} задачи. Проверьте их или откройте запуск ниже.' },
  'review.needs.idle': 'Сейчас ничего не выполняется. Откройте запуск ниже.',
  'review.needs.failed': { one: '{count} задача с ошибкой требует разбора; она не принята.', few: '{count} задачи с ошибкой требуют разбора; они не приняты.', many: '{count} задач с ошибкой требуют разбора; они не приняты.', other: '{count} задачи с ошибкой требуют разбора; они не приняты.' },
  'review.needs.showFailed': 'Показать запуски с ошибкой',
  'review.needs.unmerged': { one: 'Принято, не слито ({count}):', few: 'Принято, не слито ({count}):', many: 'Принято, не слито ({count}):', other: 'Принято, не слито ({count}):' },
  'review.needs.open': 'Открыть задачи',
  'review.needs.runs': 'К запускам',
  'review.progressTitle': 'Ход плана',
  'review.scopeLine': 'В плане {total} · вытесненные не считаются: {superseded}',
  'review.droppedLine': 'ненужные не считаются: {dropped}',
  'review.acceptedOf': '{total} принято',
  'review.bucket.accepted': 'Принято',
  'review.bucket.running': 'Выполняется',
  'review.bucket.ready': 'Готово к запуску',
  'review.bucket.queued': 'В очереди',
  'review.bucket.attention': 'Нужно разобраться',
  'review.verdicts': 'Из принятых: результат подтверждён — {result} · спорный — {disputed} · без результата — {negative} · исход не уточнён — {untyped} (старые решения)',
  'review.noTasks': 'В плане пока нет задач.',
  'review.notObserved': 'Нет данных',
  'review.noMeasurements': 'Измерений пока нет',
  'review.time.title': 'С первого запуска',
  'review.time.worker': 'Время воркеров',
  'review.time.wait': 'Ожидание приёмки',
  'review.unitsNote': 'Разные единицы, без общей суммы',
  'review.quotaNote': 'Разница до/после по окну аккаунта',
  'review.legacyQuota': 'У старых замеров нет окна',
  'review.noSubscriptionRuns': 'Нет запусков по подписке',
  'review.noApiRuns': 'Нет запусков с оплатой API',
  'review.moreWindows': { one: '+{count} окно', few: '+{count} окна', many: '+{count} окон', other: '+{count} окна' },
  'review.coverageLine': 'Измерено в {known} из {total} запусков',
  'review.coverageNone': 'Нет запусков, к которым это относится',
  'review.lastMeasured': 'последний запуск {time}',
  'review.runsTitle': 'Запуски для проверки',
  'review.statusFilter': 'Статус',
  'review.show': 'Показать',
  'review.direction': 'Порядок сортировки',
  'review.moneyPerRun': 'Показывать расход по запускам',
  'review.noRunsLong': 'Запусков пока нет. Шаги появятся, когда воркер начнёт работу.',
  'review.noMatchesLong': 'Нет подходящих запусков. Поиск и фильтры сохранены.',
  'review.clearSearch': 'Сбросить поиск',
  'review.investigation.waiting': 'задачи, которые ждут вас',
  'review.investigation.multiple': 'задачи с несколькими попытками',
  'review.status.running': 'Выполняется',
  'review.status.waiting': 'Ждёт вас',
  'review.status.failed': 'Ошибка',
  'review.status.stopped': 'Остановлено',
  'review.status.accepted': 'Принято',
  'review.status.returned': 'Возвращено',
  'review.status.completed': 'Завершено',
  'review.status.unknown': 'Исход неизвестен',
  'review.kind.model': 'Модель',
  'review.kind.tool': 'Инструменты',
  'review.kind.edit': 'Правки',
  'review.kind.check': 'Проверки',
  'review.kind.steer': 'Уточнения',
  'review.kind.request': 'Ввод человека',
  'review.kind.problem': 'Проблемы',
  'review.legend': 'Цвета шагов',
  'review.steps.aria': 'Записанные шаги: {counts}',
  'review.steps.note': { one: '{count} шаг', few: '{count} шага', many: '{count} шагов', other: '{count} шага' },
  'review.steps.complete': 'история полная',
  'review.steps.partial': 'история может быть неполной',
  'review.steps.live': 'идёт сейчас',
  'review.steps.none.complete': 'Шаги не записаны',
  'review.steps.none.partial': 'История шагов недоступна',
  'review.steps.none.live': 'Шагов пока нет',
  'review.steps.unavailable': 'Обзор шагов недоступен',
  'review.steps.timing.elapsed': 'по прошедшему времени',
  'review.steps.timing.sequence': 'по порядку; длительность не измерена',
  'review.steps.problems': { one: '{count} проблема', few: '{count} проблемы', many: '{count} проблем', other: '{count} проблемы' },
  'review.steps.route': 'Обзор шагов; выберите ячейку, чтобы открыть её первый шаг',
  'review.steps.cell': '{kind}: шагов — {count}, начиная с #{index}',
  'review.runDetail': 'Детали запуска',
  'review.close': 'Закрыть',
  'review.copyLink': 'Скопировать ссылку',
  'review.linkCopied': 'Ссылка скопирована',
  'review.runMoney': 'Деньги или квота',
  'review.allFacts': 'Все данные запуска',
} as const
