// Russian CLI texts. A separate file of the bundle (dist/dict-ru.js), loaded only when the CLI speaks Russian:
// an English run does not parse them. Keys match the English dictionary in i18n.ts.
export const ru: Record<string, string> = {

  'draft.started': 'Задание черновика {job} запущено ({agent}). Следить: {prog} plan draft job {job} --wait.\n',
  'draft.running': 'Задание черновика {job} выполняется ({run}).\n',
  'draft.needsRepair': 'Заданию черновика {job} нужна починка: ответ не соответствует схеме PlanDraft. Ответ сохранён; отправить его обратно с замечаниями: {prog} plan draft retry {job}.\n',
  'draft.failed': 'Задание черновика {job} не удалось: {error}. Повторить: {prog} plan draft retry {job}.\n',
  'draft.jobDropped': 'Задание черновика {job} отброшено; промпты и ответы остаются в .orchestration/draft-runs/{job}.\n',
  'draft.recovered': 'Восстановлено запусков черновиков: {count}.\n',
  'draft.noJobs': 'Заданий черновиков нет.\n',
  'draft.worker': 'Черновик напишет: {agent}\n',
  'draft.skipped': '  пропущен {agent}: {reason}\n',
  'draft.hint.login': 'Подсказка: {agent} не залогинен — войдите в его CLI и повторите.\n',
  'draft.hint.enable': 'Подсказка: {agent} отключён — включите его в настройках оркестрации или выберите другого воркера через -a.\n',
  'draft.hint.update': 'Подсказка: похоже, {agent} слишком старый для этого вызова — обновите его CLI и повторите.\n',
  'draft.saved': 'Черновик {id} сохранён. Проверьте: {prog} plan draft show {id}.\n',
  'draft.approveQuestion': 'Утвердить черновик {id} как новый план?',
  'draft.approved': 'Черновик {id} утверждён как новый план; теперь это текущий план.\n',
  'draft.error.invalid_id': 'Неверный идентификатор черновика: {id}',
  'draft.error.not_found': 'Нет черновика {id}.',
  'draft.error.plan_id_collision': 'План {id} уже есть: переименуйте черновик перед утверждением.',
  'draft.error.contract_id_collision': 'Контракт задачи {id} уже есть: переименуйте задачу в черновике.',
  'draft.error.draft_invalid': 'Черновик пока не годится: {id}.',
  'draft.error.bad_spec': 'Спецификация должна быть файлом внутри репозитория, не больше 256 КБ: {id}',
  'draft.error.not_repairable': 'Заданию черновика {id} повтор не нужен.',
  'draft.error.no_isolation': 'Задание черновика {id} не запущено: у этого воркера нет режима только для чтения, а временную копию git создать не удалось ({detail}). Выберите Claude или Codex через -a или запустите в git-репозитории.',
  'draft.blocked': 'Черновик {id} нельзя утвердить: сначала устраните цикл зависимостей или отсутствующую зависимость.',
  'draft.discarded': 'Черновик {id} удалён.\n',
  'draft.finding.cycle': 'Цикл зависимостей: {tasks}',
  'draft.finding.missing_dependency': 'Задача {task} зависит от отсутствующей задачи {dependency}',
  'draft.finding.missing_acceptance': 'У задачи {task} нет проверки приёмки',
  'draft.finding.empty_contract': 'У задачи {task} пустой набросок контракта',
  'draft.finding.file_collision': 'Задачи {tasks} обе заявляют файл {file}',
  'repo.usage': 'Использование: {prog} repo add [путь] | repo list | repo rm <путь> | repo preset <id> | repo default-base [<ветка>|--clear]',
  'repo.help': 'Репозитории (что показывает экран Crewboard)\n  {prog} repo add [путь]                    добавить этот репозиторий (или путь) в список Crewboard\n  {prog} repo list                          все места, которые показывает экран, и откуда они\n  {prog} repo rm <путь>                     убрать из списка Crewboard; файлы остаются\n  {prog} repo preset <id>\n  {prog} repo default-base [<ветка>|--clear]',
  'repo.added': 'Добавлен в список Crewboard: {root}\n',
  'repo.alreadyListed': 'Уже в списке Crewboard: {root}\n',
  'repo.registered': 'Добавлен в список Crewboard, экран его покажет: {root}\n',
  'repo.removed': 'Убран из списка Crewboard: {root}. Файлы и планы остаются на диске.\n',
  'repo.stillShown': 'Он остаётся на экране как: {sources}.\n',
  'repo.notListed.none': 'Нет в списке Crewboard: {root}. Смотри {prog} repo list.',
  'repo.notListed.dsh': 'Нет в списке Crewboard: {root} — воркспейс dsh; убери его в dsh.',
  'repo.notListed.profile': 'Нет в списке Crewboard: {root} задан в настройке repos плагина (профиль dsh или CREWBOARD_REPOS); измени его там.',
  'repo.listEmpty': 'Экран пока не показывает ни одного репозитория. Добавь: {prog} repo add\n',
  'repo.missing': 'нет на диске',
  'repo.source.dsh': 'воркспейс dsh',
  'repo.source.profile': 'настройка repos плагина',
  'repo.source.crewboard': 'список Crewboard',
  'repo.source.worktree': 'рабочая копия {main}',
  'repo.error.not_absolute': 'Не абсолютный путь: {path}',
  'repo.error.not_found': 'Нет папки {path}',
  'repo.error.not_directory': '{path} — файл, а не папка',
  'repo.error.not_git': '{path} — не Git-репозиторий и не рабочая копия',
  'repo.offScreen': 'Внимание: экран Crewboard не показывает этот план — {root} нет в его списке репозиториев. Исправить: {prog} repo add\n',
  'presets.active': 'Пресет: {label} (источник: {source})',
  'presets.source.builtin': 'встроенный',
  'presets.source.repository': 'репозиторий',
  'presets.source.plan': 'план',
  'presets.builtin': 'Все воркеры',
  'presets.unknown': 'Неизвестный пресет: {id}',
  'presets.saved': 'Пресет {id} сохранён.',
  'presets.removed': 'Пресет {id} удалён; переведены на «Все воркеры»: {places}',
  'presets.selected': 'Выбран пресет: {id}',
  'presets.usage': 'Использование: {prog} presets [list|add|set|rm] <id> --label "…" --code a,b --design a,b --review a,b --research a,b',
  'presets.planUsage': 'Использование: {prog} plan preset <id|--clear>',
  'presets.help': 'Пресеты\n  {prog} presets [list|add|set|rm]\n  {prog} repo preset <id>\n  {prog} plan preset <id|--clear>',
  'defaultBase.active': 'База по умолчанию: {branch} (источник: {source})',
  'defaultBase.source.default': 'база репозитория (origin/HEAD, иначе main/master)',
  'defaultBase.source.repository': 'настройка репозитория',
  'defaultBase.source.plan': 'настройка плана',
  'defaultBase.selected': 'База по умолчанию установлена: {branch}',
  'defaultBase.cleared': 'Переопределение базы по умолчанию снято.',
  'defaultBase.planUsage': 'Использование: {prog} plan default-base [<ветка>|--clear]',
  'defaultBase.help': 'База по умолчанию (bs1) — от неё ветвятся новые копии, а не от того, что случайно выбрано в основной копии\n  {prog} repo default-base [<ветка>|--clear]   без значения показывает действующую базу и её источник\n  {prog} plan default-base [<ветка>|--clear]   переопределяет только для этого плана\n  {prog} run <id> --base <ветка>               человек осознанно выбирает базу для одной задачи',
  "plan.chatLead": " · ведущий чат: {id}",
  "plan.archivedLabel": " (архив)",
  "plan.taskCount": " · задач: {count}",
  "plan.disabledReason": " — отключён: {reason}",
  "plan.class.code": "По готовому коду",
  "plan.class.design": "Проектирование и UI",
  "plan.class.review": "Ревью",
  "plan.class.research": "Исследование",

  "env.preflightDefaults": "Сохранённых профилей воркеров пока нет — проверяю встроенных и маршрутизируемых воркеров:\n",
  "env.gb": "ГБ",
  "env.mb": "МБ",
  "env.kb": "КБ",
  "env.sec": "с",
  "env.reused": " (уже был)",
  "env.baselineGreen": "базовый прогон ✓ {commit} {at}",
  "env.baselineRed": "базовый прогон ✗ {commit} {at}",
  "env.baselineUnknown": "базовый прогон неизвестен",
  "env.baselineKept": "✓ базовый прогон: {command} — зелёный на {commit} ({at}), не перезапускался\n",
  "env.dirty": "грязный",
  "env.clean": "чистый",
  "env.absent": "нет на диске",
  "env.accepted": "принята",
  "env.notAccepted": "не принята",
  "env.noWorktrees": "Рабочих копий нет.",
  "env.removable": "можно убрать",
  "env.dirtyDetails": "изменено: {modified}, новых: {untracked}: {paths} ({artefacts})",
  "env.artifactsOnly": "только артефакты сборки",
  "env.notArtifactsOnly": "есть и другие изменения",
  "env.orphanRegistered": " · бесхозная папка; Git ещё считает её worktree (только ручное решение)",
  "env.orphanUnknown": " · бесхозная папка; Git её не знает (автоматически не удаляется)",
  "env.copyRemoved": "рабочая копия убрана",
  "env.usagePrepare": "Использование: {prog} worktree prepare <id>",
  "env.usage": "Использование: {prog} worktree prepare|list|gc",
  "env.noTask": "Нет задачи {id}",
  "env.noWorktree": "У задачи {id} нет worktree",
  "env.forceQuestion": "Удалить {path} со всеми изменениями?",
  "env.branchKept": " (ветка {branch} оставлена: не слита)",
  "env.deleted": "✓ удалён {path}{branchNote}\n",
  "env.kept": "оставлен ({reason})",
  "env.failed": "· {id}: оставлен ({reason})\n",
  "env.copyRemovedLine": "✓ {id}: рабочая копия убрана\n",
  "env.nothingRemoved": "Ничего не убрано: {parts}.\n",
  "env.keptCount": "оставлено {count} — {reason}",
  "env.keep.dirty": "есть незакоммиченные изменения",
  "env.keep.unmerged": "ветка не влита в основную",
  "env.keep.running": "задача выполняется",
  "env.keep.recent": "копия принята недавно",
  "env.keep.rejected": "задача не принята",
  "env.keep.orphan": "бесхозная папка; проверить вручную",
  "slot.usage": "Использование: {prog} slot -- <команда…> | slot --set <n>",
  "slot.waiting": "ожидание слота проверки ({ahead} впереди)\n",
  "slot.set": "Слотов проверки: {n}.\n",
  "slot.show": "Слотов проверки: {n} (по умолчанию {default}).\n",
  "runs.reused": " (переиспользован)",
  "runs.noEvents": "Пока нет осмысленных событий.",
  "failure.rateLimited": "лимит исчерпан — сброс в {time}; запустите задачу снова после сброса",
  "failure.rateLimitedNoTime": "лимит исчерпан; запустите задачу снова после сброса",
  "failure.interruptedStopped": "супервизор запуска исчез; его воркер (pid {pid}) остановлен",
  "failure.interruptedGone": "супервизор запуска исчез; его воркер (pid {pid}) уже не работал",
  "failure.interrupted": "супервизор запуска исчез",
  "failure.authExpired": "воркер не залогинен или его вход истёк",
  "failure.diskFull": "на диске закончилось место; освободите место и повторите",
  "failure.setupFailed": "подготовка копии упала: {step}",
  "failure.setupFailedNoStep": "подготовка копии упала",
  "failure.baselineRed": "базовый прогон красный: {step}",
  "failure.baselineRedNoStep": "базовый прогон красный",
  "failure.workerError": "воркер упал",
  "attention.notStarted": "нет ни одного действия за {seconds} с после старта",
  "attention.running": "команда выполняется {count} мин — {command}",
  "attention.runningStuck": "возможно, зависла: команда выполняется {count} мин — {command}",
  "attention.stalled": "тишина {count} мин",
  "attention.stalledStuck": "возможно, зависла: тишина {count} мин",
  "attention.workerGone": "воркер исчез",
  "attention.loop": "повторяет одно и то же {count} раза: {action}",
  "attention.steerNoEffect": "после поправки {count} мин без шагов",
  "attention.incomplete.no_report": "запуск закончился без отчёта; не закоммичено файлов: {count}",
  "attention.incomplete.no_claim": "запуск закончился без строки «Результат:»; не закоммичено файлов: {count}",
  "attention.incomplete.left_uncommitted": "запуск отчитался о результате, но оставил незакоммиченными файлов: {count}",
  "attempt.outcome.failed": "упала",
  "attempt.outcome.cancelled": "остановлена",
  "attempt.outcome.incomplete": "закончилась недоделанной",
  "attempt.line": "последняя попытка {outcome}: {reason}",
  "attempt.action.retry": "повторить: {prog} run {id}",
  "attempt.action.login": "войти: {command}, затем {prog} run {id}",
  "attempt.action.loginDsh": "проверьте API-ключ в dsh: Settings → Models, затем {prog} run {id}",
  "attempt.action.show_output": "вывод: {log}",
  "attempt.action.continue": "{prog} continue {id}",
  "attempt.action.stop": "{prog} stop {id}",
  "runs.note.stop_requested": "запрошена остановка",
  "runs.note.stop_after_report": "остановка после финального отчёта: запуск завершается как выполненный",
  "runs.note.steer_after_finish": "поправка пришла после завершения запуска и не доставлена",
  "runs.note.sandbox_denied": "выход за песочницу отклонён: {detail}",
  "runs.dirtyQuestion": "В копии {id} остались незакоммиченные изменения прошлого запуска ({count}). Продолжить с ними [c], сбросить копию [r] или отменить [Enter]? ",
  "runs.quiet": "Всё спокойно.",
  "attention.head.review": "Ждут проверки ({count})",
  "attention.head.decision": "Открытые вопросы к вам ({count})",
  "attention.head.unmerged": "Принято, не слито ({count})",
  "attention.head.attention": "Упавшие или зависшие запуски ({count})",
  "attention.head.plan": "Другие планы ({count})",
  "attention.head.example": "Пример — не считается",
  "attention.checked": "проверено оркестратором",
  "attention.unchecked": "оркестратор не проверял",
  "attention.planWaiting": "ждут: {count}",
  "attention.total.plan": "Ждут вас: в этом плане {plan} · в этом репозитории {repo}",
  "attention.total.all": "Ждут вас: всего {all}",
  "attention.reason.review.one": "{count} задача ждёт ревью",
  "attention.reason.review.few": "{count} задачи ждут ревью",
  "attention.reason.review.many": "{count} задач ждут ревью",
  "attention.reason.review.other": "{count} задачи ждут ревью",
  "attention.reason.checkOff.one": "{count} ревью без проверки оркестратора",
  "attention.reason.checkOff.other": "{count} ревью без проверки оркестратора",
  "attention.reason.blocked.one": "{count} воркер заблокирован",
  "attention.reason.blocked.few": "{count} воркера заблокированы",
  "attention.reason.blocked.many": "{count} воркеров заблокированы",
  "attention.reason.blocked.other": "{count} воркера заблокированы",
  "attention.reason.decision.one": "{count} решение",
  "attention.reason.decision.few": "{count} решения",
  "attention.reason.decision.many": "{count} решений",
  "attention.reason.decision.other": "{count} решения",
  "attention.reason.failed.one": "{count} запуск упал или завис",
  "attention.reason.failed.few": "{count} запуска упали или зависли",
  "attention.reason.failed.many": "{count} запусков упали или зависли",
  "attention.reason.failed.other": "{count} запуска упали или зависли",
  "attention.reason.stuck.one": "{count} запуск может зависнуть",
  "attention.reason.stuck.few": "{count} запуска могут зависнуть",
  "attention.reason.stuck.many": "{count} запусков могут зависнуть",
  "attention.reason.stuck.other": "{count} запуска могут зависнуть",
  "attention.reason.workerGone.one": "{count} воркер исчез",
  "attention.reason.workerGone.few": "{count} воркера исчезли",
  "attention.reason.workerGone.many": "{count} воркеров исчезли",
  "attention.reason.workerGone.other": "{count} воркера исчезли",
  "attention.reason.unmerged.one": "{count} принята, не слита",
  "attention.reason.unmerged.other": "{count} приняты, не слиты",
  "attention.alarmsAll": "--alarms работает с одним репозиторием; уберите --all",
  "attention.planAll": "--plan называет план этого репозитория; уберите --all",
  "cost.jsonCsv": "--json и --csv нельзя сочетать",
  "cost.planAllPlans": "--plan называет один план; уберите --all-plans",
  "cost.planAllRepos": "--plan называет план этого репозитория; уберите --all-repos",
  "cost.badBy": "--by — одно из {keys} (получено «{by}»)",
  "cost.badDate": "--{flag} — не дата: «{value}»",
  "cost.orchestrator": "Оркестратор",
  "cost.orchestratorUnavailable": "недоступно (нет привязанной сессии dsh)",
  "cost.orchestratorPending": "сессий ожидают учёта dsh-bill: {count}",
  "cost.orchestratorSessions": "учтённых сессий: {count}",
  "cost.orchestratorScope": "вся сессия; не отнесено к плану",
  "cost.orchestratorCacheWrite": "запись кэша {tokens}",
  "cost.metricUnavailable": "нет данных",
  "cost.orchestratorWindowNote": "дата отбирает привязки; использование дано за всю сессию",
  "cost.codexRolloutConflict": "--codex-rollout нельзя сочетать с фильтрами затрат и режимами вывода",
  "runs.minutes": "мин",
  "runs.noMoney": "деньги: нет данных",
  "runs.cash": "деньги {usd}",
  "runs.estimate": "оценка ≈{usd}",
  "runs.noRunsInPlan": "В плане {plan} запусков нет.\n",
  "runs.runs": "{count} запуск(ов)",
  "runs.tokens": "токены {input} вход / {output} выход / {cache} кэш",
  "runs.quota": "квота +{percent}%",
  "runs.quotaWindows": "квота {list}",
  "runs.planning": "Планирование",
  "runs.pending": "{count} ждут учёта dsh-bill (перезапусти dsh web)",
  "runs.usageEvents": "Использование: {prog} events <id>",
  "runs.usageSteer": "Использование: {prog} steer <id> (--message \"…\" | --file f) [--mode auto|queue|interrupt] [--relaunch] [--skip-preflight]",
  "runs.usageStop": "Использование: {prog} stop <id>",
  "runs.usageRun": "Использование: {prog} run <id> [-a <профиль>|auto] [--base <ветка>] [--keep-changes|--reset-copy] [--verbose] [--force] — без -a запускается назначенный воркер задачи, иначе решает пресет. Агентам -a не передавать: вне пресета — отказ, спросите человека. --base задаёт базу копии осознанно; только человек, из интерактивного терминала — запрос агента отклоняется. --keep-changes / --reset-copy — ответ человека, что делать с копией, где прошлый запуск оставил незакоммиченные изменения. --verbose показывает необработанный отказ preflight каждого кандидата, а не только сводку по провайдерам. --force запускает контракт, всё ещё равный шаблону, либо с пустым разделом «Результат» или «Проверки»",
  "runs.noTask": "Нет задачи {id}",
  "runs.noRuns": "У задачи {id} ещё не было запусков",
  "runs.launched": "▶ {id}: {agent} запущен ({runId})\n  worktree: {path}{reused}\n  Проверь в первую минуту: {prog} events {id}\n",
  "runs.skipped": "  {agent} пропущен: {reason} → {chosen}\n",
  "runs.notStarted": "✗ {id} не запущена: {reason}",
  "runs.steered": "↻ поправка {steerId}: {state} для запуска {runId}. Проверь {prog} events {id}\n",
  "runs.steerState.queued": "В очереди",
  "runs.steerState.sent": "Отправлена",
  "runs.steerState.acknowledged": "Подтверждена",
  "runs.steerState.abandoned": "Не доставлена",
  "runs.steerState.refused": "Отклонена",
  "runs.steerReason.run_finished": "запуск завершён",
  "runs.steerReason.run_failed": "запуск завершён с ошибкой",
  "runs.steerReason.cancelled": "запуск отменён",
  "runs.steerRefused": "Поправка {steerId} отклонена: запуск {runId} в состоянии {state}. Текст сохранён. Для нового запуска: {prog} steer {id} --file \"{file}\" --relaunch.\n",
  "runs.steerRefusedPolicy": "Поправка {steerId} отклонена: запуск {runId} старше политики Crewboard «только API» для Claude, его канал аутентификации не проверен, поэтому новая порция ввода в него не доставляется. Текст сохранён. Остановите его и перезапустите, чтобы получить защищённый запуск: {prog} run {id} — или отправьте текст в новый запуск: {prog} steer {id} --file \"{file}\" --relaunch.\n",
  "runs.steerAbandoned": "Поправка {steerId} не отправлена в запуск {runId}: {reason}.\n",
  "runs.steerFailed": "Не удалось записать поправку {steerId} в запуск {runId}: {reason}\n",
  "runs.relaunched": "▶ {id}: новый запуск с поправкой ({runId})\n",
  "runs.usageContinue": "Использование: {prog} continue <id> [--skip-preflight] [--plan id]",
  "runs.continued": "▶ {id}: продолжен в той же рабочей копии с указанием доделать и отчитаться ({runId})\n",
  "runs.stopped": "■ {runId} остановлен\n",
  "trace.input": "ввод",
  "trace.model": "модель",
  "trace.tools": "инструменты",
  "trace.problem": "проблемы",
  "trace.sec": "с",
  "trace.turn": "ход",
  "trace.turnsFew": "хода",
  "trace.turnsMany": "ходов",
  "trace.tool": "инструмент",
  "trace.toolsFew": "инструмента",
  "trace.toolsMany": "инструментов",
  "trace.total": "всего",
  "trace.context": "контекст",
  "trace.usage": "Использование: {prog} trace <id> [--json]",
  "trace.noTask": "Нет задачи {id}",
  "trace.noRuns": "У задачи {id} ещё не было запусков",

  "help.body": "Crewboard — планы и запуски воркеров\n\nПлан\n  {prog} init [--goal \"цель\"]\n  {prog} plan list | new <id> --goal \"…\" | split <id> --from <план> --goal \"…\" --tasks a,b,c\n               | use <id> | archive <id> | unarchive <id> | rename <id> --goal \"…\"\n  {prog} plan restore [--plan <id>]          только человек: вернуть версию до последнего сохранения (plan.json.prev)\n  {prog} chat unbind <план>\n                                           несколько планов в репозитории; команды работают с текущим, --plan <id> — с другим\n  {prog} status [--json] [--plan id]\n  {prog} wait [--for decision|finished|check|any] [--tasks a,b] [--plan id] [--interval 15s] [--timeout 30m] [--json]\n                                           оркестратору: запустите в фоне; выход 0 — решение, конец запуска или шаг проверки, 2 — таймаут, 1 — ошибка\n                                           ждёт следующего изменения; с --tasks, если все задачи уже там (закончены, проверены,\n                                           решены или закрыты), сразу выход 0 и строки с пометкой «уже»; по умолчанию --timeout 30m\n  {prog} task add <id> --title \"…\" [--kind implement|review|research|decision|root] [--lane \"…\"]\n                [--deps a,b] [--worker <профиль>|auto] [--contract <файл> | --template] [--class code|design|review|research] [--backlog]\n                                           --template пишет заготовку контракта для заполнения; без контракта у задачи\n                                           метка «нужен контракт», и run её не запускает\n  {prog} task set <id> [--title] [--lane] [--deps a,b] [--worker <профиль>|auto] [--contract | --template] [--status backlog|ready]\n                [--kind implement|review|research|decision|root]   --kind: только открытая задача (не принятая и не вытесненная)\n                                           --worker: решает пресет — агентам не передавать; воркер вне пресета — отказ (выход 2),\n                                           если это не человек в терминале; auto снимает выбор\n  {prog} task show <id> [--plan id] [--json]  всё о задаче: статус, копия и diffstat, слияние, последний запуск,\n                                           отчёт, вердикт, проверка, заметки, проверки контракта; --json — целиком\n  {prog} verify <id>                         оркестратору: взять законченную работу на проверку (агентам можно)\n  {prog} verify <id> --done --note \"…\"      проверено: гейты, стенд, правки; обычную работу можно закрыть автоматически\n  {prog} verify <id> --attest --verdict result|negative|disputed --report <файл> --note <сводка>\n                                           независимая проверка результата; для положительной нужны чистый HEAD и актуальные проверки контракта\n  {prog} verify <id> --takeover --note \"…\"  взять сохранённую копию на проверку, даже если строка результата не распознана, без нового запуска\n  {prog} start <id>                          оркестратору: взять в работу root-задачу (свою работу)\n  {prog} verify <id> --done --note \"…\" [--report <файл>]\n                                           root-задача: сделано, уходит на приёмку; решение: подготовлено (варианты, рекомендация),\n                                           сохранённый incomplete-запуск: положительный отчёт после коммита; строка «Результат:»\n  {prog} verify <id> --return \"замечания\"   вернуть воркеру с замечаниями (новый запуск в той же рабочей копии)\n  {prog} verify <id> --run-checks            запустить <checks> контракта в копии задачи (окружение рецепта, таймаут на команду)\n                                           и записать результат рядом с заявлением воркера; выход 1, если проверка упала\n  {prog} verify --setting on|off|default [--scope plan|repo]\n                                           оркестратор проверяет законченную работу; по умолчанию — если у плана есть чат\n  {prog} accept <id>                         только человек (интерактивный терминал); принятую работу ещё нужно слить —\n                                           зависимые задачи ждут слияния, команды печатаются после приёмки\n  {prog} decision answer <id> --answer \"…\" --basis \"…\"\n                                           оркестратору: записать ответ, который человек уже дал в чате —\n                                           основание — сообщение, на которое он опирается; решение закрывается без повторного Accept\n  {prog} decision prepare <id> --reason \"…\"\n                                           оркестратору: вернуть открытое решение в подготовку — поручение\n                                           «изучи и предложи»; оно уходит из очереди человека до нового verify --done\n  {prog} merge <id> [--squash|--no-ff] [--yes] [--json]\n                                           только человек: слить принятую работу в её базу (по умолчанию коммитом слияния);\n                                           сначала примеряет и отказывает со списком конфликтных путей, потом убирает копию\n  {prog} mark-merged <id> --reason \"…\"      только человек: отметить принятую работу слитой, когда она попала в базу так,\n                                           что Crewboard этого не видит (перенесена руками, слита в другом клоне); git не трогается\n  {prog} reject <id> --reason \"…\" [--rerun [-a <профиль>]]\n                                           только человек: вернуть с причиной; причина уйдёт в промпт следующего\n                                           запуска; --rerun запускает его сразу (тот же воркер, если не задан -a)\n  {prog} supersede <id> --by <id>            только человек: вариант проиграл сравнение\n  {prog} drop <id> --reason \"…\"              только человек: закрыть ненужную задачу; в очередь она больше не вернётся\n\nЗапуски\n  {prog} run <id> -a <профиль> [--scope s] [--contract f] [--skip-preflight]\n                                           агенты dsh: -a dsh или -a dsh/<модель> (например dsh/deepseek-flash)\n  {prog} run <id>                            без -a — назначенный воркер задачи; если не задан, порядок пресета для класса\n                                           -a — выбор человека: агентам не передавать, вне пресета — отказ (выход 2);\n                                           нужен другой воркер — спросите человека. -a auto снимает выбор\n  {prog} run <id> --allow-unmerged            только человек: начать, хотя зависимость принята, но не слита —\n                                           в копии этой работы не будет\n  {prog} events <id>\n  {prog} trace <id> [--json]                трассировка: ходы, модель, инструменты, поправки\n  {prog} steer <id> (--message \"…\" | --file f) [--mode auto|queue|interrupt] [--relaunch] [--skip-preflight]\n  {prog} stop <id>\n  {prog} continue <id>                       запуск закончился без отчёта и с незакоммиченной работой:\n                                           новый запуск в той же копии с указанием доделать и отчитаться\n  {prog} attention [--all] [--json] [--alarms]\n                                           что ждёт человека — «Ждут вас» на экране: проверки, решения,\n                                           принятое, но не слитое, упавшие или зависшие запуски, другие планы; --alarms — только тревоги запусков\n  {prog} cost [--json|--csv] [--plan id|--all-plans] [--all-repos] [--since дата] [--until дата]\n              [--by worker|task|plan|class|effort|day]\n                                           по воркерам (по умолчанию) или по срезу: деньги (списано) и оценка\n                                           (по API-ценам для запусков по подписке), не складываются; квота по\n                                           окну, не суммируется между окнами; черновики и починки — отдельной строкой «Planning»\n\nВоркеры\n  {prog} workers [--all]                     провайдеры по строке (--all: все модели) и порядок воркеров по классам задач\n  {prog} workers add <id> --kind … --model … --label … | rm <id>\n  {prog} workers models <cli>                 модели, которые даёт CLI со входом, и их усилия\n  {prog} workers add-models <cli> --models <m,m> [--effort <e,e>]\n                                           по воркеру на модель и усилие (например claude/sonnet-5-high)\n                                           модели dsh регистрировать не нужно: -a dsh/<провайдер>/<модель>\n  {prog} workers disable <id> --reason \"…\" | enable <id> | route <class> <id,id,…>\n\nОкружение\n  {prog} preflight [-a <профиль>] [--probe] [--json]\n  {prog} worktree prepare <id> [--scope s]\n  {prog} worktree list\n  {prog} worktree gc [--yes]                 без --yes только показывает причины и размеры, ничего не убирает;\n                                           --yes убирает и перечисляет убранное или почему всё осталось\n  {prog} worktree gc --force <id>            --force только человек: убрать копию с изменениями\n  {prog} slot -- <команда…>                  дождаться свободного машинного слота проверки, затем выполнить <команду> (код выхода и вывод не меняются)\n  {prog} slot --set <n>                      задать число слотов проверки на машине; просто {prog} slot покажет его\n",
  "cli.noPlan": "Плана нет: выполни `{prog} init`.",
  "cli.planUnknown": "Плана {id} нет. Планы в репозитории: {list}",
  "cli.conflict": "План изменён снаружи — повтори команду.",
  "cli.invalidPlan": "Некорректный план: {error}",
  "cli.stateFile.no_space": "На диске нет места для {path}; освободите место и повторите.",
  "cli.stateFile.no_access": "Нет прав на запись {path}; проверьте владельца и права файла и его папки.",
  "cli.stateFile.read_only": "{path} на диске только для чтения; Crewboard не может туда писать.",
  "cli.lockBusy": "План занят: {lock} держит процесс {pid} на {host} с {at}; повторите чуть позже. Если процесс завис — остановите его.",
  "cli.lockBusyUnknown": "План занят: {lock} держит другой процесс; повторите чуть позже.",
  "cli.planCorrupt": "{file} повреждён и не читается; копия сохранена в {copy}. План только для чтения, пока его не исправят.",
  "cli.planCorruptRestore": "Вернуть версию до последнего сохранения: {prog} plan restore --plan {id}",
  "cli.restore.no_copy": "У плана {id} нет предыдущей версии: {prev} не существует.",
  "cli.restore.copy_unreadable": "Предыдущая версия плана {id} ({prev}) не читается как план; ничего не восстановлено.",
  "cli.readOnlySync": "Внимание: завершённые запуски не удалось записать, план показан как прочитан: {error}",
  "plan.restoreQuestion": "Вернуть план {id} к предыдущей версии (rev {rev}, сохранена {at}, задач: {count})? Нынешний файл станет предыдущей версией.",
  "plan.restored": "План {id} восстановлен (теперь rev {rev}).\n",
  "plan.badStatus": "Неизвестный статус «{value}». Статусы задачи: {statuses}. --status ставит только backlog или ready; приёмка — {prog} accept/reject.",

  "context.notGit": "Не git-репозиторий: запусти {prog} внутри репозитория.",
  "context.noConfig": "Профили воркеров находятся в ~/.config/crewboard/profiles.json.",
  "plan.usageTask": "Использование: {prog} task add|set|show <id> …",
  'show.usage': 'Использование: {prog} task show <id> [--plan id] [--json]',
  'show.kind': 'вид {kind}', 'show.class': 'класс {class}', 'show.status': 'статус {status}', 'show.worker': 'воркер {worker}', 'show.noWorker': 'воркер: решает пресет', 'show.lane': 'полоса {lane}',
  'show.deps': 'зависит от {ids}', 'show.dependents': 'нужна для {ids}', 'show.blockedBy': 'ждёт {ids}',
  'show.worktree': 'Рабочая копия', 'show.merge': 'Слияние', 'show.run': 'Последний запуск', 'show.report': 'Отчёт', 'show.verdict': 'Вердикт', 'show.check': 'Проверка оркестратора', 'show.notes': 'Заметки и решения', 'show.contract': 'Контракт',
  'show.path': 'путь {path}', 'show.branch': 'ветка {branch}, база {base}', 'show.noWorktree': 'рабочей копии нет',
  'show.diffstat': 'файлов: {count}, +{insertions} −{deletions} относительно {base}', 'show.diffstatEvidence': 'файлов: {count}, +{insertions} −{deletions} (по доказательствам запуска)', 'show.more': '… ещё {count}', 'show.uncommitted': 'в копии без коммита: файлов {count}',
  'show.merged': 'слита в {into} {at}{commit}', 'show.unmerged': 'принята, не слита в {into}; слить вручную:', 'show.orMerge': 'или, с теми же проверками: {prog} merge {id}', 'show.mergeConflicts': 'слияние в {into} даст конфликт в {count} файлах: {paths}', 'show.reviewClean': 'конфликтов с базой и другими задачами на приёмке нет',
  'show.running': '{run} · {agent} · идёт с {at}', 'show.runEnded': '{run} · {agent} · {outcome} {at}', 'show.runCount': 'всего запусков: {count}',
  'show.outcome.completed': 'завершён', 'show.outcome.failed': 'упал', 'show.outcome.cancelled': 'отменён', 'show.outcome.incomplete': 'не доделан',
  'show.reason.no_report': 'закончился без отчёта, без коммита осталось файлов: {count} — {prog} continue {id}', 'show.reason.no_claim': 'в ответе нет строки «Результат:», без коммита осталось файлов: {count} — {prog} continue {id}', 'show.reason.left_uncommitted': 'отчитался о результате, но оставил незакоммиченными файлов: {count} — {prog} continue {id}', 'show.reason.problem': 'причина: {text}', 'show.noRuns': 'запусков ещё не было',
  'show.reportFile': 'полный отчёт: {path}', 'show.reportEvents': 'полный ответ: {prog} events {id}', 'show.noReport': 'отчёта ещё нет',
  'show.check.pending': 'нужна, никто ещё не взял ({at})', 'show.check.checking': 'проверяет {by} с {at}', 'show.check.checked': 'проверено: {by}, {at}',
  'show.earlierNotes': '… ещё {count} раньше (все — в --json)', 'show.noNotes': 'нет',
  'show.checks': 'проверки:', 'show.noChecks': 'блока <checks> нет', 'show.noContract': 'контракта нет',
  'show.workerChecks': 'Отчёт воркера: {run}/{total} проверок контракта названы запущенными',
  'show.crewboardChecks': 'Проверки, запущенные Crewboard: прошло {passed}/{total} ({at}, {by})',
  'show.crewboardFailed': '✗ {command} · {outcome} · вывод: {path}',
  'show.crewboardExit': 'код {code}', 'show.crewboardTimeout': 'таймаут через {seconds} с',
  'show.checksMismatch': '⚠ Расхождение: воркер заявляет результат, а у Crewboard упали {commands}',
  'show.crewboardNone': 'Crewboard ещё не запускал проверки: {prog} verify {id} --run-checks',
  "plan.needTitle": "Нужен --title",
  "plan.statusOnly": "--status принимает только backlog или ready; приёмка — {prog} accept/reject",
  "plan.usageAccept": "Использование: {prog} accept <id> [--auto]",
  "plan.cancelled": "Отменено.",
  "plan.copyRemoved": "  рабочая копия убрана",
  "plan.usageReject": "Использование: {prog} reject <id> --reason \"…\" [--rerun [-a <воркер>]]",
  "plan.usageSupersede": "Использование: {prog} supersede <id> --by <задача-победитель>",
  "plan.usageDrop": "Использование: {prog} drop <id> --reason \"…\"",
  "plan.noTasks": "нет задач",
  "plan.noPlans": "Планов нет: {prog} plan new <id> --goal \"…\"",
  "plan.usageChat": "Использование: {prog} chat unbind <план>",
  "plan.sectionSubscriptions": "Подписки:",
  "plan.sectionDsh": "Через dsh (API) — ключи и модели в dsh:",
  "plan.sectionOther": "Другое / импортированное · {count}:",
  "plan.dshEmpty": "Моделей нет. Настройте их в dsh → Settings → Models.",
  "plan.noWorkers": "воркеров пока нет — войдите в CLI и добавьте модели",
  "plan.providerModels.one": "{count} модель",
  "plan.providerModels.few": "{count} модели",
  "plan.providerModels.many": "{count} моделей",
  "plan.providerModels.other": "{count} модели",
  "plan.providerUsed": "{used} в пресетах",
  "plan.providerReference": "Crewboard пока не запускает задачи на {name} — модели показаны для справки",
  "plan.workersAllHint": "Все модели: {prog} workers --all",
  "plan.workerOff": "отключён",
  "plan.otherDuplicate": "{copies} — тот же CLI, модель и усилие, что у {kept}; оставьте один: {prog} workers rm <id>",
  "plan.otherImported": "импортирован из старого инструмента",
  "plan.otherStale": "на этой машине этот id ничем не задан",
  "plan.noReason": "без причины",
  "plan.usageAddWorker": "Использование: {prog} workers add <id> --kind dsh|claude|codex|devin|opencode|cursor|gemini|grok --model <модель> --label <имя> [--transport <транспорт>] [--effort <усилие>] [--billing API|подписка|промо]",
  "plan.usageRemoveWorker": "Использование: {prog} workers rm <id>",
  "plan.statusFallback": "План",
  "cli.backendUnavailable": "Бэкенд воркера недоступен: {error}",
  "cli.legacyReadOnly": "Этот старый запуск доступен только для чтения. Для новых указаний создайте новый запуск.",
  "plan.degraded": " · ⚠ часть истории запусков недоступна",
  "plan.humanDecision": "◆ решение человека",
  "plan.exists": "План уже есть: {path}",
  "plan.created": "План создан: {path}\n",
  "plan.waiting": "ждёт {ids}",
  "plan.waitingMerge": "ждёт слияния {ids}",
  "plan.unmerged": "принята, не слита",
  "plan.noTask": "Нет задачи {id}",
  "plan.badKind": "Неизвестный --kind: {kind}",
  "plan.taskExists": "Задача {id} уже есть",
  "plan.templateOrContract": "Укажи либо --template (контракт из шаблона), либо --contract <файл>, не оба",
  "plan.templateOwnWork": "Задача вида {kind} не запускает воркера и не берёт контракт: --template — для задач воркеров",
  "plan.contractExists": "Файл контракта уже есть: {path} — подключи его через --contract",
  "plan.hasContract": "У задачи {id} уже есть контракт: {path}",
  "plan.templateWritten": "  контракт: {path} — допиши результат и проверки, затем {prog} run {id}\n",
  "plan.needsContractHint": "  нужен контракт: {prog} task set {id} --template (и допиши его) или --contract <файл>\n",
  'plan.needsContract': 'нужен контракт',
  "plan.badClass": "Неизвестный --class: {value} ({classes})",
  "plan.acceptNegative": "Закрыть задачу {id} с отрицательным результатом?{reason}",
  "plan.acceptDisputed": "Принять {id}? Расхождение: {mismatch}",
  "plan.factsMismatch": "факты расходятся с заявлением",
  "plan.acceptDecision": "Закрыть решение {id}? Это ваш ответ плану — задачи, которые его ждут, разблокируются.",
  "verdict.reason.blocked": "работа заблокирована",
  "verdict.reason.negative": "получен отрицательный результат",
  "verdict.reason.run_failed": "заявлен результат, но последний запуск завершился с ошибкой или отменой",
  "verdict.reason.no_files": "заявлен результат, но изменённых файлов нет",
  "verdict.reason.report_missing": "у задачи есть запуск, но отчёт отсутствует",
  "verdict.reason.claim_missing": "в отчёте нет явного заявления о результате",
  "plan.acceptQuestion": "Принять {id}?",
  "plan.accepted": "✓ {id} принята\n",
  "plan.acceptedUnmerged": "  ещё не слита в {into} — задачи, зависящие от {id}, ждут слияния. Когда будете готовы:\n{commands}\n",
  "plan.acceptUncommitted": "В копии {id} есть файлы без коммита ({count}): ветка задачи не содержит этот результат, и слияние его не принесёт. Команды, чтобы закоммитить их в ветке задачи, будут показаны после приёмки.",
  "plan.rejectQuestion": "Вернуть {id}: «{reason}»?",
  "plan.rejected": "↩ {id} возвращена\n",
  "plan.rejectRerunQuestion": "Вернуть {id}: «{reason}» и сразу запустить заново ({worker})?",
  "plan.rerunSameWorker": "тот же воркер",
  "plan.rejectedNextRun": "Причина уйдёт в промпт следующего запуска.\n",
  "plan.rerunCarries": "Причина — в промпте этого запуска, после контракта.\n",
  "plan.supersedeQuestion": "Отметить {id} вытесненной задачей {by}?",
  "plan.superseded": "⊘ {id} вытеснена задачей {by}\n",
  "plan.dropQuestion": "Закрыть {id} как ненужную: «{reason}»? В очередь она не вернётся.",
  "plan.dropped": "⊘ {id} закрыта как ненужная\n",
  "plan.statusDropped": "Задача {id} закрыта как ненужная: её статус не меняется.",
  "plan.split": "Отпочкован план {id}: перенесены {moved}; остались {kept}\n",
  "plan.new": "● {id}: новый план, теперь он текущий\n",
  "plan.current": "● текущий план: {id}\n",
  "plan.archived": "· {id} в архиве\n",
  "plan.unarchived": "○ {id} снова активен\n",
  "plan.chatUnbound": "Чат плана {plan} откреплён\n",
  "plan.workerSaved": "✓ воркер {id} сохранён в реестре\n",
  "plan.usageAddModels": "Использование: {prog} workers add-models <cli> --models <модель,модель> [--effort <усилие,усилие>]",
  "plan.usageModels": "Использование: {prog} workers models <cli>",
  "plan.modelsBuiltin": "У Claude Code нет своего списка моделей; здесь текущие модели Claude.\n",
  "plan.modelsUnknown": "{kind} не предлагает модель {model}; см. {prog} workers models {kind}",
  "plan.modelsEffort": "{kind} не принимает усилие «{effort}»; принимает: {efforts}",
  "plan.modelsAdded": "✓ добавлены: {workers}\n",
  "plan.modelsExisting": "· уже есть, оставлены как были: {workers}\n",
  "plan.workerRemoved": "✓ удалены воркер и псевдонимы: {workers}; ссылки в маршрутизации очищены\n",
  "plan.workerDisabled": "⊘ {id} отключён{reason}\n",
  "plan.workerEnabled": "✓ {id} включён\n",
  "plan.usagePlan": "Использование: {prog} plan list | new <id> --goal \"…\" | split <id> --from <план> --goal \"…\" --tasks a,b,c | use <id> | archive <id> | unarchive <id> | rename <id> --goal \"…\" | restore [--plan <id>]",
  "plan.usageWorkers": "Использование: {prog} workers [list] [--all] | add <id> --kind … --model … --label … | models <kind> | add-models <kind> --models <m,m> [--effort <e,e>] | rm <id> | disable <id> --reason \"…\" | enable <id> | route <class> <id,id,…> | import-porch <path>",
  "plan.porchImported": "✓ импортировано воркеров: {count} из старого инструмента: {ids} (помечены porch-import — выбирайте по id, пресет по умолчанию их сам не выбирает)\n",
  "plan.porchImportedNone": "Нечего импортировать из {path} — все его id уже сохранены\n",
  "plan.porchImportNotFound": "Нет такого файла: {path}",

  'verify.usage': 'Использование: {prog} verify <id> [--reopen | --takeover --note "причина" | --done --note "…" [--report <файл>] [--confirm] | --attest --verdict result|negative|disputed --report <файл> --note "…" | --return "замечания" [--skip-preflight] | --run-checks] [--plan id] | {prog} verify --setting on|off|default [--scope plan|repo]',
  'verify.taken': 'Проверяю {id}: человеку задача попадёт только после {prog} verify {id} --done --note "…".\n',
  'verify.checked': '{id} проверена: теперь ждёт человека, ваша сводка — над кнопкой «Принять».\n',
  'verify.returned': '{id} возвращена воркеру с замечаниями: запуск {runId}.\n',
  'verify.error.unknown_task': 'Нет задачи {id}.',
  'verify.error.not_in_review': 'Задача {id} — не законченная работа на проверке.',
  'verify.error.own_work': 'У задачи {id} нет запуска воркера для проверки: root-задача или решение завершается через {prog} verify {id} --done --note "…" [--report <файл>].',
  'verify.error.not_root': 'Задача {id} — не собственная работа оркестратора: {prog} start — для root-задач ({prog} task set {id} --kind root).',
  'verify.error.not_ready': 'Задача {id} не готова: её зависимости ещё не приняты или она в бэклоге ({prog} status).',
  'verify.error.closed': 'Задача {id} уже закрыта.',
  'verify.error.report_for_worker': 'Задача {id} принимает отчёт оркестратора только после передачи незакоммиченного incomplete-запуска; исходный отчёт воркера не меняется.',
  'verify.error.handoff_not_ready': 'Для завершения задачи {id} нужны положительный отчёт оркестратора и чистая закоммиченная копия.',
  'verify.error.report_unreadable': 'Не удалось прочитать файл отчёта: {file}',
  'verify.ownDone': '{id} сделана: теперь ждёт человека на приёмке, с вашей сводкой и отчётом.\n',
  'verify.prepared': '{id} подготовлено: когда зависимости приняты, решение ждёт человека с вашей сводкой.\n',
  'verify.alreadyChecked': '{id} уже проверена — ничего не изменилось, задача ждёт человека. Ваша сводка: {note}\nПроверить заново: {prog} verify {id} --reopen.\n',
  'verify.reopened': 'Проверяю {id} заново: задача ушла из очереди человека до {prog} verify {id} --done --note "…".\n',
  'verify.verdict': 'Вердикт: {kind}{reason} · {files}\n',
  'checks.start': '→ {index}/{total} {command}\n',
  'checks.waiting': '  ожидание слота проверки ({ahead} впереди)\n',
  'checks.passed': '  ✓ код {code} · {duration}\n',
  'checks.failed': '  ✗ код {code} · {duration}\n',
  'checks.timedOut': '  ✗ таймаут через {seconds} с\n',
  'checks.output': '  вывод: {path} ({size})\n',
  'checks.summary': 'Проверки, запущенные Crewboard: прошло {passed}/{total}. Записано рядом с фактами запуска; вердикт не меняется.\n',
  'checks.mismatch': '⚠ Расхождение: воркер заявляет результат, а у Crewboard эти проверки упали: {commands}\n',
  'verify.verdict.result': 'результат', 'verify.verdict.negative': 'отрицательный', 'verify.verdict.disputed': 'спорный',
  'verify.reason.blocked': 'работа заблокирована', 'verify.reason.negative': 'получен отрицательный результат', 'verify.reason.run_failed': 'заявлен результат, но последний запуск завершился с ошибкой или отменой', 'verify.reason.no_files': 'заявлен результат, но изменённых файлов нет', 'verify.reason.report_missing': 'у задачи есть запуск, но нет отчёта', 'verify.reason.claim_missing': 'в отчёте нет явной строки результата',
  'verify.files': 'изменено файлов: {count}',
  'verify.confirmQuestion': 'Всё равно отметить {id} проверенной? Человек увидит этот вердикт над кнопкой «Принять».',
  'verify.error.unconfirmed': 'Задача {id} не отмечена проверенной: вердикт спорный или файлы не изменены. Если вы проверили именно это, повторите с --confirm; иначе {prog} verify {id} --return "замечания".',
  'start.usage': 'Использование: {prog} start <id> [--plan id] — взять в работу root-задачу (собственную работу оркестратора)',
  'start.started': '{id} в работе у оркестратора. Когда готово: {prog} verify {id} --done --note "…" [--report <файл>].\n',
  'plan.byOrchestrator': 'в работе у оркестратора',
  'plan.prepared': '✓ подготовлено оркестратором',
  'plan.acceptOwnUnchecked': 'Оркестратор ещё не отчитался по {id} и не подготовил её — приёмка пропустит его проверку.',
  'plan.preparing': 'готовит оркестратор',
  'plan.lastRunFailed': 'последний запуск упал',
  'plan.running': 'команда выполняется {count} мин — {command}',
  'plan.stalled': 'тишина {count} мин',
  'plan.rootTask': '▣ работа оркестратора',
  'plan.kindClosed': 'Задача {id} — {status}: тип закрытой задачи не меняется.',
  'verify.error.no_note': 'Нужна короткая сводка: --note "…" (гейты, стенд, правки) или --return "замечания".',
  'verify.offQuestion': 'Выключить проверку оркестратором? Законченная работа придёт к вам непроверенной.',
  'verify.settingOn': 'Оркестратор проверяет законченную работу (источник: {source}).\n',
  'verify.settingOff': 'Законченная работа сразу приходит к вам (источник: {source}).\n',
  'verify.source.plan': 'план', 'verify.source.repository': 'репозиторий', 'verify.source.chat': 'у плана есть чат оркестратора', 'verify.source.default': 'по умолчанию',
  'plan.checking': '◌ проверяет оркестратор',
  'plan.checked': '✓ проверено оркестратором',
  'plan.acceptUnchecked': 'Оркестратор ещё не закончил проверку {id} — принять без неё?',
  'check.state.pending': 'Ждёт проверки оркестратора',
  'check.state.checking': 'Оркестратор проверяет',
  'check.state.checked': 'Проверено оркестратором',
  'check.state.off.default': 'Без проверки оркестратора — выключена для этого плана (нет чата оркестратора)',
  'check.state.off.plan': 'Без проверки оркестратора — выключена для этого плана',
  'check.state.off.repository': 'Без проверки оркестратора — выключена для этого репозитория',
  'check.accept.checked': 'Проверено оркестратором{note}.',
  'check.accept.unchecked': 'Оркестратор ещё не проверил {id} — всё равно принять?',
  'check.accept.off.default': 'Для этого плана проверки оркестратора нет (нет чата оркестратора).',
  'check.accept.off.plan': 'Для этого плана проверки оркестратора нет (выключена для этого плана).',
  'check.accept.off.repository': 'Для этого плана проверки оркестратора нет (выключена для этого репозитория).',
  'check.runHint.default': 'Проверка оркестратора для этого плана выключена (нет чата оркестратора); `{prog} verify --setting on` включает её.\n',
  'check.runHint.plan': 'Проверка оркестратора для этого плана выключена (выключена для этого плана); `{prog} verify --setting on` включает её.\n',
  'check.runHint.repository': 'Проверка оркестратора для этого плана выключена (выключена для этого репозитория); `{prog} verify --setting on` включает её.\n',
  'verdict.short.result': 'результат получен', 'verdict.short.negative': 'отрицательный результат', 'verdict.short.disputed': 'спорно',
  'verdict.reason.deviation': 'воркер заявляет отклонение от контракта',
  'plan.acceptCaution': 'Принять {id}? Воркер заявляет отклонение от контракта.',
  'wait.badFor': '--for должен быть decision, finished, check или any', 'wait.badTime': '--interval и --timeout — секунды или с суффиксом: 15, 30s, 5m, 2h', 'wait.timeout': 'Истекло время ожидания изменений задач', 'wait.watching': 'Наблюдаю план {plan} в {repo}', 'wait.unreadable': 'План не читается, продолжаю наблюдать: {error}', 'wait.readable': 'План снова читается', 'wait.already': 'уже',
  'cli.planIncompatible.read': 'План {file} записан более новой версией Crewboard ({details}). Обновите Crewboard, чтобы открыть его.',
  'cli.planArchived': 'План {id} в архиве: ничего не записано. Чтобы всё же изменить его, укажите --plan {id}; или переключитесь на активный план: {prog} plan use <id>.',
  'cli.planIncompatible.write': 'В плане {file} есть данные более новой версии Crewboard, которые эта версия не сохранит ({details}). Ничего не записано; обновите Crewboard, чтобы менять план.',
  'status.ready': 'Можно запускать', 'status.critical': 'Критический путь',
  'status.unmerged': 'Принято, не слито ({count})',
  'help.title': 'Crewboard — планы и запуски воркеров', 'help.plan': 'План', 'help.runs': 'Запуски', 'help.workers': 'Воркеры', 'help.env': 'Окружение',
  'merge.usage': 'Использование: {prog} merge <id> [--squash|--no-ff] [--yes] [--auto] [--into branch] [--json] [--plan id]',
  'merge.both': '--squash и --no-ff исключают друг друга: выберите одно.',
  'merge.question': 'Слить задачу {id} ({branch}) в {into} в {root} {how}?',
  'merge.how.no-ff': 'коммитом слияния',
  'merge.how.squash': 'одним коммитом (squash)',
  'merge.done': '✓ {id} слита в {into}: {commit}\n',
  'merge.copy.removed': '  рабочая копия убрана\n',
  'merge.copy.kept_recent': '  рабочая копия оставлена: одна из трёх последних принятых\n',
  'merge.copy.kept': '  рабочая копия оставлена: {reason}\n',
  'merge.copy.gone': '',
  'merge.orMerge': '  Или пусть слияние сделает Crewboard, с теми же проверками: {prog} merge {id}\n',
  'markMerged.usage': 'Использование: {prog} mark-merged <id> --reason "…" [--plan id]',
  'markMerged.question': 'Отметить задачу {id} ({branch}) слитой в {into} в {root}, потому что: «{reason}»? Git не трогается; зависящие от {id} задачи смогут стартовать.',
  'markMerged.done': '✓ {id} отмечена слитой в {into} человеком\n',
  'status.conflictsBase': 'конфликт с {into} в {paths}',
  'status.conflictsTask': 'конфликт с задачей {id} в {paths}',
  'status.conflicts': 'Конфликты на приёмке ({count})',
  'status.sendBack': 'вернуть: {prog} reject {id} --reason "{text}"',
  'conflicts.sendBack': 'Обновите ветку до {into}: {list}. Влейте {into} в ветку (или перебазируйте на неё), разрешите конфликты, заново прогоните проверки и отчитайтесь.',
  'conflicts.itBase': 'она конфликтует с {into} в {paths}',
  'conflicts.itTask': 'она конфликтует с задачей {id} в {paths}',
  'cli.unknown': 'Неизвестная команда: {name}', 'cli.lang': 'Язык должен быть ru или en',
  'draft.show.goal': 'Цель: {goal} ({id})',
  'draft.show.tasks': 'Задачи:',
  'draft.show.task': '  {id} — {title} [{class}]{deps}',
  'draft.show.deps': ' (нужны: {ids})',
  'draft.show.questions': 'Открытые вопросы:',
  'draft.show.question': '  - {text}',
  'draft.show.noQuestions': 'Открытые вопросы: нет',
  'status.summary': 'Открыто {open} из {total}',
  'status.allHint': 'Все задачи, включая закрытые: {prog} status --all\n',
  'cli.unknownSuggest': 'Неизвестная команда: {name} — может, вы имели в виду {suggestion}?',
  'help.short': 'Crewboard — планы и запуски воркеров\n\nС чего начать\n  {prog} init [--goal "цель"]                       создать план\n  {prog} task add <id> --title "…" --template       добавить задачу с заготовкой контракта для заполнения\n  {prog} run <id>                                   запустить воркера на задаче\n  {prog} status                                     что готово, выполняется и ждёт вас\n  {prog} accept <id>                                принять законченную работу (только человек), затем {prog} merge <id>\n\nВсё целиком: {prog} help all\n',
  'draft.usage': 'Использование: {prog} plan draft --from <файл> [-a <воркер>] [--wait] | draft jobs | draft job <задание> [--wait] | draft retry <задание> [-a <воркер>] [--wait] | draft drop <задание> | draft recover | drafts | draft show <id> [--json] | approve <id> | discard <id>',
  "io.humanOnly": "Эта команда нужна человеку: если вы человек — запустите её в терминале.",
  "decision.usage": "Использование: {prog} decision answer <id> --answer \"…\" --basis \"…\" | {prog} decision prepare <id> --reason \"…\"",
  "decision.answered": "{id}: ответ человека записан — «{answer}».\n",
  "decision.answerRepeated": "{id}: этот ответ уже записан — ничего не изменилось.\n",
  "decision.prepared": "{id} вернулось в подготовку — оно убрано из очереди человека до новой подготовки ({prog} verify {id} --done --note \"…\").\n",
}
